### ISSUE TITLE
copy transcriptome html page to the analysis

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#105]
this was done for genome, not for transcriptome

**Comment by bradfordcondon** [comment]
assigning this to @jwest60

**Comment by bradfordcondon** [comment]
* First I need to create a field that will attach to **analysis**.    Similar to the genome
* Then you will paste the html from the drupal PAGE to the field.
* The page can be deleted after I or Abdullah confirm the page.

* separate issue: move the gnome stuff to attach to the **analysis** instead of **organism**

**Comment by jwest60** [comment]
| Name                                                             | URL                                                                                                           | Migrated | Notes                 |   |
|------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|----------|-----------------------|---|
| de novo Sugar Maple (Acer saccharum)                             | https://hardwoodgenomics.org/content/de-novo-sugar-maple-acer-saccharum                                       | Y        |                       |   |
| de novo Sugar Maple (Acer saccharum) - 010515                    | https://hardwoodgenomics.org/content/de-novo-sugar-maple-acer-saccharum-010515                                | N        | Missing from dev site |   |
| de novo White Alder (Alnus rhombifolia)                          | https://hardwoodgenomics.org/content/de-novo-white-alder-alnus-rhombifolia                                    | Y        |                       |   |
| de novo Red Alder (Alnus rubra)                                  | https://hardwoodgenomics.org/content/de-novo-red-alder-alnus-rubra                                            | Y        |                       |   |
| Unigene de novo American Chestnut (Castanea dentata) - AC454_v3  | https://hardwoodgenomics.org/content/de-novo-american-chestnut-castanea-dentata-ac454v3                       | Y        |                       |   |
| de novo Dogwood (Cornus florida)                                 | https://hardwoodgenomics.org/analysis/117                                                                     | Y        |                       |   |
| de novo American Beech (Fagus grandifolia) - ABall_v2            | https://hardwoodgenomics.org/content/de-novo-american-beech-fagus-grandifolia-aballv2                         | Y        |                       |   |
| de novo Green ash (Fraxinus pennsylvanica)                       | https://hardwoodgenomics.org/node/68249                                                                       | Y        |                       |   |
| Green Ash Ozone Treatment Experiment                             | https://hardwoodgenomics.org/content/de-novo-green-ash-ozone-treatment-experiment                             | Y        |                       |   |
| de novo Honey Locust (Gleditsia triacanthos)                     | https://hardwoodgenomics.org/node/68242                                                                       | Y        |                       |   |
| de novo Hydrangea (Hydrangea macrophylla)                        | https://hardwoodgenomics.org/analysis/120                                                                     | Y        |                       |   |
| de novo Black Walnut (Juglans nigra)                             | https://hardwoodgenomics.org/content/de-novo-black-walnut-juglans-nigra                                       | Y        |                       |   |
| de novo Black Walnut Ozone Treatment Experiment                  | https://hardwoodgenomics.org/content/de-novo-black-walnut-ozone-treatment-experiment                          | Y        |                       |   |
| de novo American sweetgum (Liquidambar styraciflua)              | https://hardwoodgenomics.org/content/de-novo-american-sweetgum-liquidambar-styraciflua                        | Y        |                       |   |
| de novo Tulip Poplar (Liriodendron tulipifera)                   | https://hardwoodgenomics.org/node/68243                                                                       | Y        |                       |   |
| de novo Tulip Poplar (Liriodendron tulipifera) - 120313          | https://hardwoodgenomics.org/content/de-novo-tulip-poplar-liriodendron-tulipifera-120313                      | N        | Missing from dev site |   |
| de novo Blackgum (Nyssa sylvatica)                               | https://hardwoodgenomics.org/content/de-novo-blackgum-nyssa-sylvatica                                         | Y        |                       |   |
| de novo Blackgum (Nyssa sylvatica) - 120313                      | https://hardwoodgenomics.org/content/de-novo-blackgum-nyssa-sylvatica-120313                                  | N        | Missing from dev site |   |
| de novo Black Cherry (Prunus serotina) Unigene v1.0 (Penn State) | https://hardwoodgenomics.org/content/de-novo-Black-Cherry-%28Prunus-serotina%29-Unigene-v1.0-%28Penn-State%29 | Y        |                       |   |
| de novo White Oak (Quercus alba) - WO454_v2                      | https://hardwoodgenomics.org/content/de-novo-white-oak-quercus-alba-wo454v2                                   | Y        |                       |   |
| de novo Northern Red Oak (Quercus rubra)                         | https://hardwoodgenomics.org/content/de-novo-northern-red-oak-quercus-rubra                                   | Y        |                       |   |
| de novo Northern Red Oak Ozone Treatment Experiment              | https://hardwoodgenomics.org/content/de-novo-northern-red-oak-ozone-treatment-experiment                      | Y        |                       |   |
| de novo Northern Red Oak (Quercus rubra) - RO454_v2              | https://hardwoodgenomics.org/content/de-novo-northern-red-oak-quercus-rubra-ro454v2                           | N        | Missing from dev site |   |
|                                                                  |                                                                                                               |          |                       |   |

**Comment by bradfordcondon** [comment]
great job joe.  I believe in every case where you wrote missing from dev site, the analysis is there but under a slightly different name.

Here is blackgum:

![screen shot 2018-01-25 at 8 24 03 am](https://user-images.githubusercontent.com/7063154/35390363-25998ff4-01a9-11e8-8478-bd9cca3b2d86.png)

In every case your missing analysis is going to be labeled something along the line of "treatments" or "ozone treatments"

**Comment by almasaeed2010** [comment]
How is it that the titles changed?

Also, should we make an issue on tripal about the change in URL "safe string" filter? i.e., how in tripal 2 it made everything lowercase but it stopped doing that in T3?

**Comment by bradfordcondon** [comment]
how did we do it for tripal 2?  If thats no longer an option then yeah make an issue for safe string.

im not too worried about the titles changing.  the blackgum ozone treatments analyss is analysis 62: the analysis.name column is Black Walnut Ozone Treatment.  The v2 site did not use teh chado analysis name but somethign else for those labels, i'd guess the node name.

**Comment by bradfordcondon** [comment]
here are the props for 62.

![screen shot 2018-01-25 at 8 31 51 am](https://user-images.githubusercontent.com/7063154/35390683-3d1ecf30-01aa-11e8-8738-7042204c4642.png)

basically yeah the modified name was not stored in chado.  Why not just change the chado.analysis.name?  that's totally fine.

**Comment by almasaeed2010** [comment]
Ok sounds like it was an issue on our end. 

btw, why does it say `delete_me`? Should we delete them?

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/issues/249  replace delete me with the actual info

**Comment by bradfordcondon** [comment]
OK, the offending "Treatments" were changed to a new bundle type: *Gene Expression Profiling*

Now I need to figure out where the missing analyses are.  They are in Chado...

**Comment by bradfordcondon** [comment]
I have **three** de novo red oak transcriptomes as the correct type in alchemist.

![screen shot 2018-01-25 at 9 39 15 am](https://user-images.githubusercontent.com/7063154/35393680-ac1ea6d6-01b3-11e8-8f61-fbbe49a75e04.png)

**Comment by bradfordcondon** [comment]
easy problem easy solution:  These analyses are **NOT IN the analysis organism table** because they have no **features to link them**.

**Comment by bradfordcondon** [comment]
All secondary transcriptomes have been associated with their organism via the analysis_organism table and will now appear on the organism page.

Some analysis types may still remain unconnected to organism

**Comment by bradfordcondon** [comment]
Checked Tulip Poplar and looks good to me!  CLosing issue.
