### ISSUE TITLE
evaluate analysis expression feature plotter

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#106]
How horribly broken is it?

Come up with like 5 cases and display that it works well, ok, poorly, or unusable.

Evaluate publishing live before fixing based on this.

**Comment by almasaeed2010** [comment]
Let's create a to-do list here with enhancements we'd like to have before launching live please.

**Comment by almasaeed2010** [comment]
- [ ] Sometimes the tooltip appears out-of-window (see the following on a smaller screen 13" macbook: http://160.36.205.61:8095/feature/Fraxinuspennsylvanica120313comp2c0seq1)

**Comment by almasaeed2010** [comment]
- [ ] Calculate band width based on the number of bars on the chart rather than the number of  groups
- [ ] Test drag and drop after the band width calculations have changed. If it doesn't work properly, we can just disable it.

**Comment by almasaeed2010** [comment]
- [ ] Legend appears out of svg frame on initial load [here](http://160.36.205.61:8095/feature/Fraxinuspennsylvanica120313comp2c0seq1).

**Comment by bradfordcondon** [comment]
With teh band width and drag and drop fixed, we now just want the tooltip adjusted.

Once that is done (or perhaps even without that) I think we're in agreement Analysis_expression module is ready to deploy live

**Comment by bradfordcondon** [comment]
minor remaining issues (legend) will convert to module - specific issues, but are not release blocking.
