### ISSUE TITLE
ferry genome descriptions from organism to genome assembly analysis bundle

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#109]
*  This way they match Transcriptome.
* need to rearrange the fields as a result

The descriptions are currently in their own field attached to organism: the field_reference_genome field.

We want to associate this with the analysis instead (for example, we might have multiple genome versions loaded).  Typically there should be only one genome per organism right now though, so it should be clear which genome assembly analysis to move the description to.

**Comment by bradfordcondon** [comment]
related issue #105

**Comment by jwest60** [comment]
so do the same thing i did with transcriptome with the reference genome field?

**Comment by bradfordcondon** [comment]
yes.  except this time around, the information is in that "reference genome" field in tripal 3 on the organism. so you want to move that html from there, onto the genome assembly analysis description.

**Comment by bradfordcondon** [comment]
### Chinese Chestnut

Good

### F excelsior
Missing the citation at the [bottom](https://hardwoodgenomics.org/content/European-Ash).  Please add, with hyperlink.


### English walnut J regia
http://160.36.205.61:8095/Genomeassembly/1963051
Please copy url links from  https://hardwoodgenomics.org/organism/Juglans/regia

### Q lobata

please fix url in first part:

```
Sork VL, Fitz-Gibbon ST, Puiu D, Crepeau M, Gugger PF, Sherman R, Stevens K,
Langley CH, Pellegrini M, Salzberg SL. href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5100847/">
First Draft Assembly and Annotation of the Genome of a California
Endemic
```

**Comment by jwest60** [comment]
done but i had no earthly idea how the URL for q lobata was supposed to be formatted, i took my best
