### ISSUE TITLE
essential pre-migration for live: store image of tripal 2

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#111]
Before we lose live, let's spin up a backup of the live site.  We can't predict where we are missing something and would want the old site as a reference, be it for URL linkouts or checking if osmething did or did not exist on live...

@almasaeed2010 suggests using the backup on dev to spin up a new site (cheaper then digital ocean way)

**Comment by almasaeed2010** [comment]
Snapshots of Droplet and Volumes have been created.

Note that these have a nonsignificant cost of $0.05 per GB
