### ISSUE TITLE
landing page search engine optimization SEO

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#112]
- [ ] Keyword-laden paragraph for species section

- [ ] Keyword-laden paragraph for tools section

- [ ] More informative H1 tags

- [x] keyword-laden h1 description

- [x] move NSF stuff to about page

- [ ] see all genomes/transcriptome page block 

see #85

**Comment by bradfordcondon** [comment]
@mestato sent out an email with her ideas, pasting below:

> Hardwood Genomics is an open-source database for comparative and functional genomics in forest trees and woody plant species. Available data include genomes, gene models, transcriptomes, gene expression, functional annotation, and genetic markers. 
> 
> For the text under species, we would need to discuss a stategy. Everything I come up with has a lot of key words that aren't meaningful to our data.
> 
> Text under tools:
> - Cross Site Search
> Search across multiple websites in our network all at once
> (I think we should list sites instad of "in our network", but otherwise fine)
> 
> - Gene Search
> Filter and download transcripts or genes by organism, description or sequence name
> 
> - Expression Visualization
> Use our interactive heat map to visualize gene expression from RNASeq experiments
> 
> - JBrowse
> (Complete change:
> View genomic sequences and tracks of annotated genes, variants and alignments of transcripts from other related species )
> 
> - Blast
> Use your own sequences to search for sequence similarity using the Basic Local Alignment Search Tool
> 
> - Explore Available Trees (Change to "Explore available species")
> Change tagline to: View a list of hardwood trees with available genomic data
>

**Comment by almasaeed2010** [comment]
Implemented Meg's suggestions as listed above

**Comment by mestato** [comment]
I like bradford's suggestion of changing BLAST text to "The Basic Local Alignment Search Tool (blast) allows you to search your own sequences for sequence similarity with nucleotide or protein sequences in our database."

**Comment by mestato** [comment]
As per BC's suggestion to add keywords, i think its easy to add angiosperm, genes, proteins, molecular to the top: 

Hardwood Genomics is an open-source database for comparative and functional genomics in forest trees and other angiosperm woody plant species. Available molecular data include genomes, genes, transcriptomes, proteins, gene expression, functional annotation, and genetic markers.

that still leaves: gene(singular) mRNA, transcripts, bioinformatics, tree (singular).

I don't like this as much but it hits more keywords. It feels disingenuous to list a bunch of sequence types that all are essentially the same thing (e.g. mRNA, transcript). what do you all think:

Hardwood Genomics is an open-source database for comparative and functional genomics in forest trees and other angiosperm woody plant species. We provide many types of molecular data including sequences, gene expression profiles, functional annotation, and genetic markers. Sequences types include genomes, genes, transcripts, mRNAs, assembled transcriptomes, and proteins.

**Comment by almasaeed2010** [comment]
I don't think plural vs singular matters in the eyes of search engines

**Comment by almasaeed2010** [comment]
So we need a tag line for `Species` and for `Tools`.  The goal here is to add more keywords to the home page and keep it relevant to the section at the same time.

**Comment by bradfordcondon** [comment]
These other sections are harder than thtey sound!


### Tools

>Hardwood Genomics offers a variety of bioinformatics tools to browse, search, visualize, and analyze genomic data.

### Species

>Hardwood Genomics hosts genomes, transcriptomes, and annotations for forest trees and other angiosperm woody plant species.

Ripped off from Meg's above.  I don't know how to do flesh this one out without just listing species.

**Comment by bradfordcondon** [comment]
From meg

Genomes
Reference genome sequence scaffolds, available to download or browse with gene annotations and other feature tracks.

Transcriptomes
Assemblies of transcripts from RNASeq data, with predicted protein coding sequences and functional annotation.

gSSRs
Simple sequence repeats with primers developed from low coverage DNA sequencing of 10 tree species, with amplification and polymorphism testing for a subset of species and markers.

BAC Libraries
A list of available Bacterial Artificial Chromosome (BAC) libraries and contact information for resource providers.

Chestnut Physical Map
Download the BAC-based chestnut physical map with BAC-end sequences, hybridized overgo markers, and integration with the genetic map.

**Comment by almasaeed2010** [comment]
Ok this is done (finally lol)
