### ISSUE TITLE
publishing analsyes resulted in duplicate url aliases

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#118]
resolving #90 resulted in duplicate urls for the ported gene features:

```
The URL alias, feature/snapmasked-cbr3scaffold4-abinit-gene-031, already exists for another page. Please ensure the pattern      [warning]
supplied on the MRNA Contig/polypeptide Edit Page under URL Path options is unique.
```
TO resolve:

* delete everything` that begins with `feature/` from the url_alias table
* rerun the url updater

``delete from url_alias where alias like 'feature/%';``

**Comment by almasaeed2010** [comment]
URL updater running for bio_data_7

We'll need to check and make sure it also runs for all other features before closing this.

**Comment by bradfordcondon** [comment]
hmm OK, we know we need to republish for two bundles: mrna and mrna_contig.

**Comment by bradfordcondon** [comment]
```[site http://160.36.205.61:8095] [TRIPAL WARNING] [TRPENTITY] The URL alias, feature/augustusmasked-scaffold23109-abinit-gene-01, already exists for another page. Please ensure the pattern supplied on the <a href="/admin/structure/bio_data/manage/bio_data_7" target="_blank">mRNA/polypeptide Edit Page</a> under URL Path options is unique.
WD trpentity: The URL alias,                                         [warning]
feature/maker-scaffold23726-snap-gene-03, already exists for another
page. Please ensure the pattern supplied on the mRNA/polypeptide Edit
Page under URL Path options is unique.```

**Comment by bradfordcondon** [comment]
this alias apperas once in url_alias, and it corresponds to `bio_data/4636`
However, that entity doesnt exist.

The way I see it we have two choices.

* EMPTY the url_alias table and rerun.

Last time we just deleted based on regexp?  If we missed some aliases that way, they'll give us this error and wont be updated

* Modify the code to ignore duplicate aliases

at line 187 of `TripalEntityController`, it checks if the alias already exists.  If it does, it gives you a warning based on the numbr of duplicates.  We could set it to ignore this and run the alias setting anyway.

I Think I like option 1 more, since we don't know what problems we'll have down the road with the extra, wrong, aliases in there.

**Comment by bradfordcondon** [comment]
This issue was cuased by long-standing duplicate uniquenames in the database for proteins/mrna loaded in.

```"feature_id","dbxref_id","organism_id","name","uniquename","residues","seqlen","md5checksum","type_id","is_analysis","is_obsolete","timeaccessioned","timelastmodified"
"2081892","\N","24","augustus_masked-scaffold23109-abinit-gene-0.1-mRNA-1","augustus_masked-scaffold23109-abinit-gene-0.1-mRNA-1","ATGATGAATGATGAGAGGGAAGTCTTGCCTCCAAATTCAGAGGTTACAGGTGCAGCTACTGCTATCACTGCTGCTTCTCATGGGATTGAAGTAGCAATGGAGTTTAAGCCAGTTGAGCATCCGAGTGAACCTCTTGACACTGATATACCAATTCAATGTCCATTACCTGAACCTTCAATTCTTAATGGAAGTGGTTATGAAGGTTTGGGATTGAGGAGACAAGGCTTTGAAGAAGGGGTGGGGGATAGAGTGAAGCTTTGGACTGATCATTGGTGTGGGGAGTCTCCTCTTCAACTGTCTTTTTCGAGCATGTTTGGGATTGCATCCAATAAAGAGGCATCGGTGGCCTCTTCTCTTGAACAGTTGGGGATTGAGGAGCGGAGAAGCTGGAATGTTCATTTTATTCGGAGACCTAATGATTGGAAAATGGGTGGGGTGGATGATTTTCTCCATACCTTGGGTTCTAATCTTCCTCCCACTGAAAATGTAGATCATATGCGATGGAAGTTGATAAAGAATGGGGACTTTGATATTTGTTTATTTTACAATAAGTGTCTCTGGAGGGAGCGCAATAGTAGGACGTTCGAGGACATGAAAAGCTCAGATGACCAGCTTTTGACCTCTCTTAGTGGCACTCTGTTTGATTGGTCTAGGGCTTGA","660","8428e5f74f32d613103fa896325dc0ba","145","f","f","2015-10-18 14:24:00.001719","2015-10-18 14:24:00.001719"
"2120221","\N","24","augustus_masked-scaffold23109-abinit-gene-0.1-mRNA-1","augustus_masked-scaffold23109-abinit-gene-0.1-mRNA-1","MMNDEREVLPPNSEVTGAATAITAASHGIEVAMEFKPVEHPSEPLDTDIPIQCPLPEPSILNGSGYEGLGLRRQGFEEGVGDRVKLWTDHWCGESPLQLSFSSMFGIASNKEASVASSLEQLGIEERRSWNVHFIRRPNDWKMGGVDDFLHTLGSNLPPTENVDHMRWKLIKNGDFDICLFYNKCLWRERNSRTFEDMKSSDDQLLTSLSGTLFDWSRA","219","5448cfde032bc2cdcf6783ac3388eaae","236","f","f","2015-10-19 19:03:57.064724","2015-10-19 19:03:57.064724"```

**Comment by almasaeed2010** [comment]
Almost done. Check tomorrow to make sure no errors happened. Log is at `/root/nohup.out`.

**Comment by bradfordcondon** [comment]
interestingly we still have duplicate feature names for protein/mrna in the case of chestnut (`augustus_masked-scaffold23109-abinit-gene-0.1-mRNA-1`)

BUT the constraint is that uniquename + the organism + the type must be unique.  

So, when we deleted the aliases, removed the protein bundle, and redid the aliases, we lost the error.
