### ISSUE TITLE
polypeptide issues

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#120]
http://160.36.205.61:8095/bio_data/2118902

* polypeptide sequence is not displayed under sequences
* relationship is describeing  polypeptide with no linkout (because we got rid of that feature page...)

![screen shot 2018-01-26 at 2 48 52 pm](https://user-images.githubusercontent.com/7063154/35457771-0cc169e8-02a8-11e8-9bc1-f1891af8b40a.png)
![screen shot 2018-01-26 at 2 47 50 pm](https://user-images.githubusercontent.com/7063154/35457774-0e953772-02a8-11e8-8553-d7245356d6f6.png)

**Comment by almasaeed2010** [comment]
There used to be a field specifically for polypeptide sequence but I can't find it anymore. Is that a Tripal core issue?

**Comment by bradfordcondon** [comment]
other features do indeed have polypeptides: for example, [F excelsior ](http://160.36.205.61:8095/feature/FRAEX38873v20001093901)
This means its likely the above example justh ad the sequences loaded in wrong.  But if thats the case, why does the relationship show up?

Organisms with polypeptide issues:

*  Cornus Florida

**Comment by almasaeed2010** [comment]
Organisms that don't have polypeptides:
- [ ] Acer_saccharum
- [ ] Alnus rhombifolia
- [ ] Alnus rubra

**Comment by bradfordcondon** [comment]
for hydrangea: COnfirmed that the polypeptides are still in chado.

**Comment by bradfordcondon** [comment]
issue confirmed: protein sequence field is not attached to mrna_contig

**Comment by bradfordcondon** [comment]
to fix this, i added this in both places that data__protein is described in tripal_chado.fields.inc :

```
      ($bundle->label == 'mRNA' or $bundle->label == 'transcript' or $bundle->label == 'MRNA Contig/polypeptide'))  {

```

highlights the risk of using the label field of the bundle instead of the base table...

**Comment by bradfordcondon** [comment]
http://160.36.205.61:8095/bio_data/2118902 resolved.

Let's take a look for other fields we might want though.
