### ISSUE TITLE
JBrowse back to site links are failing

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#123]
JBrowse links are now wrong since the url updater doesn't use the same method as tripal 2. 

To fix:
1- Make sure that all jbrowse track.json files filter the name of the feature the same way tripal 3 does (there are 6 json files to configure in `/data/apollo`)
2- Make sure that url_alias.alias is case insensitive

**Comment by almasaeed2010** [comment]
- [ ] English Walnut 
- [ ] Chinese Chestnut QTL
- [ ] Chinese Chestnut
- [ ] European Ash
- [ ] Valley Oak

**Comment by almasaeed2010** [comment]
So all done except for `augustus_results` in `Chinese Chestnut QTL`. I can't figure out where the features are! There is nothing in out entities table that had `augustus` in the name except for the markers and we set those correctly.

@bradfordcondon I am gonna need your help here. Probably need to screencast to explain.

**Comment by bradfordcondon** [comment]
no problem we can meet any time tomorrow
