### ISSUE TITLE
transcriptome browser etc needs to put archived version last

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#126]
Browsers need ot order archived entries last

see http://160.36.205.61:8095/organism/Nyssa/sylvatica
Could be achievable by name, otherwise by prop
![screen shot 2018-01-29 at 4 56 59 pm](https://user-images.githubusercontent.com/7063154/35536640-7803c8e4-0515-11e8-953f-85e147456c4d.png)

**Comment by bradfordcondon** [comment]
would this be appropriate to assign to @jwest60 ?  need to point him to the field

**Comment by almasaeed2010** [comment]
If it's by altering the title then yes

**Comment by almasaeed2010** [comment]
Yes he should be able to extract anything that has the word archived and pushes it back to the end of the array

**Comment by jwest60** [comment]
i think i have the code written correctly, i just need to test it, but i'm not sure how to go about it

**Comment by almasaeed2010** [comment]
Let's take a look at the code changes. Can you push your branch up?

**Comment by jwest60** [comment]
branch has been pushed

**Comment by almasaeed2010** [comment]
Unfortunately the fix didn't work

**Comment by bradfordcondon** [comment]
Clarification:  this still needs to get done please @jwest60 

I have *renamed* the analysis start with archived, but the sorting still needs to be implemented.

**Comment by jwest60** [comment]
i updated the branch on monday with a fix, is that one still not working? not sure if it had been tested yet

**Comment by bradfordcondon** [comment]
Looks good for Nyssa.
![screen shot 2018-02-07 at 1 13 10 pm](https://user-images.githubusercontent.com/7063154/35933477-c47978be-0c08-11e8-9029-e0246d97aa15.png)

also verified in Q rubra.  http://160.36.205.61:8095/organism/Quercus/rubra?tripal_pane=group_analyses

**Comment by almasaeed2010** [comment]
So this works for analysis details tab but not for transcriptome. So @jwest60 you will need to implement the same method for field: https://github.com/statonlab/tripal_manage_analyses/blob/master/includes/TripalFields/local__transcriptome_viewer/local__transcriptome_viewer_formatter.inc

**Comment by almasaeed2010** [comment]
And probably the same thing again for local__genome_browser 👍

**Comment by jwest60** [comment]
just updated the branch for transcriptome and and genome, just needs to be tested

https://github.com/statonlab/tripal_manage_analyses/tree/sort_archived

**Comment by bradfordcondon** [comment]
@jwest60 unfortunately this breaks it:

![screen shot 2018-02-14 at 4 50 51 pm](https://user-images.githubusercontent.com/7063154/36230072-4608f492-11a7-11e8-93e2-39ae1c494bf6.png)


(sorry it took me a week to ping this, maybe @ me next time)

**Comment by jwest60** [comment]
@bradfordcondon rewrote the sorting code, the transcriptome browser is written differently than the rest for some reason but this should prevent it from breaking at the very least

https://github.com/statonlab/tripal_manage_analyses/tree/sort_archived

**Comment by bradfordcondon** [comment]
@jwest60 current status of this branch

![screen shot 2018-03-01 at 10 58 08 am](https://user-images.githubusercontent.com/7063154/36854628-74cc8e12-1d3f-11e8-9905-477e0b28f7ca.png)

Transcriptome field is null when it should not be.

**Comment by jwest60** [comment]
![image](https://user-images.githubusercontent.com/32902460/37726003-b1baa2ca-2d0a-11e8-9e7a-1beccaad72af.png)

@bradfordcondon [latest commit works on my end](https://github.com/statonlab/tripal_manage_analyses/tree/sort_archived)

**Comment by bradfordcondon** [comment]
It works!

But....


![screen shot 2018-03-21 at 1 26 57 pm](https://user-images.githubusercontent.com/7063154/37726367-930457d0-2d0b-11e8-96ac-6a655db90525.png)


Check your code at line 157 of the load and only open that property if the property exists.

**Comment by jwest60** [comment]
@bradfordcondon whoops, just corrected that as well in the last commit

**Comment by bradfordcondon** [comment]
- [ ] put on dev (master branch)

- [ ] put on live
