### ISSUE TITLE
collections theme issue

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#132]
After creating a collection, i can't [visit my collections page](http://localhost:8081/user/1/data-collections) because of this error

`Notice: Undefined index: #title_display in hardwood_form_element() (line 202 of /Users/chet/UTK/tripal/sites/all/themes/hardwood/template.php).`

I'm assuming we'll have this problem on the dev instance too and that it will be an easy fix to the hardwood theme.

**Comment by almasaeed2010** [comment]
Could you try updating the theme please?

**Comment by bradfordcondon** [comment]
After pulling my theme was out of date.

Now the page shows up but i still have the warning.  i'll try to address

**Comment by almasaeed2010** [comment]
Clearing the cache should remove the warning too. We had that issue on the staging server and it went away after clearing the cache. Let me know how that goes.

**Comment by bradfordcondon** [comment]
yeah youre right.  so no further problem/need to fix i guess.
