### ISSUE TITLE
transcript search field for organism not behaving as expected

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#135]
http://160.36.205.61:8095/organism/Quercus/robur?search_term=test&op=Search&organism=Quercus+robur&form_build_id=form-rup2Osi--yOsV4s1ZBKVHySM0xbRcBP3t5au31Nxu1Y&form_token=xtAApdNb749VC2yjrraOJXyput3RgL9NfRBSj972VQg&form_id=tripal_elasticsearch_gene_search_form

* I can search against quercus rubor.  i believe there are no features for this organism.
* i get search results, I guess to quercus rubra?

**Comment by bradfordcondon** [comment]
Feature search should only appear if there are features for that organism.  Unfortunately, checking if there is a transcriptome/genome analysis linked to an organism isnt enough, because some organisms have archived analyses with no features.

Maybe we do need to keep that mview table after all?

**Comment by almasaeed2010** [comment]
The fix is as simple as replacing the organism search query with a specific ID rather than the genus/species. We can also query a count from ES for each organism and if it returns 0, we don't display the field.

**Comment by bradfordcondon** [comment]
I like both of those solutions
