### ISSUE TITLE
Q lobata jbrowse has no tracks or features?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#144]

**Comment by almasaeed2010** [comment]
To fix: add a new field in the jbrowse module to handle manual location entires and add them to the URL (as &loc=GENE_NAME). While doing this, let's also attach the gene name to the generated button when visiting from a feature page.

URL to working feature: QlobV1.0_scaffold2013_0000070

**Comment by almasaeed2010** [comment]
Will need to add a default "location" field to link directly from organism page.

**Comment by almasaeed2010** [comment]
Done. To test: http://160.36.205.61:8095/organism/Quercus/lobata?tripal_pane=group_jbrowse
