### ISSUE TITLE
Chinese Chestnut organism

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#149]
Chinese chestnut
- [x] Organism cross reference - link out to ncbi goes to xml - is this on purpose?
- [x] genome date is 1899 or 1900, can we fix?
- [x] Reference genome pane - remove one of two links

**Comment by bradfordcondon** [comment]
date: #68

**Comment by bradfordcondon** [comment]
page at http://160.36.205.61:8095/chinese-chestnut-genome deleted, field linking to it removed.  (using chado analysis instead)

**Comment by bradfordcondon** [comment]
reference genome freetext field deleted

**Comment by bradfordcondon** [comment]
old ncbi link out:

* http://purl.obolibrary.org/obo/ncbitaxon#
new linkout
* https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=60419
