### ISSUE TITLE
Create Help Page

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#157]
* New node type
* In style of Treesnap
* Categories for each tool
  * Include modules as tools
*

**Comment by almasaeed2010** [comment]
New module: https://github.com/statonlab/hardwoods_help

Once we have some content there, we can start investigating ways to make the help page more accessible than simply adding a link to the navbar. Ideas for that:
- Create a floating button at the bottom right of the page
- Add a link on each tool's page that leads to the help content for that tool (doable now with bookmark-able tabs)

**Comment by bradfordcondon** [comment]
Question about your vision:

A single help page, with many tabs?

Or many, more focused, help pages?

My current dox status is here : https://github.com/mestato/statonlabprivate/wiki/hwg-help-documentation

Section for tools, section for using the organism/feature/analysis stuff, and a FAQ.  Would we have 3 tabs with really long help content?  Or would the tools be its own help page, wiith each tool as a tab?

Or can we do nested menu items?

**Comment by almasaeed2010** [comment]
The only benefit from creating separate pages is that page might load faster if we have lots of content. 
I like the idea of splitting into 2 pages, one for tools and the other for everything else

**Comment by bradfordcondon** [comment]
OK, I'll try organizing it that way.

**Comment by bradfordcondon** [comment]
For images, the url should be `![trees dropdown](/../sites/default/files/help_docs/navigation/organism_dropdown_list.png).`

**Comment by almasaeed2010** [comment]
What's with the relative path?

**Comment by almasaeed2010** [comment]
I can access `http://160.36.205.61:8095/sites/default/files/help_docs/navigation/organism_dropdown_list.png` so the path should be `/sites/default/files/help_docs/navigation/organism_dropdown_list.png`

**Comment by bradfordcondon** [comment]
it comes out with `/content/` appended doing it that way.  Hence the `/../`

**Comment by almasaeed2010** [comment]
Not if you start with `/`

**Comment by bradfordcondon** [comment]
*shrug man*  they both work

**Comment by almasaeed2010** [comment]
That's because we have an apache configuration to redirect but this may fail on other servers if apache isn't configured the same way

**Comment by bradfordcondon** [comment]
ok thanks for hte clarification
