### ISSUE TITLE
JBROWSE data storage hosting

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#159]
The issue with hosting flat files liek we currently do is

* Stuff gets lost
* Size is huge
* Harder to maintain
* Can't connect new stuff

### Solutions

* Load everything into our site's chado (we dont like this)
* Create a second chado db.  It's on the same server so we dont need to set up anything else.
* Use APOLLO or something similar to act as the API  (need JAVA service, keeps crashing).  
* Use DAS in the same manner as APOLLO (dont know requirements)  http://www.sanger.ac.uk/science/tools/das-archive.  DAS is deprecated, what replaced it? maybe  https://rest.ensembl.org/

We like the second DB idea.  Doesn't allow easily connecting new stuff (IE biodalliance)

Is there any way we can host our sequences and annotations on say ENSEMBL and connect to it via the API instead of hosting ourselves.

**Comment by almasaeed2010** [comment]
It looks to me that we are gonna keep using files and not move to chado so I am closing. Feel free to reopen if needed.
