### ISSUE TITLE
Chinese chestnut qtl: lets revisit this

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#161]
Issues:

*  own organism (should it stay this way?)
*  reference genome not listed in reference genomes
*  JBROWSE instance lists "tracts" instead of tracks
* Jbrowse field needs some description.  see #137 

![Screen Shot 2018-02-06 at 2.38.59 PM](http://static.gitscout.com/34cdc25a724551c27c81d3ad468f380c76ddfc63b6cb9375b94a179931a640c8.png)

![image](http://static.gitscout.com/9741e522a1c838a9a655031676cfd3760d8b30d2e002992e12c005996b3a09cb.png)

**Comment by bradfordcondon** [comment]
send email to meg for a description of the jbrowse instance and the tracks

**Comment by bradfordcondon** [comment]
* turns out people do use tract to describe jbrowse tracks.  I still think its incorrect but it's out there in the world so, whatever.
* Still need to add jbrowse track descriptions for chiense chestnut QTL to be provided by meg

**Comment by almasaeed2010** [comment]
there is another issue for this #137
