### ISSUE TITLE
Add biomaterial description to organism pane view

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#163]
The biomaterial names are cryptic (e.g. BW-OW-11), if we could add the description to the view on the organism pane it would be much better (and probably more useful than biomaterial provider, so I vote to get rid of that if they don't both fit). Prior to rolling over to Tripal v3 we had tissue and treatment, this was also a good solution.

**Comment by bradfordcondon** [comment]
some of the biomaterial descriptions are essays and not suitable for display in a table  (could set a max character length).

I think the "upcoming" reannotation of existing biomaterials will give us some nice handles to add to the table.  We can consistently say that each biomaterial needs say a tissue and treatment property for example, and we'll include this.

**Comment by bradfordcondon** [comment]
set up on dev.  Needs to go live, possibly after additional table formatting @almasaeed2010 ?

**Comment by almasaeed2010** [comment]
Ready to go live
