### ISSUE TITLE
Expression Heatmap tool search

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#164]
For the search next to the expression heatmap builder tool, i think it would be more significantly more useful if you could limit by organism and then search by blast/go/ips. (Just like the gene search, basically). our transcript/gene names are not very memorable.

**Comment by bradfordcondon** [comment]
Collections support would also be cool.

**Comment by almasaeed2010** [comment]
This is done and live. 

I am not sure about supporting collections since the heat map simply can't take hundreds of features all at once. Even if the code can handle it, the browser won't be able to render such a big matrix.
