### ISSUE TITLE
Live site collections issue: permissions

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#166]
Drupal is creating the wrong permissions for collection files which's making downloaders fail with the following error:

```
{"status":"failed","message":"Could not access the directory on the server for storing this file.","file_id":""}Job execution failed: Cannout open collection file:        
```

**Comment by almasaeed2010** [comment]
Tripal is creating the directory but then it thinks its not writeable when it actually is since the user is root! No idea why is_writeable is returning false.

**Comment by bradfordcondon** [comment]
i remember manually changing the permissions.

i dont remember, does it create new directories for each user etc?  If so thats not a feasible solution

**Comment by almasaeed2010** [comment]
Yeah I had to change the dir permissions manually too

It creates a directory for each user in `sites/default/files/tripal/users/$uid`. If it can create the directory, its automatically writeable but it's failing somewhere to figure out that it is writable. I wrote a little php script to check permissions for bot the root and the apache users and they both return true (writeable). Therefore, the error is with Drupal's `file_prepare_directory()` 

No idea where to go from here

**Comment by almasaeed2010** [comment]
Ok removing this code block form TripalFieldDownloader works!

```php
// Make sure the user directory exists
    $user_dir = 'public://tripal/users/' . $user->uid;
    if (!file_prepare_directory($user_dir, FILE_CREATE_DIRECTORY)) {
      $message = 'Could not access the directory on the server for storing this file.';
      watchdog('tripal', $message, array(), WATCHDOG_ERROR);
      drupal_json_output(array(
        'status'  => 'failed',
        'message' => $message,
        'file_id' => '',
      ));
      return;
    }
```

**Comment by almasaeed2010** [comment]
Created an issue on tripal main repo:

https://github.com/tripal/tripal/issues/293

**Comment by bradfordcondon** [comment]
just pinged Stephen on this to get some movement

**Comment by bradfordcondon** [comment]
this has been submitted and merged, but i think we still have problems.

**Comment by almasaeed2010** [comment]
Collections are working fine now. I tested with a new user on live.
