### ISSUE TITLE
Missing Polypeptides

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#168]
https://hardwoodgenomics.org/feature/Alnusrubra021816comp1350c0seq1?tripal_pane=group_sequence_tripalpane
doesn’t show the polypeptide sequence …

**Comment by almasaeed2010** [comment]
FASTA files: http://160.36.205.61:8095/Transcriptome-assembly/1963030?tripal_pane=group_description_download

**Comment by bradfordcondon** [comment]
peptide name:
>>Alnus_rubra_021816_comp10000_c0_seq1_m.8728 Alnus_rubra_021816_comp10000_c0_seq1_g.8728  ORF Alnus_rubra_021816_comp10000_c0_seq1_g.8728 Alnus_rubra_021816_comp10000_c0_seq1_m.8728 type:5prime_partial len:329 (+) Alnus_rubra_021816_comp10000_c0_seq1:1-987(+)


mrna name:

>Alnus_rubra_021816_comp9690_c0_seq1



so the regexp needs to drop everythign after seq#, ie _m.8728.  note that sometimes its seq1, sometimes its seq2

**Comment by bradfordcondon** [comment]
I believe`/(?=> Alnus)(.*?)(?=_m)/`  works.

**Comment by bradfordcondon** [comment]
Added to http://160.36.205.61:8095/Transcriptome-assembly/1963030

I reloaded.  
Feature with polypeptide:

http://160.36.205.61:8095/feature/Alnusrubra021816comp9690c0seq1?tripal_pane=group_sequence_tripalpane

Feature without:

https://hardwoodgenomics.org/feature/Alnusrubra021816comp1350c0seq1?tripal_pane=group_summary_tripalpane

**Comment by bradfordcondon** [comment]
its not in the source polypeptide FASTA file, for whatever reason.  Probably working as intended. closing.
