### ISSUE TITLE
Add gene locations to gene page (for organisms with genomes)

### ISSUE THREAD

**Issue by jwest60** [statonlab/hardwoods_site#17]
https://www.rosaceae.org/fragaria/fragaria_vesca/gene23664-v1.0-hybrid

**Comment by bradfordcondon** [comment]
The Chado way to store this information is the [Chado Map module](
http://www.gmod.org/wiki/Chado_Map_Module).

As far as tripal goes, start with the[ tripalmap module](http://tripal.info/extensions/modules/tripalmap)

The actual location info would have to be imported from the GFF files (which we have for anything we use jbrowse for)

**Comment by almasaeed2010** [comment]
The module https://github.com/ksbuble/TripalMap is currently empty and has only a README file (from 2 years ago). During PAG, I believe I heard Dorrie suggest that they will release a tripal map module in March or May to replace CMap. We can ask them to confirm or just wait and see if anything comes out. The other option is to develop one ourselves.

**Comment by almasaeed2010** [comment]
Find a route around. Look at Lacey and Ethy's code and keep Emily in the loop.

**Comment by bradfordcondon** [comment]
This is duplicate with #210 .
