### ISSUE TITLE
expression heatmap very slow live

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#171]
https://www.hardwoodgenomics.org/content/expression-visualization

Using the default set is minutes to load the heatmap.

**Comment by bradfordcondon** [comment]
just curious, why is the speed fine for the individual feature then?

**Comment by almasaeed2010** [comment]
individual as in only 1 feature?

**Comment by bradfordcondon** [comment]
right.

the heatmap is mega slow even with just 2 features selected.

**Comment by almasaeed2010** [comment]
Yeah the script quits once it realizes it has less than 2 features so the query never runs

**Comment by bradfordcondon** [comment]
no, my point was that the individual feature expression viewer is speedy enough.  Why would it get so slow for the heatmap tool?  It's not like it should take that much longer to fetch 3 features as opposed to 1.

**Comment by almasaeed2010** [comment]
It's a completely different script. honestly, I have no idea how the heatmap query is constructed or why it's different than the query used for the individual features.

**Comment by almasaeed2010** [comment]
Worth investigating though. Maybe we can come us with a new way to build the matrix.

**Comment by bradfordcondon** [comment]
this has been resolved by @almasaeed2010
