### ISSUE TITLE
search can be improved

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#174]
Take the following example:
I'm looking for lectins on chestnut.

https://www.hardwoodgenomics.org/tripal_elasticsearch/search_website/?search_box=chestnut++and+lectin&op=Search&category=&form_build_id=form-w3c29-CDMOXJHs1fMVA_Ti_hDeiotLoJ9MrPYbXjKyg&form_token=LpYm6862P0Cz3hZ4EF_y2mu2B1mXX_Qpm2G24LEIGYA&form_id=website_search_box_form

No results.

However, look at this gene entry:

https://www.hardwoodgenomics.org/feature/AC454contig43821v3?tripal_pane=group_homology
Scroll down and you'll see that both sets of blast matches correspond to lectins.

<img width="1029" alt="screen shot 2018-02-09 at 8 06 54 pm" src="https://user-images.githubusercontent.com/7063154/36056724-d09a7ddc-0dd4-11e8-9e8b-06b021fdf41f.png">

All of the blast homology are to lectin proteins:  http://www.uniprot.org/uniprot/F4I8U6

**Comment by bradfordcondon** [comment]
Note that this shows up for the organism's feature search:

https://www.hardwoodgenomics.org/organism/Castanea/dentata?search_term=lectin&op=Search&organism=Castanea+dentata&tripal_pane=group_feature_search&form_build_id=form-fuyKeczcbgkOhZmmNfNTqkNGM54joJcf2QeY-DcSgyk&form_token=cCVTFj4O4RziXUbwMSAeyaTRye-s9m1pWyLCTO6MlNU&form_id=tripal_elasticsearch_gene_search_form


So my question is, why doesnt the site wide search include feature annotations? Is it ignoring this info intentionally?

**Comment by almasaeed2010** [comment]
It depends on how the Blast module is structuring data in its field. If it's object based, ES can't handle it. It has to be manually converted to an array of entires. We can add an exception in our indexer but that obviously doesn't fix the issue entirely.

**Comment by almasaeed2010** [comment]
Enabled blast indexing. Let's check again later/tomorrow to see if it worked.

**Comment by almasaeed2010** [comment]
So this works now. I am still not sure why some pages either fail to index or fail to report the progress. Either way, the ones failing are in the second round of indexing so I'll make an issue for that on ES.
