### ISSUE TITLE
organism's feature search should also allow collection creation

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#178]
<img width="1439" alt="screen shot 2018-02-11 at 11 08 25 am" src="https://user-images.githubusercontent.com/7063154/36075369-0d11bd5a-0f1c-11e8-9781-0cec81375de5.png">

Download FASTA= great but should also support collection creation

**Comment by almasaeed2010** [comment]
Simple enough 👍

**Comment by almasaeed2010** [comment]
Moved to ES repo

**Comment by almasaeed2010** [comment]
for reference https://github.com/tripal/tripal_elasticsearch/issues/170
