### ISSUE TITLE
Training / developer sessions

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#180]
Split off from #94  

General goal: When we do the training, record, put here.  And also hopefully when prepping the training,create the material that will go in the help page

# Dev Trainings
- [x] Basic module development
- [x] Tripal Elasticsearch (abdullah)
- [x] Tripal Analysis Expression

- [x] Jbrowse (point to existing training?)

- [x] Tripal v3 module development  <--- hopefully the tripal.info docs will make this negligible????

- [x] Galaxy (Ming)

**Comment by almasaeed2010** [comment]
Completely forgot about this. If we still wanna do this, let's assign the issue so it's easy to find later.
