### ISSUE TITLE
jbrowse tool genome page links need updating

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#183]
https://www.hardwoodgenomics.org/content/jbrowse

link to for example https://www.hardwoodgenomics.org/chinese-chestnut-genome

**Comment by almasaeed2010** [comment]
This page also needs updating:
https://www.hardwoodgenomics.org/genomes

same example as above

**Comment by almasaeed2010** [comment]
done for Chinese chestnut gnome and Chinese QTLs.
