### ISSUE TITLE
Why do we have 2 European Ash analyses?

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#187]
Currently we have 1 [transcriptome assembly](http://160.36.205.61:8095/bio_data/1963055) and 1 [genome assembly](http://160.36.205.61:8095/bio_data/1963052). Is this correct?

**Comment by bradfordcondon** [comment]
It should just be genome.  But before we correct, let's see what the features are tied to.

**Comment by bradfordcondon** [comment]
http://160.36.205.61:8095/feature/FRAEX38873v20001606202  the type_ID is mRNA not mRNA_contig.

The feature sis linked, via analysisfeature, to analysis **151**, which is genome _assembly.

THis means we can safely delete the transcirptome assembly analysis.

**Comment by bradfordcondon** [comment]
i deleted the transcriptome... did it break? hahah

**Comment by bradfordcondon** [comment]
https://www.hardwoodgenomics.org/bio_data/1963055

should be only analysis with 

Program version: `BATG-0.5, v4`

**Comment by bradfordcondon** [comment]
`select * FROM chado.analysis T  WHERE T.programversion = 'BATG-0.5, v4';` finds it.

So we delete by

`delete FROM chado.analysis T  WHERE T.programversion = 'BATG-0.5, v4';`

Chado record and entity deleted on live and dev, closing.
