### ISSUE TITLE
update juglans genome download links

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#194]
The walnut team at UCD is having trouble with the genome/transcriptome download links.  our links are headed to the TreeGenes FTP site. There's a new site:

https://treegenesdb.org/FTP/Genomes/Reju/v1.0/annotation/

But since we aren't too good a keeping up with broken links and its tough to know when others move things around, I suggest we move to storing locally.

**Comment by bradfordcondon** [comment]
I wonder if our policy should be to not try to direct link files hosted elsewhere, but instead redirect to the general landing page (ie, walnut data is hosted on treegenesdb)

**Comment by mestato** [comment]
I'm not as big a fan of this, because it means more clicking and hunting around for what you want for the user. If the data isnt' public, then we dont' have a choice, we'll always link to the originator. but if we can host it and describe the files within our site, I think we should, to have user experience consistency

**Comment by bradfordcondon** [comment]
[organism](http://160.36.205.61:8095/organism/Juglans/regia) links to http://dendrome.ucdavis.edu/ftp/Genome_Data/genome/Reju/

[analysis](http://160.36.205.61:8095/Genome-assembly/1963051) links to the same.

### Tasks

- [ ] update dev

- [ ] update live

**Comment by bradfordcondon** [comment]
Updated but the link is dead.  Seeking correct link from treegenes people.

**Comment by bradfordcondon** [comment]
From Jill
>Ugh, sorry, our cloud storage is having connection issues....hold for an update - should be resolved shortly

Now live
