### ISSUE TITLE
Centralized services

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#195]
The idea...

Centralized Tripal Services
1. Galaxy
share workflows and files
2. ElasticSearch
Host indices and enable cross site search

This could also have a site agnostic uber-search of all Tripal ES.
"Tripal Central Station"
Search the Tripal-verse!

Possible hosts to ask: Cyverse, TACC, Main lab

What else do we want to make a central service? Is it a good idea to pin anyone's site on a central service that might go down? We need admin salary  money, where to get?

**Comment by almasaeed2010** [comment]
Reference: natural language support in ES #162

**Comment by mestato** [comment]
The grant is out for review (at least on the mobile side), fingers crossed.
