### ISSUE TITLE
JBrowse - highlight and download region

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#201]
This is a JBrowse feature request. Would be nice to highlight a region and export as fasta (or export the track features). Would also be nice to do this with the current region on the screen. Should be possible with [version 1.7](https://jbrowse.org/jbrowse-1-7-0/). [From this issue](https://github.com/GMOD/Apollo/issues/1152), Nathan says its possible with native jbrowse, not via apollo.

**Comment by bradfordcondon** [comment]
We've discovered this is possible by selecting the SEQUENCE track, correct? closing, please re-open if necessary.
