### ISSUE TITLE
JBrowse help page updated

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#202]
Help text updates were posted to JBrowse section on [Tools help wiki](https://github.com/mestato/statonlabprivate/wiki/Help-Page:-Tools). Needs to be copied, pushed to dev, pushed to live.

**Comment by bradfordcondon** [comment]
* updating images not necessary
- [ ] copied to dev

- [ ] copied live

**Comment by bradfordcondon** [comment]
Note: I also updated the FAQ, text only.
