### ISSUE TITLE
JBrowse issue: can you download sequences?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#211]
User comment
>. I also tried downloading my own sequence like the video described but it did not work as described in the jbrowse video.

**Comment by mestato** [comment]
Made a video which can be posted to help pages. Sent to user, still awaiting input from them to see if this solves problem. 

Link to mp4: https://drive.google.com/open?id=1jI1yVJPPmQ76HtV6JpOKxE07EuCc2waO

**Comment by bradfordcondon** [comment]
Thanks Meg!

Are you interested in setting up a HWG youtube channel?  If so want me to set it up?  Maybe we make it public once we make 5 videos or something?

**Comment by mestato** [comment]
Video live at:
https://www.youtube.com/watch?v=SgEU9ZHsoOc&t=3s
