### ISSUE TITLE
confirm working email for new registration

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#215]
When a new user registers, verify their email is correct before logging them in.

**Comment by bradfordcondon** [comment]
This is supported out of the box in Drupal 7.

<img width="1440" alt="screen shot 2018-03-15 at 9 13 21 pm" src="https://user-images.githubusercontent.com/7063154/37498623-bf570f50-2895-11e8-8b2f-1aeaad798587.png">


I've enabled it on the live site.  this is what it looks like after registering:

<img width="1387" alt="screen shot 2018-03-15 at 9 14 25 pm" src="https://user-images.githubusercontent.com/7063154/37498646-e010ffb2-2895-11e8-9122-956f5034ab89.png">

Unfortanetly I never got the email dsent to my UTK box.

Can someone else please try?  Not sure if this is our existing problem where server emails go to "spam"  or a problem with our configuration.

**Comment by almasaeed2010** [comment]
Yes the current email server has no “reputation” established and therefore many (if not all) mail clients reject it automatically. Thus, the need for the mail module, which hopefully will ready soon 👍

**Comment by bradfordcondon** [comment]
hey i read the mime mail module can help: https://www.drupal.org/project/mimemail

did you check this out at all?

**Comment by bradfordcondon** [comment]
here's the message in my junk mail

<img width="790" alt="screen shot 2018-03-15 at 9 24 47 pm" src="https://user-images.githubusercontent.com/7063154/37498928-523b6d74-2897-11e8-885d-44bf792ab209.png">

**Comment by bradfordcondon** [comment]
ps i recognize im like months late to this discussion haha

anyway ill disable on live for now since the registration link just goes to junk

**Comment by almasaeed2010** [comment]
Unfortunately modules that don’t implement drivers to send emails off reputed mail servers like mailgun via APIs or SMTP, can’t help our situation

**Comment by bradfordcondon** [comment]
so what about https://www.drupal.org/project/mailgun or https://www.drupal.org/project/mailman_integration ?  What is the need for the custom mailman module: galaxy support?

**Comment by almasaeed2010** [comment]
Ok this is fixed on line too. All our emails should get to the inbox (not junk) and the FROM is now `contact@hardwoodgenomics.org` and if someones sends a message to that email or replies to an email sent from there, it will automatically get forwarded to Meg, Bradford and myself.
