### ISSUE TITLE
Galaxy site wide files

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#216]
For dev site, make these files site wide files:
For all genomes, we need the genome sequence, the gff3 annotation and the genes (nucleotide and protein)
(gtf might need to be generated, @MingChen0919 what workflows require gtf?)
For all transcriptomes, nucleotide and protein sequences

**Comment by MingChen0919** [comment]
## Under progress

* **Chinese chestnut**

- [ ] Cm_v1.1_contigs.fasta
- [ ] Cm_v1.1_scaffolds.fasta
- [ ] Cm_v1.1_transcripts.fasta
- [ ] Cm_v1.1_peptides.fasta
- [ ] Cm_v1.2_genes.gff3

**Comment by bradfordcondon** [comment]
hi @MingChen0919 it looks to me like you've accomplished this.

* Does it need to be repeated on live?
* If not, can I close the issue?

**Comment by MingChen0919** [comment]
I don't know if it need to be repeated on live. To me it seems unnecessary. Because the workflows use tools that can transfer data with URLs directly from tripal site (it does not have to be from HWG) to a galaxy instance.

**Comment by bradfordcondon** [comment]
ok in that case i'm closing this out.  @mestato please reopen if you disagree.
