### ISSUE TITLE
Build Galaxy workflows to support adding genes and transcripts to the site

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#217]
We need BLAST results in xml format against two databases: swissprot and the plant section of trembl. We also need InterProScan results in xml format. Workflows to support these and an estimate of how long each sequence takes on the main lab galaxy would be helpful.

**Comment by MingChen0919** [comment]
#158

**Comment by MingChen0919** [comment]
duplicate issue: #158
