### ISSUE TITLE
Tripal Tutorial - Loading FASTA file screenshot issue 

### ISSUE THREAD

**Issue by Lupercal2** [statonlab/hardwoods_site#221]
The issue found is a line of text is different in the screenshot from what is suppose to be. The input is `(FRA.*?)(?=:)`, whereas in the screenshot it is `(FRA.*?)\.1`
<img width="1010" alt="slide 45 fixed" src="https://user-images.githubusercontent.com/37534829/37668695-7540950e-2c3b-11e8-9d20-d1d2aa1c4cba.png">
<img width="1010" alt="slide 45" src="https://user-images.githubusercontent.com/37534829/37668696-755058fe-2c3b-11e8-8af1-18296045dce6.png">

**Comment by bradfordcondon** [comment]
resolved, thanks.
