### ISSUE TITLE
look into making the trees menu item automatic

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#223]
The Trees menu on the top nav bar has to be edited and sorted manually every time a new organism is added. We need to look into a method to make that menu automatically generated

**Comment by jwest60** [comment]
i'm not 100% sure how to implement it, but here's some pseudocode that i think might work

**Comment by jwest60** [comment]
[first attempt at creating a module for this](https://github.com/jwest60/tripal_manage_menus)

creates the menu on install with links to all the organisms and updates the links automatically any time a new organism is created, deleted, or updated

**Comment by almasaeed2010** [comment]
@jwest60 could you please move the module repo to the statonlab organization on Github? this would allow us to make any changes without having to fork.

Let me know if you want help doing this.

Thanks!

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/issues/319#issuecomment-377978153

FYI this functionality is something lacey needs and therefore is something that will probalby get added into core.

**Comment by almasaeed2010** [comment]
In that case, let's keep this simple and not targeted towards any/all bundles. What it does currently is perfect for our cases. I'll test it locally and if it works we can use it until core supports this functionality again.

**Comment by jwest60** [comment]
This module is done, give it a look and try it out on the dev site. @almasaeed2010 @bradfordcondon

**Comment by bradfordcondon** [comment]
it probably wants info on what it looks like/how to set up (if theres any setup step)
https://github.com/statonlab/tripal_manage_menus/issues/5

**Comment by bradfordcondon** [comment]
- [ ] add dev

- [ ] add live

**Comment by bradfordcondon** [comment]
I added the module on my local site and enabled the "trees"block.  Nothing shows up though, and no warnings.

**Comment by jwest60** [comment]
im certain it was working when i left it so i'm not sure why it wouldn't be working now

**Comment by jwest60** [comment]
so it turns out the link path was hard-coded for the organism page on the hardwood genomics site, which was intended since this is really only intended for our use until something like this gets added to core

the documentation has been updated to reflected this [here](https://github.com/statonlab/tripal_manage_menus) along with solutions on how to use it on a personal site

**Comment by bradfordcondon** [comment]
I'd like to get https://github.com/statonlab/tripal_manage_menus/issues/6 resolved before putting it on live.

**Comment by bradfordcondon** [comment]
Enabled and updated on dev.


after creating an organism

<img width="1240" alt="screen shot 2018-06-14 at 11 12 55 am" src="https://user-images.githubusercontent.com/7063154/41421087-f32bce0e-6fc3-11e8-92c0-27269819e953.png">


cool, its in the menu right away.  After deleting the entity, the menu link goes away.  well done @joe.

After creating a pub, no error so https://github.com/statonlab/tripal_manage_menus/issues/6 s resolved.

Way to go!  let's put it live.

**Comment by bradfordcondon** [comment]
enabled live.
