### ISSUE TITLE
links to the english walnut genome resources are broken

### ISSUE THREAD

**Issue by MingChen0919** [statonlab/hardwoods_site#224]
On this page: http://160.36.205.61:8095/english-walnut-genome.

**Comment by bradfordcondon** [comment]
please see https://github.com/statonlab/hardwoods_site/issues/194

Previously their cloud storage was down.  I can contact them and let them know its down again.

**Comment by almasaeed2010** [comment]
@jwest60 can handle it if we give him access to the server

**Comment by bradfordcondon** [comment]
I updated urls to dendrome.

**Comment by mestato** [comment]
@jwest60 Even though links are currently fixed, please download the files locally and lets link to our local version, this will be more robust moving forward.

**Comment by jwest60** [comment]
[links are now localized](http://160.36.205.61:8095/english-walnut-genome)

all download links tested and seem to work fine

**Comment by almasaeed2010** [comment]
Done live
