### ISSUE TITLE
case where  JBROWSE feature linkout does not find feature

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#225]
European ash

might be related to problems im having with #210 and discrepencies between the features loaded and the GFF...
https://www.hardwoodgenomics.org/feature/FRAEX38873v20003249204?tripal_pane=group_jbrowse

The Jbrowse linkout here is to the start of scaffold 0: not to the actual feature.

**Comment by bradfordcondon** [comment]
linkout is also wrong for nearby feature https://www.hardwoodgenomics.org/feature/FRAEX38873v20003249501?tripal_pane=group_jbrowse

**Comment by bradfordcondon** [comment]
Linkouts are for http://160.36.205.61:8095/tools/jbrowse/?data=european_ash&tracks=gene&loc=FRAEX38873_v2_000324930.1

when they should be for 

http://160.36.205.61:8095/tools/jbrowse/?data=european_ash&tracks=gene&loc=FRAEX38873_v2_000324930

IE, it's linking out to the mRNA instead of the gene.

**Comment by bradfordcondon** [comment]
regexp needed:  `[^;.]*`

**Comment by almasaeed2010** [comment]
So the correct expression in PHP is `/(.*)?\./`

here is an example of the result: http://160.36.205.61:8095/feature/FRAEX38873v20003873601?tripal_pane=group_jbrowse

I'll implement it on live (once the cache clears ...)

**Comment by almasaeed2010** [comment]
Fixed on live.
