### ISSUE TITLE
Download button for Gleditsia triacanthos putative transcripts not working

### ISSUE THREAD

**Issue by MingChen0919** [statonlab/hardwoods_site#230]
The download button for Gleditsia triacanthos putative transcripts is not working. When clicking the button, it redirects to the same page, instead of a downloadable url. 
http://160.36.205.61:8095/Transcriptome-assembly/1963033?tripal_pane=group_description_download.

**Comment by bradfordcondon** [comment]
Does the file exist?
yep.  simple edit then.

`/home/bcondon/dev_server/sites/default/files/sequences/honeyLocust082614/Gleditsia_triacanthos_082614_transcripts.fasta`

**Comment by bradfordcondon** [comment]
- [ ] fixed dev

- [ ] fixed live

**Comment by MingChen0919** [comment]
is this page manually created?

**Comment by bradfordcondon** [comment]
yes and no.

It's an analysis page, so its in Chado.
The text and formatting is manual: its the description field of the Chado analysis entry.

You can fix by directly editing the page, though.

**Comment by bradfordcondon** [comment]
resolved.
