### ISSUE TITLE
Inconsistent downloading button icon

### ISSUE THREAD

**Issue by MingChen0919** [statonlab/hardwoods_site#231]
The downloading button icon is inconsistent on this page: http://160.36.205.61:8095/english-walnut-genome

<img width="1299" alt="screen shot 2018-03-28 at 12 06 57 pm" src="https://user-images.githubusercontent.com/1262709/38041834-cbe5f25a-3280-11e8-9490-a3c576e593b7.png">

I can fix this by editing the html, but I am not sure that's the standard way. @almasaeed2010 could you check that? thanks!

**Comment by bradfordcondon** [comment]
yes thats the standard way.  its probably msising a style property that the other button has.


PS note  that its fine on live https://www.hardwoodgenomics.org/english-walnut-genome

**Comment by MingChen0919** [comment]
ok good. the dev site is missing a css attribute on that button. the live site has it.
