### ISSUE TITLE
[idea] Creating Tripal Server Management Service

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#232]
All major server providers provide an API to create and manage servers
- Amazon AWS: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Welcome.html
- Digital Ocean: https://developers.digitalocean.com/documentation/v2/
- Azure: https://docs.microsoft.com/en-us/rest/api/

### Proposal
The service would be targeted towards users with little to no sys admin experience. It would provide the following services:
- Allows users to create a full Tripal site in one click.
  - The form will require nothing more than to select a server provider from the list above (e,g. aws), and fill the general site information such as username, password etc.
- Allows users to use contributed "recipes" that would install certain services on their servers (e,g. one click elasticsearch integration).
- Allows users to install tripal extensions as well as download Drupal modules through the interface.

### Technical Requirements
- Resources
  - We'll need nothing more than a small (1GB) server
- Development
  - Laravel based application to provide the site
  - 3 API integrations for each of the server providers (we can start with one to see how it goes)
  - Shell files for ubuntu (called "recipes") to perform the tasks of installing the required services such as apache, postgres and php.

### Notes
- We already have docker build files that contain all the code we need to build useable tripal servers so we can use those to build servers
- This service is already provided by multiple other sites (for a certain fee) to install popular frameworks such as laravel, wordpress etc. So we know that this is possible.
  - Example 1: [Ansible](https://www.ansible.com/integrations/cloud)
  - Example 2: [Laravel Forge](https://www.ansible.com/integrations/cloud)

**Comment by bradfordcondon** [comment]
We all think  this is a really cool idea for a long-term tripal plan.  I dont think it went into CSSI, so not much to discuss on this issue right now.
