### ISSUE TITLE
Genetic Map content type

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#235]
We want to start adding genetic maps to HWG (types: linkage, QTL, maybe association). 

Optimally maps would exist on HWG with all this stuff:
- an analysis describing the map and pointing to the paper and downloads of flat files
- map markers in chado (new entity bundle) with sequences and map locations where available
- a track on jbrowse if reference genome is available
- a way to explore via CMap JS or other map viewer software

**Comment by bradfordcondon** [comment]
* content type maps to `featuremap` table. (bundle already exists).
* Organism linker field in tripal_manage_analyses will be expanded to work on featuremaps.
* Linking to analysis: analysis_featuremap is not a table, but it could be.
* cmap field will attach to featuremap bundle.  Need some way to manage flat files for now.

**Comment by bradfordcondon** [comment]
- [ ] update organism linker to work on map

- [ ] cmap field with a field setting that lets you specify path to flat file.

**Comment by bradfordcondon** [comment]
these pieces are all in place except for an analysis linker.  Going to close, if we feel the need for an analysis beyond the map description we can create it but it will include creation of a new chado table and linker field.
