### ISSUE TITLE
organism linker field is buggy

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#240]
https://github.com/statonlab/tripal_manage_analyses
Errors on dev:

* Updating throws a warning
![image](https://user-images.githubusercontent.com/7063154/38426958-f40ebc10-3985-11e8-9d7f-a706a0e671f6.png)

* Creating new content with organism set is blocked

**Comment by jwest60** [comment]
@bradfordcondon fixed on my end and should be ready to test on dev

**Comment by bradfordcondon** [comment]
thanks! looks good on dev.  Just need to pull live and we can close.
