### ISSUE TITLE
tripal cmap loader

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#244]
### Overview
Input: Cmap file.
Loads into [chado map module](http://gmod.org/wiki/Chado_Map_Module)
It's a Tripal 3 importer so if the tripal map module ever goes open source we can just contribute it.
Alternatively we write in tripal support for the cmap.js viewer as a field and make our own fully developed module.

### Data structure

We need to insert into
*  `featuremap` : name, description, unittype (cvterm).
*  `featurepos`: feature, map_feature_id , mappos (double)
   - map_feature_id links to the feature (map) upon which the feature is being localized.
* `featurerange`: feature, leftstartf_id (feature), righttartf_id (feature)
   -  leftstartf_id, leftendf_id, rightstartf_id, rightendf_id are the ids of features with respect to which the feature is being mapped.

**Comment by bradfordcondon** [comment]
I started a loader here https://github.com/statonlab/tripal_cmap_loader

Some unanswered questions before i continue:

* Do we want to actually have this stuff in our DB or would we rather host flat files
I ask this namely because were going to have to create features for the map (the linkage group) and for the marker (the SSP, the BAC, whatever)
* Whats up with the start/end?  I think most of our markers are goign to be "single location" only.  In that case do we just have left start = right start, and leave ends = null?

**Comment by mestato** [comment]
Yes, we want it in the DB, so that it is searchable from the main search box and we can store ancillary information (primers, publication, alleles, whether the marker appears on more than one map, genomic location, etc).

**Comment by bradfordcondon** [comment]
note redundancy with #235 .  Next step after loader is to define a content type although that step will require more thought re: meshing with tripal_map if its even possible.

>map markers in chado (new entity bundle) with sequences and map locations where available

One thing im mulling over... does hte loader load ALL markers as a SO type marker?  or does it load it depending on the specific type (ie, SSR, RFLP).  The problem with loading the specific type is that you can't have a signel bundle contain all your markers.
The chado solution is to load in *two* features for a marker, one being type marker, the other being type SSR, and then associating htem via feature_relationship.

**Comment by bradfordcondon** [comment]
The loader that lacey's modules use is a *VCF* loader
https://github.com/UofS-Pulse-Binfo/genotypes_loader
If nothing else I should try to model my feature usage in the same manner.  Still trying to figure out if i need two features or one per marker (ie a marker feature and an SSR feature, related by is_a_marker)

**Comment by bradfordcondon** [comment]
ok i think we want to be using the [main lab loader](https://github.com/tripal/mainlab_chado_loader.git) or at least looking at it for a guideline on using the map chado module.

**Comment by almasaeed2010** [comment]
So to make this searchable, we want our maps to exist as entities. 
I am gonna need to know:
- What those entities should include?
- Will the CMap graph be displayed on the map entity page or on an organism page?

**Comment by bradfordcondon** [comment]
for now:  DON'T load maps into chado.

Instead, create map bundle.   Insert JUST the map into chado, no markers etc.  Figure out how we want to load into chado loader.

then in the description field, dump to flat file.

**Comment by bradfordcondon** [comment]
The[ cmap loader is currently functional](https://github.com/statonlab/tripal_cmap_loader).  However we probably want to hold off on loading the full cmap file into chado for now, as we have no visualization, no use for the data really.  The closest we have is that we do have SSRs loaded in as props, and we want to change those over to features... I think those are the same SSRs in the map files.

Until we have a visualizer that can utilize chado, we should probably stick to the below protocol:

* Create map entity
* Link publication
* hardlink cmap file for downloading

**Comment by bradfordcondon** [comment]
I'm closing this issue since the module is complete!  We can reopen if we have problems enabling module on dev/live, but right now we arent loading into chado anyway so i'm calling it done.
