### ISSUE TITLE
Elasticsearch sometimes misses the node title

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#246]
The ES results don't always have a node title!
![screen shot 2018-04-18 at 12 26 29 pm](https://user-images.githubusercontent.com/1512664/38945154-bd5468aa-4303-11e8-9ca6-c1bd46b0cb53.png)

Notice the blast database.

**Comment by bradfordcondon** [comment]
Decision: we dont want these blast dbs showing up in search at all.  However, as long as we cna't change the view permissions, we cant fix that without coding in an exception.
https://github.com/tripal/tripal_blast/issues/30

**Comment by almasaeed2010** [comment]
Done on dev and live (see ES 7.x-2.1 release)
