### ISSUE TITLE
Kiwi Genome 

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#249]
New paper:
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-4656-3

**Comment by Lupercal2** [comment]
The files are located in [this github repo.](https://github.com/PlantandFoodResearch/Red5_WGS_Manual_Annotation/tree/master/Gene_Model_Annotation/Fasta) Contains the cds, proteins, assembly and annotations.  

The regexp used on dev for the kiwi is `>(A.*\.[1-9]*)`

**Comment by almasaeed2010** [comment]
@Lupercal2 let's change the regex to be `>(A.*\.[0-9]*)`

**Comment by Lupercal2** [comment]
important links:

[organism page](http://160.36.205.61:8095/bio_data/2288674)

analysis
[genome assembly](http://160.36.205.61:8095/bio_data/2288674)
 [blastx uniprot](http://160.36.205.61:8095/BLAST-annotation/2322704)
[blastx against trembl](http://160.36.205.61:8095/BLAST-annotation/2322703)

**Comment by mestato** [comment]
The genome assembly link above need to be corrected, it goes to the organism. Its important to note that the links are to the dev site (later you will need to provide the live site links). 

The genome assembly is named "Actinidia chinensis mRNA and polypeptide genome assembly". This needs to be changed to "Actinidia chinensis genome assembly".

**Comment by cricha59** [comment]
Analysis created for "Actinidia chinensis"
http://160.36.205.61:9090/bio_data/415

**Comment by cricha59** [comment]
Jobs page
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22374

**Comment by cricha59** [comment]
### Gene
```
>Acc00001.1 [locus_tag=CEY00_Acc00001] [length=1296] [bioview=7014728] [product=Switch-associated protein] [manual_quality_score=2F] [status=full_length]
ATGGCTTCCAATGGAGCTTCTGCGAGAGAAGGGGATACACAGAGCAGCTTGGAGAAGATCAAACGCCAAT
TAGCATCTAACTCTGGAAGAAATTTATTGCAAGGTCCTCTACTCAAGCGATCCGAAACGCTGAGGAAATG
GAATGAGAGATGGGTGATCTTAGACCCAACAACTGGAAAAATGGACTACAAGATTAGGAGAAACGAGCCA
ACTGTCAAGGGGACAATTATATTTGATGCAAATAGCACGATAACAATATCTCCTGTGAATTTCCATGGAC
TACCGAAGTATGATGGCTGCTGTTTCTATATTGGAACACCACAGAAAAAAGATTATTTCCTCTGTGCAGA
AACCCCTGGTGCGGCTAGAGCTTGGGTATCAACTTTACATGCGACACAGTTGGTTCTGAAGGCACATAAA
GAGTCCGTGAATTCCTTGAGTGGGAATGGTTCTGCAAAGCTAGGAACAGTTGCGACTGTAGTTGCCGCTG
CCAATTCAACAACTCTGGAAGCTTCTAAAGAAATTGAGGCAGCAATGCAGATTGCCATGAGGAATGCGTT
AGGAGCAATGATGAATAGACCAACCGATGGTCCAATGGATGACCTCACGGTCATGAAGGAGACACTAGGA
```
### Peptide
```>Acc00001.1 [locus_tag=CEY00_Acc00001] [length=431] [bioview=7014728] [product=Switch-associated protein] [manual_quality_score=2F] [status=full_length]
MASNGASAREGDTQSSLEKIKRQLASNSGRNLLQGPLLKRSETLRKWNERWVILDPTTGKMDYKIRRNEP
TVKGTIIFDANSTITISPVNFHGLPKYDGCCFYIGTPQKKDYFLCAETPGAARAWVSTLHATQLVLKAHK
ESVNSLSGNGSAKLGTVATVVAAANSTTLEASKEIEAAMQIAMRNALGAMMNRPTDGPMDDLTVMKETLG
VKDEELQNLARDLRARDSTIKEIAEKLSETAEAAEAAASAAHTMDEQRRVACVEIECLAKDSEKQLDSSM
LKLRESEEKVMVLSKEIDQLIKQRDSALHEAQLWRSELAKARERVVILEGAVVRAEEKVRVSEADAEARI
KEAAQKEAAALKEKLELLAYVNMLQAQLQRQQVDTKQVFEEKIESCSDNGNTVPRTKHVDPSEDNVDKAC
GSAKSRPSWRW
>Acc00002.1 [locus_tag=CEY00_Acc00002] [length=257] [bioview=7014729] [product=AT-hook motif nuclear-localized protein] [manual_quality_score=2F] [status=full_length]
MFSSSASQTTTPSMADLTNLSFIGSKGSEPENSSMNKVPKVMPTAAEGETIRRPRGRPAGSKNKPKQPII
```

**Comment by cricha59** [comment]
@almasaeed2010  What regular expression should I use to match the peptide names with the cds?

**Comment by almasaeed2010** [comment]
You can use this regexp `>(.*?)`

**Comment by cricha59** [comment]
Polypeptide job link
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22381

**Comment by almasaeed2010** [comment]
Try this: `>(Acc\d*\.?\d?)`

**Comment by almasaeed2010** [comment]
Path to CDS:
`/home/www/sites/default/files/sequences/kiwi/Acc_all_models_cds.fasta`

Path to peptides:
`/home/www/sites/default/files/sequences/kiwi/Acc_all_models_peptide.fasta`

**Comment by cricha59** [comment]
### Links for AG site
Completed job link
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/674317
Organism link
https://hardwoods.ag.utk.edu/organism/Actinidia/chinensis
Genome assembly link
https://hardwoods.ag.utk.edu/Genome-assembly/2209460

**Comment by cricha59** [comment]
BLASTX
`nohup blastx -query Acc_all_models_cds.fasta -db /data/libraries/uniprot/uniprot_sprot.fasta -out kiwi_blast_sprot.xml -evalue 1e-5 -outfmt 5 &`

**Comment by cricha59** [comment]
### Blast on ACF 
Swissprot
```#PBS -N swissprot_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/kiwi/split/Acc_all_models_cds.fasta.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/kiwi/blast/swissprot/kiwi_swissprot_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5```

**Comment by cricha59** [comment]
InterPro
```
#PBS -N kiwi_ips
#PBS -A ACF-UTK0011
#PBS -S /bin/bash
#PBS -t 1-200
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=3:30:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/interproscan-5.28-67.0/interproscan.sh \
 -i /lustre/haven/gamma/staton/projects/undergrads/kiwi/aa_splits/Acc_all_models_peptide.fasta.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/gamma/staton/projects/undergrads/kiwi/ips/xmls \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/gamma/staton/projects/undergrads/kiwi/ips/tmp \
 >& /lustre/haven/gamma/staton/projects/undergrads/kiwi/ips/tmp/$PBS_ARRAYID.out
```

**Comment by almasaeed2010** [comment]
@cricha59 unfortunately your trembl job seems to have failed on the ACF. However, the swissprot succeeded.

The files are now on the staging server and ready to be uploaded using Tripal. The path for the files is:
```
/var/www/sites/default/files/sequences/kiwi/blast/swissprot
```

**Comment by cricha59** [comment]
Chado BLAST results job page link
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/696226

**Comment by almasaeed2010** [comment]
InterProFiles path:

```
sites/default/files/sequences/kiwi/ips
```

**Comment by cricha59** [comment]
Chado InterProScan Loader job page link
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/696232

**Comment by cricha59** [comment]
Trembl although successfully uploaded does not appear on dev sit @almasaeed2010

**Comment by cricha59** [comment]
****Live site****
Organism
https://www.hardwoodgenomics.org/organism/Actinidia/chinensis
Analysis
https://www.hardwoodgenomics.org/Genome-assembly/2243625?tripal_pane=group_summary_tripalpane
Inter Pro Scan Annotation created
https://www.hardwoodgenomics.org/InterProScan-annotation/2243626

**Comment by cricha59** [comment]
Need permissions for BLAST annotation. It is not in "Add tripal content"

**Comment by cricha59** [comment]
@almasaeed2010  Swissprot shows but trembl does not.
https://hardwoods.ag.utk.edu/gene/2277240?tripal_pane=gp_format__blast_results17982

**Comment by almasaeed2010** [comment]
@cricha59 for the live site (from meg):

>could we change “all model” to “all gene model”

**Comment by cricha59** [comment]
@bradfordcondon I downloaded the gff file but Abdullah and I are not quite sure the next step. Any help would be appreciated. Here is the link where the files are located.

https://www.ncbi.nlm.nih.gov/genome?LinkName=nuccore_genome&from_uid=1371540932

**Comment by bradfordcondon** [comment]
Have you read https://www.bradfordcondon.com/2018/03/28/loading_gff3_tripal.html
do that first.


* Filtering the GFF: this is @mestato 's call really.   Glancing at it, you can see that it will create genes, mrna, cds, exons.  I would say these are all appropriate.
* loading the parent FASTA whatever FASTA file contains, for example `CM009654.1`
* use the tripal 3 gFF importer.  See: https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/genomes_genes.html?highlight=gff#loading-a-gff3-file

If you have more specific questions im happy to help.

```
CM009654.1	Genbank	region	1	18577340	.	+	.	ID=id0;Dbxref=taxon:1590841;Name=LG1;chromosome=LG1;country=New Zealand: Te Puke;cultivar=Red5;gbkey=Src;genome=chromosome;mol_type=genomic DNA;sex=female;tissue-type=young leaf;variety=chinensis
CM009654.1	Genbank	gene	5213	8548	.	+	.	ID=gene0;Name=CEY00_Acc00111;gbkey=Gene;gene_biotype=protein_coding;locus_tag=CEY00_Acc00111
CM009654.1	Genbank	mRNA	5213	8548	.	+	.	ID=rna0;Parent=gene0;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00111.1;orig_transcript_id=gnl|WGS:NKQK|Acc00111.1_mrna;product=Protein NRT1/ PTR FAMILY 5.2 like
CM009654.1	Genbank	exon	5213	5439	.	+	.	ID=id1;Parent=rna0;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00111.1;orig_transcript_id=gnl|WGS:NKQK|Acc00111.1_mrna;product=Protein NRT1/ PTR FAMILY 5.2 like
CM009654.1	Genbank	exon	6661	7226	.	+	.	ID=id2;Parent=rna0;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00111.1;orig_transcript_id=gnl|WGS:NKQK|Acc00111.1_mrna;product=Protein NRT1/ PTR FAMILY 5.2 like
CM009654.1	Genbank	exon	7502	8548	.	+	.	ID=id3;Parent=rna0;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00111.1;orig_transcript_id=gnl|WGS:NKQK|Acc00111.1_mrna;product=Protein NRT1/ PTR FAMILY 5.2 like
CM009654.1	Genbank	CDS	5242	5439	.	+	0	ID=cds0;Parent=rna0;Dbxref=InterPro:IPR000109,InterPro:IPR016196,NCBI_GP:PSS35628.1;Name=PSS35628.1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=CDS;orig_transcript_id=gnl|WGS:NKQK|Acc00111.1_mrna;product=Protein NRT1/ PTR FAMILY 5.2 like;protein_id=PSS35628.1
CM009654.1	Genbank	CDS	6661	7226	.	+	0	ID=cds0;Parent=rna0;Dbxref=InterPro:IPR000109,InterPro:IPR016196,NCBI_GP:PSS35628.1;Name=PSS35628.1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=CDS;orig_transcript_id=gnl|WGS:NKQK|Acc00111.1_mrna;product=Protein NRT1/ PTR FAMILY 5.2 like;protein_id=PSS35628.1
CM009654.1	Genbank	CDS	7502	8390	.	+	1	ID=cds0;Parent=rna0;Dbxref=InterPro:IPR000109,InterPro:IPR016196,NCBI_GP:PSS35628.1;Name=PSS35628.1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=CDS;orig_transcript_id=gnl|WGS:NKQK|Acc00111.1_mrna;product=Protein NRT1/ PTR FAMILY 5.2 like;protein_id=PSS35628.1
CM009654.1	Genbank	gene	14371	28455	.	+	.	ID=gene1;Name=CEY00_Acc00112;gbkey=Gene;gene_biotype=protein_coding;locus_tag=CEY00_Acc00112
CM009654.1	Genbank	mRNA	14371	28455	.	+	.	ID=rna1;Parent=gene1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00112.1;orig_transcript_id=gnl|WGS:NKQK|Acc00112.1_mrna;product=Tuberculostearic acid methyltransferase
CM009654.1	Genbank	exon	14371	14482	.	+	.	ID=id4;Parent=rna1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00112.1;orig_transcript_id=gnl|WGS:NKQK|Acc00112.1_mrna;product=Tuberculostearic acid methyltransferase
CM009654.1	Genbank	exon	14715	14905	.	+	.	ID=id5;Parent=rna1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00112.1;orig_transcript_id=gnl|WGS:NKQK|Acc00112.1_mrna;product=Tuberculostearic acid methyltransferase
CM009654.1	Genbank	exon	18373	18590	.	+	.	ID=id6;Parent=rna1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00112.1;orig_transcript_id=gnl|WGS:NKQK|Acc00112.1_mrna;product=Tuberculostearic acid methyltransferase
CM009654.1	Genbank	exon	19024	19129	.	+	.	ID=id7;Parent=rna1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00112.1;orig_transcript_id=gnl|WGS:NKQK|Acc00112.1_mrna;product=Tuberculostearic acid methyltransferase
CM009654.1	Genbank	exon	19217	19318	.	+	.	ID=id8;Parent=rna1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00112.1;orig_transcript_id=gnl|WGS:NKQK|Acc00112.1_mrna;product=Tuberculostearic acid methyltransferase
CM009654.1	Genbank	exon	19457	19516	.	+	.	ID=id9;Parent=rna1;experiment=COORDINATES:Manual curation using Apollo2 with RNASeq;gbkey=mRNA;orig_protein_id=gnl|WGS:NKQK|Acc00112.1;orig_transcript_id=gnl|WGS:NKQK|Acc00112.1_mrna;product=Tuberculostearic acid methyltransferase

```

**Comment by mestato** [comment]
I think we normally only load the gene and mrna. Lets talk more about this today at the meeting.

**Comment by cricha59** [comment]
AG site
KEGG Annotation https://hardwoods.ag.utk.edu/kegg_brite_data/2611107
KEGG job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/475788

**Comment by cricha59** [comment]
Live site
KEGG Annotation https://www.hardwoodgenomics.org/KEGGresults/2480845
KEGG  Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/501393

**Comment by cricha59** [comment]
AG SITE
Chado FASTA GFF Loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs
Chado GFF3 FASTA Loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/500336

**Comment by cricha59** [comment]
LIVE SITE
BLAST db for cds https://www.hardwoodgenomics.org/content/actinidia-chinensis-transcripts
BLAST db for peptides https://www.hardwoodgenomics.org/content/actinidia-chinensis-peptides

**Comment by CaseyRichards92** [comment]
AG SITE
JBrowse https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/503917

**Comment by mestato** [comment]
Comments on JBrowse for dev site:
- I get “error reading from name store” - I think @almasaeed2010 has solved this before, but I can’t remember what its about. it then loads fine
- we also has a trick where clicking on the feature gives you an option to go to the gene page on hwg, which would be good to get working

**Comment by patricksis** [comment]
https://www.hardwoodgenomics.org/admin/tripal/extension/tripal_jbrowse/management/instances/2
^ This is the JBrowse instance Casey did a while back just putting it for continuity sake

**Comment by patricksis** [comment]
@cricha59 
Gotta add cross reference and then this organism is good to go.
