### ISSUE TITLE
Remove all tripal 2 nodes once upgrade is complete

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#25]

**Comment by bradfordcondon** [comment]
abdulluah would like to unpublish, rather than delete, for now.

**Comment by bradfordcondon** [comment]
unpublished 1-22-18
Note we did not use the copy title or migrate url tool: this was done by @almasaeed2010 manually.

**Comment by bradfordcondon** [comment]
the delete node job failed first time through.

Now we have a bunch of weird no-title nodes.

![Screen Shot 2018-01-23 at 3.52.08 PM](http://static.gitscout.com/20962a509d22186001d183c9dca6933298ba7ce93b28567032bad10587e6ffb4.png)
editing them shows that the fields are all blank !!!!  The entities are still ok, though.

**Comment by bradfordcondon** [comment]
all tripal entities deleted on dev.
