### ISSUE TITLE
Hazelnut genetic map and QTLs

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#254]
[Genetic mapping and QTL analysis in European hazelnut (Corylus avellana L.)](https://link.springer.com/article/10.1007%2Fs11032-016-0450-6)

**Comment by patricksis** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/4877
This is the completed job for the organism

**Comment by jwest60** [comment]
i cant find the genetic map file for this paper

**Comment by mestato** [comment]
Me neither. Email sent to corresponding author:

"I run the hardwood genomics website (https://hardwoodgenomics.org/), a web portal to provide open access tools for exploring tree genomes and transcriptomes. I am in the process of adding genetic maps to the site and would like to add your hazelnut map from the 2016 paper "Genetic mapping and QTL analysis in European hazelnut (Corylus avellana L.)".  I would provide links to your paper and any other sites you request to make sure you receive credit for this work.

Unfortunately, I have been unable to find the map marker sequences and marker order in a downloadable format.  Would you be willing to share that information?
"

**Comment by mestato** [comment]
No response after 5 days, likely a lost cause. Closing.
