### ISSUE TITLE
Stats on Q. rubra transcriptome page are wrong

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#256]
https://hardwoodgenomics.org/Transcriptome-assembly/1963023?tripal_pane=group_description_download

Should be:
Number of Transcripts	52,662
Transcript N50	1,244 bp
Transcript Average Length	778 bp
Number of Proteins	27,764
Protein N50	368 aa
Protein Average Length	293 aa

**Comment by almasaeed2010** [comment]
copy of old data in case it's needed:
<table class="table table-sm">
 <tr><td>Number of Transcripts</td><td>78,834</td></tr>
 <tr><td>Transcript N50</td><td>1,427 bp</td></tr>
 <tr><td>Transcript Average Length</td><td>869 bp</td></tr>
 <tr><td>Number of Proteins</td><td>42,665</td></tr>
 <tr><td>Protein N50</td><td>365 aa</td></tr>
 <tr><td>Protein Average Length</td><td>291 aa</td></tr>
</table>

**Comment by almasaeed2010** [comment]
fixed dev and live
