### ISSUE TITLE
JBrowse - non "primary" transcripts link to empty page

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#258]
Only the "primary" transcript in a reference genome gets an entity page, so "secondary" transcripts link to nowhere. Should we 

- redirect these pages to the primary transcript (and add info on secondary transcript to that page?)
- start focusing on storing genes as entities and transcripts are subset features that show up on those entity pages

Example from Chinese chestnut: 
https://hardwoodgenomics.org/feature/maker-scaffold00690-augustus-gene-046-mRNA-2

**Comment by bradfordcondon** [comment]
Do you care about alternative transcript splicing?  If yes, then we need features.  If not, then we want to redirect.

**Comment by almasaeed2010** [comment]
For the time being, as a temporary fix, we have amended the Chinese chestnut script to map `mRNA-2` to `mRNA-1`.

**Comment by bradfordcondon** [comment]
great!

The conclusion from the discussion I think was to load in the isoforms as well.  Do we have the sequences anywhere?  Reloading the same file should be OK because it'll update the primary transcripts that are already loaded.

If not we can load in the GFF and keep the mrna-2's... this wont have the sequences though.

**Comment by mestato** [comment]
Yeah, so I think the ideal is to have a gene entity bundle and then have the mRNAs (one or more) show up as related features. All mRNAs will have a nucleotide sequence and some will also have a peptide sequence (another related feature). For chestnut we have both a gff3 file and a transcripts files. Its easy enough to figure out the gene name from the files. For example

`maker-scaffold00001-augustus-gene-1.54-mRNA-1`
and
`maker-scaffold00001-augustus-gene-1.54-mRNA-2`
are both mRNAs from the gene
`maker-scaffold00001-augustus-gene-1.54`

So its all figure-out-able with regexs.

**Comment by bradfordcondon** [comment]
yeah.  its even easier than that because the GFF contains the relationships.  If you load in the GFF first, and set the FASTA importer to update only, then you have no problems finding relationships.

**Comment by bradfordcondon** [comment]
Revisiting this.

So we either a) write a custom migration to transfer annotations from the mrna to the gene, or b) reload everything.

b) is much easier but requires finding the data.  I'll look and see wahts available easily.

**Comment by bradfordcondon** [comment]
shoot.  it just occured to me.... when we publish mRNA, we'll always create mRNAs, even if we dont want them for Chestnut.  

So if we go through with this plan, we'd have entities for both gene and mRNA (which i dont think we want).  OR we'd have to continually delete mRNA as they get published.

**Comment by bradfordcondon** [comment]
closing this and moving discussion to #226
