### ISSUE TITLE
Northern Red Oak Genetic Map

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#260]
https://www.ncbi.nlm.nih.gov/pubmed/28558688

We have sequence files on the staton server if you can't find them in the supplemental material, just ask if needed.

**Comment by almasaeed2010** [comment]
How do we get the necessary files for the genetic map? I managed to get the sequences/fasta but I am not sure how to convert that into a genetic map file. Any ideas?

**Comment by mestato** [comment]
Try [Additional File 3](https://static-content.springer.com/esm/art%3A10.1186%2Fs12864-017-3765-8/MediaObjects/12864_2017_3765_MOESM3_ESM.xlsx) from the paper

**Comment by almasaeed2010** [comment]
At first I thought this file all the data needed to construct a map using our tripal_cmap_loader module, but it looks like it's a completely different format that I couldn't make much sense of. The cmap loader repo [explains what columns to we require](https://github.com/statonlab/tripal_cmap_loader#expected-cmap-data) and it doesn't look like everything exists in this file.

@bradfordcondon when you get a chance can you take a quick look at this file and try to make sense of it?

**Comment by almasaeed2010** [comment]
If it helps at all, this is the description for this file:


>Q. rubra mapped markers and associated data. The table shows all of the mapped framework and SNP markers, the cM distances between them, marker category, position on the Q. rubra linkage group, the sequence in which the marker occurs and the genotypes for the 217 full-sib progeny used for mapping.

**Comment by bradfordcondon** [comment]
thanks thats helpful. 
* Ignore all SMx columns: those are the 217 full-sib progeny.
* ignore sequence

The information you need is the LG, locus, and Position.


So map_acc = Organism.LG
map_name = LG (LG1, LG2...)
map start/start - figure out from max/min of each LG.  I think i wrote a pytohn script for this, did i include it?
locus/feature = Locus.
Feature start/stop = position
Feature type = I dont know but they'll all be the same, need to look at the paper.  Polymorphism?
is_landmark = 0

**Comment by bradfordcondon** [comment]
Theres no way to associate teh loci to features, is there?

**Comment by almasaeed2010** [comment]
>Theres no way to associate the loci to features, is there?
I assume we can't use the sequences to get that info?

**Comment by bradfordcondon** [comment]
you could use that info to associate with features but would be its own seperate analysis.  So the answer for now is no, use the scheme i propose above.

**Comment by almasaeed2010** [comment]
alright thanks that's helpful.

**Comment by almasaeed2010** [comment]
>map start/start - figure out from max/min of each LG. I think i wrote a pytohn script for this, did i include it?

The cmap loader docs says that those columns (map start/end) are not actually used so I assume we can put a placeholder there and ignore it.

**Comment by bradfordcondon** [comment]
oh if that what i say :)  then sure.  theres nowhere to store that information except as a featuremapprop, and its not useful so no point...

**Comment by mestato** [comment]
Markers starting with "loc" are SNPs, markers starting with anything else are "SSRs"

**Comment by jwest60** [comment]
working on changing Additional File 3 above into a cmap appropriate file, but i'm missing `feature_name` and `feature_accession`

this is what i have so far, some of the information may be wrong
![image](https://user-images.githubusercontent.com/32902460/51631340-71c72c80-1f1a-11e9-952c-f5ca1bf8a3bf.png)

not sure if the headers are needed

**Comment by mestato** [comment]
- For map_acc change "organism" to "Q_rubra". 
- In general, the feature_name and feature_accession can be identical to locus_accession (and that's the model show in https://github.com/statonlab/tripal_cmap_loader#expected-cmap-data)
- map start is 0, map stop is the location of the last marker on that map. so in the case of LG1, it starts with the first marker at 0 and the last marker at 72.535. So the map stop would be 72.535 for all columns with LG 1.

**Comment by almasaeed2010** [comment]
Thanks for the clarifications @mestato 

Just a note that `map_start` and `map_stop` are not actually used and can be safely ignored or zeroed out

**Comment by jwest60** [comment]
@mestato Here's Quercus Rubra with the genetic map on the dev site:

[organism](https://hardwoods.ag.utk.edu/organism/Quercus/rubra?tripal_pane=group_physical_and_genetic_map)

[map](https://hardwoods.ag.utk.edu/mapviewer/3/LG1)

![image](https://user-images.githubusercontent.com/32902460/51706357-3b59e200-1fec-11e9-8226-f07e7ab2b12d.png)

**Comment by bradfordcondon** [comment]
looks like the map field isnt configured to display in a tripal pane, let me correct that.

**Comment by bradfordcondon** [comment]
it also looks like the map didnt load right: e verythign is on one linkage group, LG1.  There should be multiple linkage groups.  (LG1, LG2, LG3...) . Did you adapt the cmap file yourself @jwest60 ?   can you show it to me?

**Comment by jwest60** [comment]
Yup, I created the cmap file manually from the Excel spreadsheet. Here's the cmap file:

[quercus_rubra.cmap.gz](https://github.com/statonlab/hardwoods_site/files/2793533/quercus_rubra.cmap.gz)

**Comment by bradfordcondon** [comment]
ok, so LG2, 3, etc, are in the cmap file you loaded.  Next question, are they in the database.

**Comment by bradfordcondon** [comment]
```
 select * from chado.feature where name='LG2';
hardwoods_dev=# select * from chado.feature where name='LG1';
6614487		19	LG1	Q_rubra.LG				124	f	f	2019-01-24 15:05:49.199909	2019-01-24 15:05:49.199909
```

nope.  Why not?  must be something wrong with the loader....
let me try loading it on my dev site.

**Comment by bradfordcondon** [comment]
please review the column mappings

https://github.com/statonlab/tripal_cmap_loader#cmap-column-to-chado-mapping

map_acc is defined as: 

>uniquename for mapping feature IE chromosome, scaffold

your map_acc value is always Q_rubra.LG.  it should be Q_rubra.LG1, Q_rubra.LG2, etc.

because you se tthe uniquename of each linkage group to the same name, it all gets loaded into one linkage group, named Q_rubra.LG

Maybe its confusing because you think one o the columns should be the name of the map?  No column is the name of teh map.  Map_acc and map_name refer to the linkage group only.

while we're talking: your map_stop column needs to  be the max value for that linkage group.  for LG_1, that should be 72.535, instead of 0.

**Comment by jwest60** [comment]
ah, i see, i don't really understand all the jargon like mapping features and linkage groups, so i'm just taking my best guess at what values should go into those columns based on the documentation and comments on this issue

i'll change the map_acc as well as the map_stop column and update with results

**Comment by bradfordcondon** [comment]
i see the problem
https://github.com/statonlab/hardwoods_site/issues/260#issuecomment-425935660


>The information you need is the LG, locus, and Position.
>So map_acc = Organism.LG
>map_name = LG (LG1, LG2...)

i was suggesting you name the map_acc the organism's name and the LG (linkage group's) name.  you thought i was saying the column should always be a literal `organism.LG` instead of the organism name and the LG name.  Meg noticed and it was corrected  Q_rubra.LG instead of Q_rubra.[name of the linkage group]

**Comment by jwest60** [comment]
i just updated the cmap and reran the importer on dev, but the job likely won't be run until tomorrow. job id = 505467

until then, here's the updated cmap in case i missed anything
[q_rubra2.cmap.gz](https://github.com/statonlab/hardwoods_site/files/2793766/q_rubra2.cmap.gz)

**Comment by bradfordcondon** [comment]
looks like you've resolved it, way to go.

i havent looked at the code closely, you might find you near to clear the previous map's data before re-importing.  i dont know if the markers will now appear twice, once on LG1, and once on its correct linkage group.

**Comment by almasaeed2010** [comment]
I ran the job manually and there was an error. Here is the output:

```
2019-01-25 08:34:52: Job ID 505467.
2019-01-25 08:34:52: Calling: tripal_run_importer(197)

Running 'Chado Cmap loader' importer
NOTE: Loading of file is performed using a database transaction. 
If it fails or is terminated prematurely then all insertions and 
updates are rolled back and will not be found in the database

processing marker 0
Done.

Remapping Chado Controlled vocabularies to Tripal Terms...
Done.
SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32)
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(32)
```

**Comment by almasaeed2010** [comment]
>while we're talking: your map_stop column needs to be the max value for that linkage group. for LG_1, that should be 72.535, instead of 0.

If this is the case, we need to update the readme in tripal_cmap_loader repo which suggests that it is not used ->
<img width="661" alt="screen shot 2019-01-25 at 7 45 03 am" src="https://user-images.githubusercontent.com/1512664/51746794-54f33c00-2075-11e9-8a9f-ec5d2aea8dc3.png">

**Comment by bradfordcondon** [comment]
oh ok then who cares.  It's still true, those are the correct map start/stop values, but i forgot the importer ignores them---- sorry joe.

**Comment by almasaeed2010** [comment]
@jwest60 the issue with the field was fields has been fixed. You'll need to reload the data and re-enable fields. I'll fix the mview.

**Comment by jwest60** [comment]
@bradfordcondon after reloading the data, we have multiple linkage groups

![image](https://user-images.githubusercontent.com/32902460/52003322-2ec50600-2492-11e9-8011-b92c8ee231b9.png)

**Comment by bradfordcondon** [comment]
great.

We need to make an issue that the sorting is wrong: lg10 should come after LG9, etc. thats a tripal_map issues though.

**Comment by almasaeed2010** [comment]
String sorting vs int sorting. This has to be processed in the PHP side and not using an `ORDER BY` statement. Not an easy prolem to fix if the names are not always prefixed with `LG`

**Comment by bradfordcondon** [comment]
Well unfortunately LG1, LG2 are the full names of the chromosomes


![](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5450186/bin/12864_2017_3765_Fig2_HTML.jpg)

I think this name schema is common enough it should be supported.  We'd want to come up with a list of cases that should be supported (trees x, y z have chromsomes named these ways...)

**Comment by almasaeed2010** [comment]
@jwest60 the module is finally live. Can you take care of loading the data for Q. robur?

**Comment by jwest60** [comment]
genetic map for q. rubra is now live
