### ISSUE TITLE
Pistachio transcriptome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#263]
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-017-3989-7

**Comment by almasaeed2010** [comment]
Data has been removed:

<img width="1210" alt="screen shot 2018-09-18 at 2 49 37 pm" src="https://user-images.githubusercontent.com/1512664/45709450-17742480-bb52-11e8-8387-019b6355e4b8.png">

**Comment by mestato** [comment]
The data is available:
https://www.ncbi.nlm.nih.gov/sra/?term=SRX1880621

**Comment by RaymondS1** [comment]
@cricha59 are you working on this organism?

**Comment by RaymondS1** [comment]
Duplicate issue
