### ISSUE TITLE
Go live with CVTerm Borwser

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#273]
The current version of tripal_cv_xray can go live

**Comment by almasaeed2010** [comment]
Creating the ontology field is resulting in an "500 Error"

**Comment by almasaeed2010** [comment]
Going live is delayed by this issue: https://github.com/tripal/tripal/issues/375#issuecomment-389993039

**Comment by almasaeed2010** [comment]
Ok now that the core issue is fixed, let's pull Tripal on the live server and create the field.

**Comment by bradfordcondon** [comment]
unfortunately i jumped the gun, core issue is not present on dev but persists live.

Do we have any ideas for what could be going on here?

**Comment by almasaeed2010** [comment]
The memory error doesn't happen on dev because I configured it to allow for 4gb+ whereas the live site (for security reasons) only allows 512MB.

**Comment by bradfordcondon** [comment]
ok very helpful for sharing in the tripal issue.

For HWG, would it be possible to dump a warning on dev when we exceed 512MB since we know it will fail in production?

**Comment by bradfordcondon** [comment]
The browser as using the wrong term (data:4231, which isnt a real EDAM accession.)  I've updated the module but the old field must be deleted.

**Comment by bradfordcondon** [comment]
* KEGG is waiting on changes to the OBO generator.
* we should be ok for GO.  however I want to hear back on [this duplicate term issue](https://github.com/tripal/tripal/issues/421) first in case we have to say repopulate cvtermpath or something.

**Comment by bradfordcondon** [comment]
This seems like a big issue to fix I encountered while deploying live. 
 https://github.com/statonlab/tripal_cv_xray/issues/39  
Entities are in the index many times per entity.

**Comment by bradfordcondon** [comment]
issue resolved.  Rerunning the index.
here's one of the early indexed entities:
https://hardwoods.ag.utk.edu/bio_data/132373
