### ISSUE TITLE
Lucas and Joe Tasks

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#274]
>During the meeting today, among other things, we discussed tasks Joe and Lucas could start. Here’s a list for reference.

@jwest60 
* now that cvxray is pretty much done, set up KEGG browsers (see Lucas tasks below)
* make training vids for dev modules (tripaldock, test suite are most important), probably need to work with Abdullah and Bradford to outline a plan for what to include and some good examples
* more on cvxray - adding support for data collections

@Lupercal2
* work with ming to test workflows. report back all confusing parts of the experience as well as how it turns out. keep track of tests on a google doc or sheet somewhere so we can see how long they take to finish and if they fail.
* run ghost koala to get kegg terms for our current transcriptomes

**Comment by bradfordcondon** [comment]
these tasks have all come to pass.  Thanks both for your work on them: closing.
