### ISSUE TITLE
error creating fasta collection

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#277]
from the log:

```
2018-05-23 16:22:18: Calling: tripal_create_collection_files(26)
Writing tab delimeted file.
Writing comma separated file.
Writing protein FASTA file.
Getting entities for ids 0 to 100 of 108
Got 100 entities.
WD php: Error: Cannot access empty property in [error]
TripalTabDownloader->formatEntity() (line 57 of
/var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc).
Error: Cannot access empty property in TripalTabDownloader->formatEntity() (line 57 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc).
Drush command terminated abnormally due to an unrecoverable error. [error]
```

https://www.hardwoodgenomics.org/user/1/data-collections

the protein collection here is null

**Comment by almasaeed2010** [comment]
When creating a collection I get this error:
```
Failed to create the collection 'Sequence Test': Must provide a 'ids' to TripalEntityCollection::addFields().
```

**Comment by bradfordcondon** [comment]
so either we arent selecting hte fields properly (in which case we need to provide some guidance), collections API changed, or collections is broken.

I guess next step is to create a collection using the "vanilla" search

**Comment by bradfordcondon** [comment]
currently trying to create collection on live:

```
Calling: tripal_create_collection_files(30)
Job execution failed: The user's data directory is not writeable:  [error]
public://tripal/users/1.
```

Possible that #166 is involved/responsible?

**Comment by almasaeed2010** [comment]
Is this run using root and/or cron?

**Comment by bradfordcondon** [comment]
drush.

**Comment by bradfordcondon** [comment]
when crontab creates a collection, it does so with priveledges.  When manually running the job via drush, it does not have permissions so it must be run with sudo.  

let's try again.

**Comment by bradfordcondon** [comment]
```
 sudo drush trp-run-jobs --username=hwadmin --root=/var/www/html
2018-06-26 10:02:51
Tripal Job Launcher
Running as user 'hwadmin'
-------------------
2018-06-26 10:02:51: There are 1 jobs queued.
2018-06-26 10:02:51: Calling: tripal_create_collection_files(30)
Job execution failed: The user's data directory is not writeable: public://tripal/users/1.
```

still failed.

**Comment by bradfordcondon** [comment]
I tried creating a collection as a different user.

```
Calling: tripal_create_collection_files(31)
Writing tab delimeted file.
Writing comma separated file.
Writing nucleotide FASTA file.
Getting entities for ids 0 to 100 of 108
Got 100 entities.
WD php: Error: Cannot access empty property in TripalTabDownloader->formatEntity() (line 57 of                                  [error]
/var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc).
Error: Cannot access empty property in TripalTabDownloader->formatEntity() (line 57 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc).
Drush command terminated abnormally due to an unrecoverable error.                                                              [error]
[bcondon@hardwoodgenomics 275]$
```

We therefore have two different issues.  1 is that permissions are messed up for user/1.  the other is we've got errors on line 57.

**Comment by bradfordcondon** [comment]
permissions resolved by deleting folder and letting tripal re-create.

Now we just have the line 57 TabDownloader error

https://github.com/tripal/tripal/blob/3302486540c12042fb26e29acb167176e8c1149c/tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc#L56-L65

**Comment by bradfordcondon** [comment]
Issue created https://github.com/tripal/tripal/issues/478

**Comment by bradfordcondon** [comment]
pushed my fix for the files to be created here

https://github.com/tripal/tripal/tree/478_collections_with_null_fields

however i think theres something else going on so i am not merging yet....

**Comment by bradfordcondon** [comment]
This looks resolved.  I'm able to create collections as both guest and admin.
