### ISSUE TITLE
Test Tseq module from UConn and provide feedback

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#278]
Check out module - will it install, basic bugs, how much faster is it, etc. Is it something we would prefer over our current blast solution?

Full email from Sean:

We've been working on Tripal Sequence Similarity Search (TSeq), an extension module for Tripal 3. The module provides sequence search via Diamond and NCBI BLAST to sites using Tripal. One of the key features is that it exposes site-owned data (protein, gene, genome) to be used as targets in the user's search, or alternatively any user submitted data. It also features Diamond which has considerable speed benefits over BLAST when running BLASTP and BLASTX searches. When the user needs BLASTn or tBLASTn, it will use NCBI's BLAST instead. 

Tseq relies on Tripal Remote Job, another module which was originally developed and modified to work with Tripal 3.  This allows us to run these BLAST searches away from the webserver and bring the results back to the user on the webserver.

We are hoping the HWG folks, currently in Tripal 3 (and anything other Tripal 3 sites), might want to start testing this.  We would like to get early feedback on additional features, etc that would be useful.  We currently have this running on TreeGenes here:
https://treegenesdb.org/Drupal/Diamond/submit

It does require that users register for an account as jobs are connected to Drupal profiles.  Users can view their results and track past jobs through their profile.

CODE:
https://github.com/Ferrisx4/tripal_diamond
and
https://github.com/Ferrisx4/tripal_remote_job

DOCUMENTATION:
https://github.com/Ferrisx4/tripal_diamond/wiki
and
https://github.com/Ferrisx4/tripal_remote_job/wiki

Upcoming Features for TSEQ:
* More robust job summary information
* Linking results back to species pages and/or JBrowse
* Accepting FASTA files for targets (currently requires Diamond or BLAST index)
* Emailing the user when the job has finished (some functionality exists in Tripal Remote Job for this, need to get working).

Upcoming Features for Tripal Remote Job:
* More robust remote job monitoring
* Other HPC scheduler support (SLURM, GridEngine, etc).

**Comment by almasaeed2010** [comment]
- Both modules install without any issues
- Adding remote servers works as expected
- Adding diamond db works as expected
- Running a diamond job:
  - Fails until we create a /tripal_remote_job and make it writeable by the current user. Suggestion: create the folder in the current working directory instead since `/` is only writeable to the root user.
- Results page is not easily findable
- The results page shows the following error: `Error: Error reading input stream at line 2: Invalid character ( ) in sequence`. This is likely an issue on my end.

**Comment by almasaeed2010** [comment]
@mestato should I email them the above list?

**Comment by bradfordcondon** [comment]
reviewed: abdullah will send hte feedback in.

**Comment by almasaeed2010** [comment]
Sent and they said they'll follow up if they have any questions.
