### ISSUE TITLE
drush sql-cli not useable on live

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#282]
```
drush sql-cli
psql: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

I like drush sql-cli, it makes it really simple to modify DB.

**Comment by almasaeed2010** [comment]
This usually means there is a script that uses chado_select_record in a loop.

**Comment by bradfordcondon** [comment]
?  like executing on the site?  Or related to the drush command somehow?

**Comment by bradfordcondon** [comment]
oh ok, and now i can connect.  I see, thanks.
