### ISSUE TITLE
description formats are bad and should feel bad

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#286]
See:

https://www.hardwoodgenomics.org/organism/Acer/saccharum

For some reason there's a bunch of `<br>` tags inserted everywhere.

The example i linked:

```
<b>Other Common Names</b>:  rock maple, hard maple
<br/>
<b>Order</b>:  Sapindales
<br/>
<b>Family</b>:  Aceraceae
<br/>
<b>Chromosome Number</b>: 2n=26
<br/>
<br/>
```

What it should be:

```
<b>Other Common Names</b>:  rock maple, hard maple
<b>Order</b>:  Sapindales
<b>Family</b>:  Aceraceae
<b>Chromosome Number</b>: 2n=26
```

In most cases, the correct html is present in the "Description X" field (which is not displayed).  Please Go through *every organism on live* and make sure that the formatting looks reasonable.  If not, you probably want to copy the correctly formatted description over from Description X.  Please make sure that no information is lost in this process.

**Comment by Lupercal2** [comment]
- [ ] [Castanea mollissima](https://hardwoodgenomics.org/organism/Castanea/mollissima)

- [ ] [Juglans regia](https://hardwoodgenomics.org/organism/Juglans/regia)

- [ ] [Juglans nigra](https://hardwoodgenomics.org/organism/Juglans/nigra)

- [ ] [Fraxinus pennsylvanica](https://hardwoodgenomics.org/organism/Fraxinus/pennsylvanica)

- [ ] [Handroanthus impetiginosus](https://hardwoodgenomics.org/organism/Handroanthus/impetiginosus)

- [ ] [Acer saccharum](https://hardwoodgenomics.org/organism/Acer/saccharum)

- [ ] [Fraxinus excelsior](https://hardwoodgenomics.org/organism/Fraxinus/excelsior)

- [ ] [Cornus florida](https://hardwoodgenomics.org/organism/Cornus/florida)

- [ ] [Quercus rubra](https://hardwoodgenomics.org/organism/Quercus/rubra)

- [ ] [Quercus robur](https://hardwoodgenomics.org/organism/Quercus/robur)

- [ ] [Quercus alba](https://statonlab.slack.com/messages/D9SV38SA3/)

- [ ] [Prunus serotina](https://hardwoodgenomics.org/organism/Prunus/serotina)

- [ ] [Persea borbonia](https://hardwoodgenomics.org/organism/Persea/borbonia)

- [ ] [Nyssa sylvatica](https://hardwoodgenomics.org/organism/Nyssa/sylvatica)

- [ ] [Liriodendron tulipifera](https://hardwoodgenomics.org/organism/Liriodendron/tulipifera)

- [ ] [Liquidambar styraciflua](https://hardwoodgenomics.org/organism/Liquidambar/styraciflua)

- [ ] [Gleditsia triacanthos](https://hardwoodgenomics.org/organism/Gleditsia/triacanthos)

- [ ] [Fraxinus americana](https://hardwoodgenomics.org/organism/Fraxinus/americana)

- [ ] [Fagus grandifolia](https://hardwoodgenomics.org/organism/Fagus/grandifolia) -does not have a description beside order/family and missing picture

- [ ] [Castanea sativa](https://hardwoodgenomics.org/organism/Castanea/sativa)

- [ ] [Castanea dentata](https://hardwoodgenomics.org/organism/Castanea/dentata)

- [ ] [Castanea crenata](https://hardwoodgenomics.org/organism/Castanea/crenata)

- [ ] [Alnus rubra](https://hardwoodgenomics.org/organism/Alnus/rubra) - also missing description beside order/family and no picture of tree. 

- [ ] [Alnus rhombifolia](https://hardwoodgenomics.org/organism/Alnus/rhombifolia)- missing descirption besides order/family also no picture

- [ ] [Hydrangea macrophylla](https://hardwoodgenomics.org/organism/Hydrangea/macrophylla) no description at all. 

- [ ] [Populus deltoides](https://hardwoodgenomics.org/organism/Populus/deltoides) - no description and no image

- [ ] [Populus trichocarpa](https://hardwoodgenomics.org/organism/Populus/trichocarpa) - no description and no image

- [ ] [Castanea mollissima Disease Resistant QTL Regions](https://hardwoodgenomics.org/organism/Castanea/mollissima-Disease-Resistant-QTL-Regions) - no image and this organism had no "Description X"

- [ ] [Quercus lobata](https://hardwoodgenomics.org/organism/Quercus/lobata) - no description /no image

**Comment by bradfordcondon** [comment]
@Lupercal2 organisms missing descriptions and/or images please add.

**Comment by bradfordcondon** [comment]
#268 is resolved.  Live site can again be deited.

**Comment by bradfordcondon** [comment]
@Lupercal2 any luck with this issue now that live site can be edited again?

**Comment by Lupercal2** [comment]
All the trees have had their image and description fixed.

**Comment by bradfordcondon** [comment]
Looks good!  Thanks lucas!
