### ISSUE TITLE
cross-site field for chinese chestnut

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#287]
we want some deliverable for cross-site funcitoning.  Could we create a field whose backend is web-services, that gets chestnut data from tree-genes?

**Comment by almasaeed2010** [comment]
Not yet available but we could ask for them to add simple instructions: https://tripal.info/node/383

**Comment by almasaeed2010** [comment]
Steps to add a cross site field:
- Go to [Tripal » Data Storage » Remote Tripal Sites » Configuration](https://hardwoodgenomics.org/admin/tripal/storage/ws/tripal_sites/edit) and add a new site
- From a bundles fields page, there will be a new field type called Remote Site (see screenshot). 
<img width="1018" alt="screen shot 2018-06-11 at 2 14 45 pm" src="https://user-images.githubusercontent.com/1512664/41228688-e0c850d2-6d81-11e8-95b1-54048aa3890a.png">
- Fill the form and the data will appear on the bundle

Explore an organism on TreeGenes (Juglans regia, English Walnut):
https://treegenesdb.org/Drupal/web-services/content/v0.1/Organism/39727

**Comment by almasaeed2010** [comment]
See issue on core repo: https://github.com/tripal/tripal/issues/423

The PR to fix: https://github.com/tripal/tripal/pull/424

**Comment by almasaeed2010** [comment]
PR was merged and issue fixed.

We can link to Chinese chestnut from any website now.

**Comment by almasaeed2010** [comment]
Here is the chinese chestnut page on TreeGenes: https://treegenesdb.org/Drupal/organism/Castanea-mollissima

We get to pick any field and attempt to get the data displayed on HWG. Any idea which field would be interesting/missing from hwg?

**Comment by bradfordcondon** [comment]
literature and TPPS?  I think TPPS is their main value added

<img width="959" alt="screen shot 2018-08-02 at 8 50 11 am" src="https://user-images.githubusercontent.com/7063154/43584687-179561fe-9631-11e8-81d3-4af93006c0f3.png">

**Comment by almasaeed2010** [comment]
Possible issue (need to investigate more):

Does tripal load this remote data before rendering the page? Does it take long to pull that data from the remote site? If so, we might need to PR a fix for that to asynchronously pull the data after the page with our content fully loaded.

**Comment by almasaeed2010** [comment]
Discovered something about treegenes web services. Not all the fields are available.

TreeGenes Chinese Chestnut:
- Web services: https://treegenesdb.org/Drupal/web-services/content/v0.1/Organism/39190
- Actual page: https://treegenesdb.org/Drupal/bio_data/39190

HWG:
- Web services: https://hardwoodgenomics.org/web-services/content/v0.1/Organism/21
- Page: https://hardwoodgenomics.org/bio_data/21

**Comment by almasaeed2010** [comment]
I think I fully understand how to do this now for any field we want from any website. But I can't do TreeGenes since they don't provide the data in their web-services. Maybe we should ask them why that is?

**Comment by bradfordcondon** [comment]
I have some theories but would need to see their code.  Go ahead and reach out and link the WS page and say we can try and help them figure it out

**Comment by almasaeed2010** [comment]
I reached out to TreeGenes.


Noticed another thing about our web services where we either return an error or empty values.

- Visit: https://hardwoodgenomics.org/web-services/content/v0.1/Organism/21
- Click on [biological_samples](https://hardwoodgenomics.org/web-services/content/v0.1/Organism/21/biological+sample) link. You'll see an error.
- Click on [analysis_browser](https://hardwoodgenomics.org/web-services/content/v0.1/Organism/21/analysis_browser). You'll get an empty body (no value).
- Click on [microsatellite](https://hardwoodgenomics.org/web-services/content/v0.1/Organism/21/microsatellite). You get a value this time.

Could be that we need to define elementinfo in our fields? Or should WS figure out how to display the data automatically?

**Comment by bradfordcondon** [comment]
pinging this issue.  are we awiting on core issue?  If so i have a tag for that.

**Comment by almasaeed2010** [comment]
So I am not sure where to go from here to fix those little things. But, I assume the issues that I found are caused by how the field is handling  the loading of data because it looks like most of what is displayed on each field's page are simply the values of the `value` array. If we want all our fields to support WS we are gonna have to take the time and make sure the load method of all of our custom fields return something useful.

Meanwhile, we can go ahead and add a remote field with any other site (other than TreeGenes).

**Comment by bradfordcondon** [comment]
you could create an organism record for citrus and try hosting fields from it?

**Comment by almasaeed2010** [comment]
Adding a new citrus organism that’s pulling everything from a remote host will take way too much time since we have to create a remote field for everything. On top of that, those fields will still have to be loaded into other organisms even though they are not needed so I don’t think creating that organism is gonna be good for the usability of the site

**Comment by almasaeed2010** [comment]
It's been a while since we looked at this. Do we still want to implement it?
