### ISSUE TITLE
statonlab module showcase

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#291]
- [x] markdown cards for all modules (i have bullet writeups for most, but need images)

- [x] add new custom tags (Travis, github, and Zenodo) that build links for the cards
- [ ] add categories (particularly "in production" and "needs collaborators") that can used to filter.

- [x] Move repo to statonlab and reword to be about the lab.

code
https://github.com/bradfordcondon/condon_tripal_showcase
site
https://bradfordcondon.github.io/condon_tripal_showcase/

The purpose of this showcase is to be able to link somewhere that has all the stuff we do in one attractive place.  people can see what we work on.

**Comment by bradfordcondon** [comment]
If we want it hosted on HWG we need to rethink my approach to this.  

I think I could put some work in to rebuild the site configuration so that it wouldnt be weird on HWG.  However before we go down that road... would it be OK to just linkout to the github pages, which would be hosted at statonlab.github.io/tripal_showcase?

If we need to have it on HWG, then it might make sense to write a module instead, or perhaps implement the existing module that tripal.info uses.   We'd need to redo the display completely.

The nice thing about the seperate jekyll site is its super easy to do.  a single markdown file per module.    markdown is converted into cards.

see the below md which creates the test suite card.


```md
---
layout: post
title:  "Tripal Test Suite"
img: TravisCI-Full-Color.png
---

Tripal Test suite adds PHPUnit testing and Travis Continuous Integration to your module!

### [Tripal Test Suite](https://github.com/statonlab/TripalTestSuite)
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.1257164.svg)](https://doi.org/10.5281/zenodo.1257164)

* One command to add PHPunit with access to your Drupal site, and Travis-CI setup.
* Helper methods, such as **factories** to generate test Chado data.
```

**Comment by mestato** [comment]
I think its fine to just link out from HWG, it doesn't have to look the same on there. A Tripal logo, a few sentences, and links to tripal.info and to our contributions. My thinking is that I'm just as likely to visit other Tripal developers dbs as their github pages, so this might make it more discoverable. Plus statonlab has a zillion repos. Maybe we need a statonlabtripal github account and we can pin this as the top repo as a kind of intro to our scope of efforts? 

Overall, this is a really great way to show our Tripal efforts and impact of the lab, plus it looks nice. :)

**Comment by bradfordcondon** [comment]
>A Tripal logo, a few sentences, and links to tripal.info and to our contributions

This would be the page on HWG right?  If you're happy with this approach awesome, I think its the most straight forward.

I'm also pleased you like the showcase website.  This is just a super rough draft. But I wanted 1-2 sentences and a photo for each module to share with others so they could see what we were working on, what they might want to use....

**Comment by mestato** [comment]
Yep, I was referring to a simple page on HWG to link to the nicer looking Jekyll page.

**Comment by bradfordcondon** [comment]
* [We're still improving a bit but probably nice enough to link out to it]. (https://statonlab.github.io/hardwoods_tripal_showcase/)
* I pinned the repo to statonlab.  shame we cant pin the github pages URL instead.
* [I created a tripal menu item in about: see below.](http://160.36.205.61:8095/content/tripal)
* Feeling a bit uninspired for the text, I'll come back to it.

![screen shot 2018-06-05 at 9 18 28 am](https://user-images.githubusercontent.com/7063154/40978359-6ffa015a-68a1-11e8-9bbd-ac2127f02ac0.png)

**Comment by bradfordcondon** [comment]
abdullah suggested its hard to style pages with very little content.  With that in mind I created a section in [About](http://160.36.205.61:8095/content/about) instead.

With approval it will go on live.

**Comment by bradfordcondon** [comment]
continue to make small improvements.  Need to add "see it in action" URLs for all modules, and hsould probably expand on the full description a bit more/add more info and/or just copy the README...

**Comment by almasaeed2010** [comment]
Reduce the padding of images/icons in cards to make them fit 👍 .

**Comment by bradfordcondon** [comment]
Thanks!  I figured that, adjusted it yesterday.  what do you think of current site?

**Comment by bradfordcondon** [comment]
can go live.

additional requests:

* tooltip for icons
* dont use icons on module page/have description that says "See the code on github..."

**Comment by bradfordcondon** [comment]
still need tooltip (i feel like i'd know what to do if i was using something like webpack...) but added the other request.  added the link live.
