### ISSUE TITLE
Make training vids for dev modules

### ISSUE THREAD

**Issue by jwest60** [statonlab/hardwoods_site#296]
in response to [#274](https://github.com/statonlab/hardwoods_site/issues/274)

create some videos outlining how to use [tripaldock](https://github.com/statonlab/tripaldock) and [tripaltestsuite](https://github.com/statonlab/TripalTestSuite), possibly a mini-series

**Comment by jwest60** [comment]
going to post the notes from my meeting with bradford here as well for some more direction
```
### Videos
##### TripalDock

Video 1 : Starting from scratch: launching a site from nothing using tripaldock.
 prerequisites (docker...)
 command line access? 

##### Test Suite

Video 1 is:
make a fictional, empty module...
* Adding test suite to your project with composer
* testsuite init
* Going to Travis and enabling CI.
```

**Comment by bradfordcondon** [comment]
@jwest60 you've made some good progress on this: friendly reminder to please post complete videos here.

@mestato i dont think you have an official lab channel, do you?   When appropriate ill check with stephen/lacey if they should go on the official tripal account as well.

**Comment by mestato** [comment]
Official tripal channel would be much better. My two videos aren't on an actual channel I don't think... we could create a lab tripal channel if we can't get add to the official tripal one (https://www.youtube.com/channel/UCbmec1Z4LWzBAeWoHdcB_MQ/videos)

**Comment by bradfordcondon** [comment]
im an admin on the tripal account.  I still get a little confused about adding it to the account while maintaining ownership to Joe, ill play with a bit...

**Comment by jwest60** [comment]
https://www.youtube.com/watch?v=5SOfQLypvdE

here's a link to the first one, i'll be uploading the second one once i apply the changes suggested so i'll update in like the next hour or so

i still have the exported mp4s from the movie project if you want to try just uploading them directly to the channel, i'm not really concerned with trying to maintain any ownership for them

**Comment by jwest60** [comment]
https://www.youtube.com/watch?v=g_fmONUgG3s

link to the updated version of the second part of the tripaldock video covering commands and site structure where i tried to clarify what site mapping does and also talked about creating and adding new modules into the module directory

currently writing the script for the first video on the tripal test suite, should be done very soon so i can start recording video and audio for it tomorrow

**Comment by bradfordcondon** [comment]
as these get created lets add them to the README for each module.

**Comment by jwest60** [comment]
https://www.youtube.com/watch?v=hxuiDzRqs9U

first video in the tripal test suite series covering installation and creating / running basic tests

**Comment by bradfordcondon** [comment]
I need to verify with stephen that these videos are appropriate for reposting to the tripal youtube channel.

In addition they should get added to the tripal core documentation.  I'll add it to the docs somewhere...

**Comment by bradfordcondon** [comment]
issue at https://github.com/tripal/tripal/issues/629

**Comment by bradfordcondon** [comment]
There's now a video tutorial section on the tripal:

https://tripal.readthedocs.io/en/latest/dev_guide/tutorials.html

**Comment by jwest60** [comment]
https://www.youtube.com/watch?v=PTJ1Dv8QAag

second video in the tripal test suite series covering factories and database transactions

**Comment by jwest60** [comment]
https://youtu.be/HE2B7YnWYfQ

last video in the tripal test suite series covering seeders and publishing seeder data

should be the last video for training videos for now
