### ISSUE TITLE
unable to run jbrowse perl scripts live

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#299]
### Bug description

running any apollo perl script (necessary to add tracks etc) results in error.

Looks like the extensions library isnt set up correctly.  Could need to reinstall apollo on live, could need to mess with the perl configuration.

### Screenshots

```
sudo ../../jbrowse/bin/flatfile-to-json.pl
Attempting to create directory /data2/apollo/jbrowse/bin/../src/perl5/../../extlib
perl: symbol lookup error: /data2/apollo/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/x86_64-linux-thread-multi/auto/JSON/XS/XS.so: undefined symbol: Perl_Gthr_key_ptr
```

**Comment by bradfordcondon** [comment]
> This type of error usually occurs when using a binary compiled [module that] is used by [a different] version of Perl.

https://stackoverflow.com/questions/18301093/symbol-lookup-error

So we should probably reinstall apollo with the version of perl on live since im assuming that apollo was installe on dev then ported to live where it perhaps has a different version of perl running.

**Comment by bradfordcondon** [comment]
I might wait for abdullah on this one since theres maybe a lot to do for it.  Installing from scratch failed:


```

Package gdlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `gdlib.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gdlib' found
 at Makefile.PL line 447.
*** can not find package gdlib
*** check that it is properly installed and available in PKG_CONFIG_PATH
 at Makefile.PL line 447.
N/A
```

So for now, deleting the fresh install and re-instating the broken install that atl east serves correctly.

**Comment by almasaeed2010** [comment]
That's odd. I usually run the scripts with no problems at all. Do you have the files for the tracks that you wanna add? I'd like to try it again just in case there was an option missing since JBrowse is not great when dealing with flags and options.

**Note** that we do not use Apollo anymore and we only use JBrowse directly.

**Comment by almasaeed2010** [comment]
Fixed on both live and new dev 👍

**Comment by bradfordcondon** [comment]
we were missing all the perl module dependencies and had mismatches, so we re-installed jbrowse and the perl module dependencies.

**Comment by almasaeed2010** [comment]
To fully document this for CentOS 7:

First run:
```
yum groupinstall "Development Tools" -y && yum install libpng-devel gd-devel zlib-devel perl-ExtUtils-MakeMaker -y
```

then navigate to your jbrowse folder (in `/data/apollo/jbrowse` in our case) and run:
```
./setup.sh
```
