### ISSUE TITLE
undergrad curator user role

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#300]
### Feature description

Tripal 3 will soon have many content types installed by default. I think it might be a good idea to simplify the permissions for undergrads working on the site.  This way their "create content" will only show them a short list of the types of content they should see, and will hopefully make their job easier.
### Link to relevant info

see https://github.com/tripal/tripal/issues/441

**Comment by mestato** [comment]
Sounds good to me. (Also we'll probably find a lot of bugs in permissions!)

**Comment by bradfordcondon** [comment]
spent some time trying to set up a [curator admin setting on dev](http://160.36.205.61:8095/admin/people/permissions).  kind of a pain to think about what to give/not give access to.
![screen shot 2018-06-21 at 1 41 08 pm](https://user-images.githubusercontent.com/7063154/41735849-c704be0e-7558-11e8-957f-3aa8626cd652.png)

It does make the admin menu much less intimidating.

Same with the tripal content area: 

![screen shot 2018-06-21 at 1 41 53 pm](https://user-images.githubusercontent.com/7063154/41735896-ed34f9cc-7558-11e8-813d-4e7b712e94dd.png)


The main downside is we now have to manually add permissions for new content types to the curator role, and they might get confused when htey dont have access to something.   I'm kind of ambivalent on if this is a good idea or not.

**Comment by bradfordcondon** [comment]
The contributor role on live has been edited to give *streamlined* permissions.  we may find we have to expand these permissions, but the goal is to keep ti lean so that helpers will only see options to create content that they should be messing with in their role, making it easier to get new peopel started.  That's the hope at least.

https://www.hardwoodgenomics.org/admin/people/permissions/roles
