### ISSUE TITLE
unable to upload files

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#301]
### Bug description

the fasta uploader cant upload files.  Attempting to do so gives this error

### Screenshots
<img width="481" alt="screen shot 2018-06-19 at 8 27 36 am" src="https://user-images.githubusercontent.com/7063154/41597161-a6ca7b3e-739a-11e8-9f3d-da1cf49c1177.png">

### Additional info

I did some DPMing and  "didnt exist" returns, so `!file_prepare_directory($user_dir, FILE_CREATE_DIRECTORY)` is false.
`$user_dir` is `public://tripal/users/1`.
```
 $user_dir = tripal_get_user_files_dir($user);
   dpm($user_dir);
  // First, make sure the directory exists.
  if (!file_prepare_directory($user_dir, FILE_CREATE_DIRECTORY)) {
dpm("didnt exist");
  return FALSE;
  }

```
 
`/var/www/html/sites/default/files/tripal/users/1` does indeed exist and is writeable...

**Comment by bradfordcondon** [comment]
```
 */
function tripal_is_user_files_dir_writeable($user) {
  $user_dir = tripal_get_user_files_dir($user);

if ($user_dir = 'public://tripal/users/1'){
$user_dir = 'public://files/tripal/users/1';}
```
Modifying the tripal_is_user_files_dir_writeable to this fixes the error but causes an error at the next step because it looks for the finished file at tirpal/users/1/ instead of /files/tripal/users/1.

Why is this happening?  Public file system path is set correctly to `sites/default/files` at `/admin/config/media/file-system`.
I could set a symbolic link at sites default  to the tripal folder but that seems like a crazy fix to something thats very likely a site config problem...

**Comment by bradfordcondon** [comment]
when performant drush updatedb:
`opendir(/var/www/html/sites/default/tripal/users/1/temp): failed to open dir: Permission denied filesystem.inc:685                                                                                                                                                            [warning]`

teh permissions are definitely set wrong according to drupal

**Comment by bradfordcondon** [comment]
@almasaeed2010 touched the permissions, but the error still occurs.

**Comment by almasaeed2010** [comment]
Is this issue related to the one on core: https://github.com/tripal/tripal/issues/293 ?

**Comment by almasaeed2010** [comment]
I tested the fix Stephen added on my local machine and it was working. So it shouldn't be a core issue anymore.

**Comment by bradfordcondon** [comment]
resolved.
