### ISSUE TITLE
Quercus robur genome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#304]
Finally out:
https://www.nature.com/articles/s41477-018-0172-3

**Comment by almasaeed2010** [comment]
Data: ftp://ftp.sra.ebi.ac.uk/vol1/ERZ403/ERZ403029/Qrob_H2.3_Genes_v2.2_annot.embl.gz

**Comment by adevine4** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22370 genome upload

**Comment by MattHuff** [comment]
@bradfordcondon 

We are confused about matching the protein data to the genome; specifically, the fasta headers in the genome file `/data/www/html/undergrads/sites/default/files/sequences/quercus_robur/Qrob_PM1N.fa` do not match the headers in the proteins file `/data/www/html/undergrads/sites/default/files/sequences/quercus_robur/Qrob_PM1N_CDS_aa_20161004.fa`. Any tips on how to proceed, including any regular expressions you feel would help match the data?

**Comment by bradfordcondon** [comment]
hi @MattHuff ill take a look - what server, dev?

**Comment by MattHuff** [comment]
Yes, on `160.36.205.61`

**Comment by almasaeed2010** [comment]
```shell
# head /data/www/html/undergrads/sites/default/files/sequences/quercus_robur/Qrob_PM1N.fa
>Qrob_Chr01
TCTGAAGTATAGGGTTTAAAATGTAATTTGATCTAAGATTTATTGACATCTGTTGCCTAT
TTATTTCCCAATATGACAGACCACTTTTCTTTAGTCCTACTGTTTTCTTTTTTCTTTTTT
TTTTTAACATAATAAGACATTATTGTTTTGTTAAGAACTTTATAACTCAATTGTGTGTGA
AAAAATAAAATTGCATTGTCTAATCTTATTTGGGAGAACCAGAATTTGAAATCCCCATAC
ACCACTTTTTAGTAACAACTGAATTTAAAAAATAAAAACGCACTGTTGTTTTTATAGTAC
AACACATTGTATTTCTTATTGAAAAGCAGGGGGACTATATTCTGATCACTTTTTCCTACT
CCTATTCTATGTTCTCATCAATTCCCCATCCAAACATAAGGCTATGTACATAAAAAATGA
TAATTTATCCATTGGTAGAACGGTTTTATTTGGGAATGCCTTCTGGTTTTTCTTTCATAC
AGCAACTTTTGAATTTAATTAGAACCCCACTATCAGTTGCCATCTTTTGAAGTTTCATGT
```

### Protein
```shell
# head /data/www/html/undergrads/sites/default/files/sequences/quercus_robur/Qrob_PM1N_CDS_aa_20161004.fa
>Qrob_P0000010.2 230
MSGPENWLQFYQQQNLSTSQMSDSTIVTTTVTSNSPIGSGNSSANTGHLSPEGRVSKPIR
RRSRASRRTPTTLLNTDTTNFRAMVQQFTGGPSAPFASGAHHGAPPNFGFALGTNRQAHH
HHPAMMLPPTGHGFHLQPQQQLLYPHHHHHQQGQQQYMFSLGNNSSHSTHHGQDHALLQR
LGSSRPSSNMGSVVSDGFVIEGVGVPSSSQVPPASTVRPSNENRSNSFLF*
>Qrob_P0000020.2 395
MQKMNLHSICISLSFLFAIFAVLPSTHIINSNPSFLEYLINFSLTFFSSSPITSTVITYN
IEGHHKHHKKNKTINPCEDFSPDFPTDSDTTSYICVDRNGCCNFTTVQAAVNAIPDFSQN
RTIIWINTGIYYEKVTVPSPKTNVTFQGQGFTSTAIAWNDTANSSHGTSFSGSVQVFSTN
FIAKNISFMNLAPIPNPGDIGAQAVAIKISGDKAAFWGCGFFGAQDTLHDDKGRHYFRDC
```

**Comment by bradfordcondon** [comment]
hi @MattHuff you are missing the gene call information.  Is there a seperate mRNA or CDS FASTA file?  That's what we usually load.  We also don't load the actual scaffolds ie `Qrob_PM1N.fa`

**Comment by almasaeed2010** [comment]
```shell
# head Qrob_PM1N_CDS_nt_20161004.fa 
>Qrob_P0000010.2 693
ATGTCTGGCCCTGAAAACTGGCTCCAATTCTATCAACAACAAAACCTCTCTACTTCTCAG
ATGTCTGATTCCACAATTGTAACCACCACTGTCACTTCCAATAGTCCAATTGGGTCCGGC
AATTCTAGCGCAAACACTGGTCACTTGAGCCCAGAAGGCCGTGTATCCAAGCCAATACGT
AGGAGATCCAGGGCTTCTAGACGAACCCCAACAACTTTACTCAACACAGACACTACAAAT
TTCAGAGCCATGGTGCAACAATTCACTGGAGGTCCTAGTGCACCCTTTGCCTCAGGAGCT
CACCATGGTGCACCACCAAACTTTGGTTTTGCATTAGGAACCAACCGTCAAGCTCATCAT
CATCATCCAGCAATGATGTTACCTCCTACAGGTCATGGATTTCATTTACAGCCTCAACAA
CAGTTACTATACCCTCATCATCATCATCATCAGCAAGGCCAGCAGCAATACATGTTTTCT
CTAGGAAACAATAGTAGTCATAGTACACATCATGGTCAAGATCATGCTCTTCTTCAAAGA
```

**Comment by MattHuff** [comment]
Yes, it's saved as `Qrob_PM1N_CDS_nt_20161004.fa `.

```
head Qrob_PM1N_CDS_nt_20161004.fa 
>Qrob_P0000010.2 693
ATGTCTGGCCCTGAAAACTGGCTCCAATTCTATCAACAACAAAACCTCTCTACTTCTCAG
ATGTCTGATTCCACAATTGTAACCACCACTGTCACTTCCAATAGTCCAATTGGGTCCGGC
AATTCTAGCGCAAACACTGGTCACTTGAGCCCAGAAGGCCGTGTATCCAAGCCAATACGT
AGGAGATCCAGGGCTTCTAGACGAACCCCAACAACTTTACTCAACACAGACACTACAAAT
TTCAGAGCCATGGTGCAACAATTCACTGGAGGTCCTAGTGCACCCTTTGCCTCAGGAGCT
CACCATGGTGCACCACCAAACTTTGGTTTTGCATTAGGAACCAACCGTCAAGCTCATCAT
CATCATCCAGCAATGATGTTACCTCCTACAGGTCATGGATTTCATTTACAGCCTCAACAA
CAGTTACTATACCCTCATCATCATCATCATCAGCAAGGCCAGCAGCAATACATGTTTTCT
CTAGGAAACAATAGTAGTCATAGTACACATCATGGTCAAGATCATGCTCTTCTTCAAAGA
```

**Comment by adevine4** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/24345 polypeptide upload

**Comment by adevine4** [comment]
http://160.36.205.61:9090/bio_data/416 analysis description

**Comment by almasaeed2010** [comment]
Path to CDS:

`/home/www/sites/default/files/sequences/quercus_robur/Qrob_PM1N_CDS_nt_20161004.fa`


Path to Proteins: 

`/home/www/sites/default/files/sequences/quercus_robur/Qrob_PM1N_CDS_aa_20161004.fa`

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/672170 gene upload

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/organism/Quercus/robur organism page

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/674887 polypeptide upload

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/674881 gene record publish

**Comment by adevine4** [comment]
`ps aux | grep  13600` if command prints 1 line, then we're done for blast

**Comment by adevine4** [comment]
swissprot code
```
#PBS -N swissprot_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=02:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/oak/BLAST_splits/Qrob_PM1N_CDS_nt_20161004.fa.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/oak/blast/swissprot/swissprot_Qrob.$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/700516 load genes fasta 
need to:
- publish genes
- load polypeptides
- load blast
- run interpro
- load interpro

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/organism/Quercus/robur organism 

https://hardwoods.ag.utk.edu/Genome-assembly/2209455 reference genome

**Comment by adevine4** [comment]
IPS code
```
#PBS -N oak_ips      
#PBS -A ACF-UTK0011
#PBS -S /bin/bash
#PBS -t 1-200
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=3:30:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/interproscan-5.28-67.0/interproscan.sh \
 -i /lustre/haven/gamma/staton/projects/undergrads/oak/IPS_splits/Qrob_PM1N_CDS_aa_20161004.fa.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/gamma/staton/projects/undergrads/oak/IPS/xmls \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/gamma/staton/projects/undergrads/oak/IPS/TMP \
 >& /lustre/haven/gamma/staton/projects/undergrads/oak/IPS/TMP/$PBS_ARRAYID.out
```

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/BLAST-annotation/2360513 new BLAST analysis

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/710702 import blast file

**Comment by adevine4** [comment]
to test how effective diamond is compared to blast I used this code on the swissprot data set
```
#PBS -N swissprot_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=00:10:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/diamond blastx \
 -q /lustre/haven/gamma/staton/projects/undergrads/oak/BLAST_splits/Qrob_PM1N_CDS_nt_20161004.fa.$PBS$
 -d /lustre/haven/gamma/staton/library/uniprot/diamond_db/uniprot_sprot.dmnd \
 -o /lustre/haven/gamma/staton/projects/undergrads/oak/blast/swissprot/diamond_swissprot_Qrob.$PBS_AR$
 --evalue 1e-5 \
 --outfmt 5

```

**Comment by adevine4** [comment]
new swissprot blast file https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/712993

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/714549 Swissprot blast file
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/714554 trembl blast file

**Comment by adevine4** [comment]
1st IPS output failed because it was missing a FASTA header other jobs appear to be unaffected

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/730792 swissprot blast file

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/BLAST-annotation/2445489 trembl blast annotation

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/730798 trembl blast file

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/InterProScan-annotation/2445490 IPS annotation

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/Publication/2555665?tripal_pane=group_summary_tripalpane publication

**Comment by adevine4** [comment]
**Common name**: Olive
**Order**: Lamiales
**Family**: Oleaceae
Found in Mediterranean areas, is a main source of olive oil.

**Sources**: [USDA publication] (https://plants.usda.gov/core/profile?symbol=OLEU)
description

**Comment by adevine4** [comment]
-moving splits from acf to server, still need to do the blastkoala

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/Genome-assembly/2365975 reference genome
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/476175 fasta loader

**Comment by adevine4** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/475329 fasta
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/475333 blast trembl
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/475334 blast swissprot 
https://hardwoods.ag.utk.edu/InterProScan-annotation/2585294 ips annotation

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/480505 CDS fasta loader
https://hardwoodgenomics.org/organism/Quercus/robur?tripal_pane=group_analyses IPS and BLAST annotations

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/480510 CDS fasta loader 
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/480511 swissprot blast file

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/480516 publish mrna polypeptide

**Comment by adevine4** [comment]
trembl splits 201-400 
```
#PBS -N trembl_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 201-400
#PBS -l nodes=1:ppn=2
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/oak/trembl_splits/trembl2/Qrob_PM1N_CDS_aa_20161004.fa.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/oak/trembl_splits/trembl2/xml/$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```


1-200
```
#PBS -N trembl_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/oak/trembl_splits/trembl1/Qrob_PM1N_CDS_aa_20161004.fa.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/oak/trembl_splits/trembl1/xml/$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by adevine4** [comment]
-ran trembl1, appears to have completed. trembl2 completed.
-1st file in trembl1 empty, all others are fine 
`/lustre/haven/gamma/staton/projects/undergrads/oak/trembl_splits/trembl1/xml`

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/519108 swissprot fasta loader
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/519112 IPS fasta loader
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/519183 publish mRNA

**Comment by almasaeed2010** [comment]
@adevine4 IPS and swissprot don’t use the fasts loader. IPS uses InterProScan loader and swissprot/trembl use the BLAST loader.

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/525051 swissprot blast file

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/525218 trembl blast file

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/533810 fasta file
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/533866 ips file 
https://hardwoodgenomics.org/KEGGresults/2539071 kegg annotation

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/Publication/2539072 publication

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/content/quercus-robur-transcripts blast database (nt)
https://hardwoodgenomics.org/content/quercus-robur-peptides blast database (pep)

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/content/quercus-robur-scaffolds blast database (scaffolds)

**Comment by mestato** [comment]
On live site, there are no downloads or description for reference genome analysis (https://www.hardwoodgenomics.org/Genome-assembly/2365975?tripal_pane=group_details)

Also, the record on dev doesn't appear to be working (https://hardwoods.ag.utk.edu/Genome-assembly/2209455 reference genome)

**Comment by mestato** [comment]
It looks like there are a number of versions available for this genome: V1, V2 and PM1N (http://www.oakgenome.fr/?page_id=587). We need to check that we are loading version PM1N and make sure this is clear on the analysis page. It would be good for version 1  and 2 to be available for download only.

**Comment by MattHuff** [comment]
@mestato, where did you get the link for the record on dev? Abdullah and I aren't sure where this error is occuring.

@adevine4, can you verify which version of the Oak genome you used?

**Comment by mestato** [comment]
I got the link from this issue, see above Amanda, Oct 17th

**Comment by MattHuff** [comment]
Try https://hardwoods.ag.utk.edu/Genome-assembly/2335725 for the record on the dev site. When I go to the organism and click on the reference genome, that's what works for me.

**Comment by mestato** [comment]
Yep, that works for me. And looks like the live site page. Still needs downloads or description for reference genome analysis and publication. A good example to look at is the kiwi genome analysis: https://www.hardwoodgenomics.org/Genome-assembly/2243625?tripal_pane=group_summary_tripalpane

**Comment by adevine4** [comment]
downloads https://hardwoodgenomics.org/Genome-assembly/2365975

**Comment by mestato** [comment]
A few additional todos:
- [ ] link the publication to the analysis
- [ ] KEGG Xray (the expandable/collapsible tree) doesn't seem to be populated
- [ ] add jbrowse

And for @almasaeed2010:
- at the gene level (ie https://www.hardwoodgenomics.org/feature/Qrob_P0542810.2?tripal_pane=gp_schema__publication49321), can we not show panes with no reuslts? cross references, location on map, publication, synonyms
- could we inherit the publication from the analysis to fill that in?
- could we start adding dbxrefs to NCBI?
- I don't think IPRs are being parsed correctly? I think there should always be an IPR Term

<img width="865" alt="screen shot 2019-03-06 at 1 29 28 pm" src="https://user-images.githubusercontent.com/508122/53904383-ed38f500-4013-11e9-8a99-eb629a84fac6.png">

**Comment by mestato** [comment]
Specifically related to missing IPR term and description - see #438. So not a problem with Q robur only

**Comment by almasaeed2010** [comment]
>at the gene level (ie https://www.hardwoodgenomics.org/feature/Qrob_P0542810.2?tripal_pane=gp_schema__publication49321), can we not show panes with no reuslts? cross references, location on map, publication, synonyms

Done

> could we inherit the publication from the analysis to fill that in?

Issue submitted for a new feature request on https://github.com/tripal/tripal/issues/876

> could we start adding dbxrefs to NCBI?

This should already be doable, we just gotta teach the undergrads how to do it. I believe we already do it to publications?

@cricha59 please talk to me about this so that we test it and add it to the wiki

> I don't think IPRs are being parsed correctly? I think there should always be an IPR Term

Not sure if this is fully related but take a look at this: https://github.com/statonlab/hardwoods_site/issues/438

**Comment by almasaeed2010** [comment]
@mestato could you please elaborate on the dbxref thing. We add cross reference records in the analysis but where else should they be added?

**Comment by mestato** [comment]
Yep. This may not be the greatest first use case, as the Oak data is housed in another community db. But for example, the gene Qrob_P0032420.2 has a lot of external information here: https://urgi.versailles.inra.fr/OakMine_PM1N/portal.do?externalids=Qrob_P0032420.2

A dbxref would be awesome. If we get data out of NCBI the link to genes should be more standardized and easier to consistently implement.

**Comment by almasaeed2010** [comment]
Created a temporary module for displaying publications on feature pages until the Tripal PMC votes on how to deal with it: https://github.com/statonlab/tripal_feature_pub

This module is deployed live. See this page for an example: https://www.hardwoodgenomics.org/feature/Qrob_P0729230.2?tripal_pane=gp_schema__publication49321

**Comment by adevine4** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/745519 kegg

**Comment by mestato** [comment]
still need a jbrowse for PM1N

**Comment by patricksis** [comment]
Jbrowse:
https://www.hardwoodgenomics.org/admin/tripal/extension/tripal_jbrowse/management/instances/12

gff track is not showing up.

**Comment by patricksis** [comment]
This organism has 2 KEGG analysis associated with it. In addition, IPS results aren't showing up and trembl shows up for a few, but not most. 

@almasaeed2010 could you add this to your list of things to do for KEGG. I am looking into the IPS. https://www.hardwoodgenomics.org/organism/Quercus/robur?tripal_pane=group_analyses

Most likely keep the KEGG from March and delete the one from December

**Comment by CaseyRichards92** [comment]
@mestato Could you look at the organism description and let me know if this is what you want? Amanda put a lot of links, which isnt what we have been putting for this part of the description but I dont want to delete anything if she was told to put those there.
https://www.hardwoodgenomics.org/organism/Quercus/robur?tripal_pane=group_summary_tripalpane

**Comment by CaseyRichards92** [comment]
### Live Site ###
Description added to reference genome https://www.hardwoodgenomics.org/Genome-assembly/2365975
New KEGG Annotation https://www.hardwoodgenomics.org/KEGGresults/3500182
New KEGG job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/800723

**Comment by CaseyRichards92** [comment]
Jbrowse Link created https://www.hardwoodgenomics.org/organism/Quercus/robur?tripal_pane=group_jbrowse

**Comment by CaseyRichards92** [comment]
@almasaeed2010 Still no gff track https://www.hardwoodgenomics.org/tools/jbrowse/?data=data%2Fquercus_robur__pedunculate_oak%2Fdata&tracks=&loc=qrob_v2_scaffold_0018%3A779501..1352500&highlight=

I used ```Qrob_PM1N_CDS_nt_20161004.fa``` for the instance and ```Qrob_PM1N_genes_20161004.gff``` for the track

**Comment by CaseyRichards92** [comment]
gff works https://hardwoodgenomics.org/tools/jbrowse/?data=data%2Fquercus_robur__pedunculate_oak%2Fdata&tracks=pendulate_oak&loc=Qrob_H2.3_Sc0000885%3A1..143359&highlight=

Used ```Qrob_PM1N.fa``` for the instance instead

**Comment by CaseyRichards92** [comment]
@RaymondS1 @patricksis Quercus robur is ready for inspection
