### ISSUE TITLE
Creating a new DB server separate from the apache server

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#305]
Currently we are having issues with server resources. The site is being slow and unresponsive for long periods of time. 

### Solution
I suggested separating the DB server from the main server since the DB processes are taking up most of the cores which is making it hard for other services such as apache and elasticsearch to utilize their share of the server.

This adds a cost of $45/month to our monthly bill (total of ~$175 after adding the new server and enabling backups)

### Alternative Solution
Since this adds a new complexity to our server setup and requires developers to maintain 2 separate servers, it may be easier to simply upgrade the current server to have more resources.

This would add $96 per month (total of ~$226/month with backups enabled).

### Pros and Cons
- Upgrading the server means resources are still shared between processes and the DB could end up overloading the server and slowing down apache and ES.
- Upgrading the current server is more expensive
- Separate server means maintaining 2 live servers

**Comment by mestato** [comment]
Lets go with separate instances. I think it makes more sense if the database needs dedicated resources.

**Comment by almasaeed2010** [comment]
Sounds good. I'll start the process today.

**Comment by bradfordcondon** [comment]
This is stephen's recommendation and im hopeful it will do a lot for site speed.

**Comment by almasaeed2010** [comment]
This doesn't seem to have helped the issue at all. From the list of queries running during bootstrapping Drupal (after clearing the cache), it looks like entities are being loaded when they are not supposed to. A lot of repeating queries and so many connections that we have no clue where they are coming from.

**Comment by almasaeed2010** [comment]
The separate DB has caused more issues than it resolved. We have a problem in our httpd -> postgres connections where httpd is not closing the connection immedietly after the visitor leaves the site. We need find out how to fix that and we should be back in the clear.

**Comment by almasaeed2010** [comment]
Also not that the separate DB instance has been "destroyed"
