### ISSUE TITLE
consolidate jbrowse modules?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#309]
### Feature description
we have two seperate modules for our jbrowse linkouts: one for features and one for the organism link itself.  Is there a reason not to consolidate to make maintenance easier?
### Link to relevant info
https://github.com/statonlab/tripal_jbrowse_instance
https://github.com/statonlab/tripal_feature_jbrowse

**Comment by almasaeed2010** [comment]
the tripal_feature_jbrowse is old and should be disabled. Let's verify that it is in fact disabled and uninstalled then remove.

**Comment by bradfordcondon** [comment]
hmmm ok.  remove from github or simply label is deprecated?

**Comment by almasaeed2010** [comment]
<img width="1089" alt="screen shot 2018-06-21 at 3 57 32 pm" src="https://user-images.githubusercontent.com/1512664/41742422-e1493e12-756b-11e8-9e5b-07f5af1020c1.png">

tripal jbrowse feature is disabled so I am gonna uninstall and remove from the setup. We can safely delete the repo too.

**Comment by almasaeed2010** [comment]
Removed from live and dev and the repo has been renamed to have DEPRECATED in the title.
