### ISSUE TITLE
Biosample page cross references missing

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#31]
For the cross references - the SRA links are there, Biosample links are missing for all materials (that I checked).

**Comment by bradfordcondon** [comment]
For broken SRA links:
correct link:
https://www.ncbi.nlm.nih.gov/sra/SRS830175
broken link:
https://www.ncbi.nlm.nih.gov/sra/NCBI%20SRA:SRS830175

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal_analysis_expression/pull/153

>Instead of inserting the accession into biomaterial we associate it like we do the other db's in biomaterial_dbxref.
>Note that we need to do something for already loaded bio samples.

The below snippet will update already loaded bio-samples.

```

  $sql = "SELECT * FROM {biomaterial}";
  $results = chado_query($sql);

  foreach($results as $result) {

    if ($result->dbxref_id) {

      $sql = "SELECT db.name FROM {dbxref} DBX
        INNER JOIN {db} DB ON  DBX.db_id = db.db_id
        WHERE DBX.dbxref_id = :dbxref_id";

      $db = chado_query($sql, [":dbxref_id" => $result->dbxref_id])->fetchObject();
      if ($db == "NCBI BioSample") {

        $biomaterial_id = $result->biomaterial_id;
        $ncbi_id = $result->dbxref_id;

        tripal_associate_dbxref('biomaterial', $biomaterial_id, [
          'accession' => $ncbi_id,
          'db_name' => 'NCBI BioSample'
        ]);

      }
    }
  }
```

**Comment by bradfordcondon** [comment]
Resolved with https://github.com/tripal/tripal_analysis_expression/pull/158

However: 

* DBs need to be corrected to properly format URLs
* Need to rollback DB to remove erroneous dbxref's (the dbxref_id, instead of the accession, got inserted for the new dbxrefs...)

**Comment by bradfordcondon** [comment]
Fixing the DB links:

* Go to `admin/tripal/loaders/chado_db/` and search for the appropriate DB
 - NCBI BioSample
 - NCBI SRA
*  Click Edit, and scroll to the Prefix section.
* Update the prefix to use the `{db}` and `{accession}` tokens as described below.
* BioSample and SRA are updated as follows:
  - http://www.ncbi.nlm.nih.gov/biosample/{accession}
  - http://www.ncbi.nlm.nih.gov/sra/{accession}


>Tripal can provide links to external databases when accession numbers or unique identifiers are known. Typically, a database will provide a unique web address for each accession and the accession usually is the last component of the page address. Please enter the web address, minus the accession number for this database. By default, Tripal will combine this "URL prefix" with the database short name and accession to create a link to the external site. But, you can also use the tokens {db} and {accession} within the URL prefix to specify exactly where the database short name and the accession should be added. Tripal will substitute the actual values in place of these tokens to create the link. (e.g. URL prefix: https://phytozome.jgi.doe.gov/phytomine/portal.do?externalid=PAC:{accession}).

**Comment by bradfordcondon** [comment]
http://160.36.205.61:8095/bio_data/2038423  resolved
