### ISSUE TITLE
jbrowse instance needs a readme

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#310]
https://github.com/statonlab/tripal_jbrowse_instance

- [x] add supporting info (readme, license, doi)

- [x] add to tripal showcase

**Comment by bradfordcondon** [comment]
also, does this module merit sharing on showcase?

**Comment by almasaeed2010** [comment]
README, Zenodo, License and release added. We can add to showcase if you'd like 👍

**Comment by mestato** [comment]
I vote to add to showcase, its a pretty common need I would think.

**Comment by bradfordcondon** [comment]
nice! @almasaeed2010 do you want to try adding it to see how it works?  or want me to?

**Comment by almasaeed2010** [comment]
Sorry didn't see this comment! I can add sure :)
