### ISSUE TITLE
GreenAsh to Live

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#311]
Publish Green Ash JBrowse but do not add it to the website (keep it hidden).

**Comment by almasaeed2010** [comment]
All tracks now work except for the BW track. Re-syncing to fix.

**Comment by almasaeed2010** [comment]
Ok proxy fixed and all is ready.

**Comment by mestato** [comment]
Could you post link? https://hardwoodgenomics.org/tools/jbrowse/index.html?data=green_ash doesn't work for me.
