### ISSUE TITLE
jbrowse unreachable on dev

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#314]
### Location
https://hardwoods.ag.utk.edu/tools/jbrowse/index.html?data=english_walnut
### Additional info

```
RequestError: Unable to load https://hardwoods.ag.utk.edu/tools/jbrowse/english_walnut/tracks.conf status: 403.
```

**Comment by almasaeed2010** [comment]
So I tried all overrides to disable http basic auth for jbrowse and even removed it completely but we still don't have access to it. Not sure why since the config is exactly the same as live.

**Comment by almasaeed2010** [comment]
Fixed. For some reason, this server needed additional apache config:
```
<Directory /data/apollo>
    Options Indexes FollowSymLinks MultiViews
    Require all granted
</Directory>
```
