### ISSUE TITLE
Biosample page error

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#32]
Found on  [page](http://160.36.205.61:8095/bio_data/334). Appears in red box at top even when not logged in. 

```Notice: Trying to get property of non-object in local__contact->load() (line 132 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal/tripal_chado/includes/TripalFields/local__contact/local__contact.inc).```

**Comment by almasaeed2010** [comment]
Task: report on Tripal core since this field is coming from tripal_contact module

**Comment by bradfordcondon** [comment]
pretty sure my PR here resolves this https://github.com/tripal/tripal/pull/219

**Comment by bradfordcondon** [comment]
This is resolved.

Semi related new issue: we dont fill out the contact table so we have blank columns #81
