### ISSUE TITLE
what to do with SSRs that arent linked to features or are just publications

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#320]
### Feature description

We loaded in all SSRs that we were able to: generally just the predicted SSRs.

For many organism SSR sets, we only have access to files which dont help us.  For example, those in the `gssr` folder:

```
 cd gSSRs/
[bcondon@hardwoodgenomics gSSRs]$ ls
black_cherry_extendedFrags.fastq  blackgum_hqSSR_seqs.fasta               CarlsonLab_Sweetgum_TestedSSRs.xlsx  green_ash_hqSSR_seqs.fasta    redbay_gssrs_v4.xlsx             sweetgum_extendedFrags.fastq   white_ash_hqSSR_seqs.fasta
black_cherry_gssrs_v4.xlsx        black_walnut_extendedFrags.fastq        CarlsonLab_WhiteOak_TestedSSRs.xlsx  gssrs_chart.jpg               redbay_hqSSR_seqs.fasta          sweetgum_gssrs_v4.xlsx         white_oak_extendedFrags.fastq
black_cherry_hqSSR_seqs.fasta     black_walnut_gssrs_v4.xlsx              copy.sh                              gssrs_chart.png               sugar_maple_extendedFrags.fastq  sweetgum_hqSSR_seqs.fasta      white_oak_gssrs_v4.xlsx
blackgum_extendedFrags.fastq      black_walnut_hqSSR_seqs.fasta           green_ash_extendedFrags.fastq        honeylocust_gssrs_v4.xlsx     sugar_maple_gssrs_v4.xlsx        white_ash_extendedFrags.fastq  white_oak_hqSSR_seqs.fasta
blackgum_gssrs_v4.xlsx            CarlsonLab_BlackCherry_TestedSSRs.xlsx  green_ash_gssrs_v4.xlsx              honeylocust_hqSSR_seqs.fasta  sugar_maple_hqSSR_seqs.fasta     white_ash_gssrs_v4.xlsx
[bcondon@hardwoodgenomics gSSRs]$ pwd
/var/www/html/sites/default/files/gSSRs
```

For others, we have no files, and just link to a publication.  

For now I'm thinking we leave all these as is.  Maybe we can convert the files into something that relates to the organisms features and we can load them in.  Maybe we want to convert the pubs into chado pubs.  

### Link to relevant info

coming soon.

Previous mega SSr issue: #35

**Comment by mestato** [comment]
Those will be analyses only, since there aren't parent features.

**Comment by bradfordcondon** [comment]
Some of these SSRs we dont link to the data, we just have it as a publication. We could opt not to create an analysis, and just create the pub and attach it to the organism.  K

* https://www.hardwoodgenomics.org/organism/Acer/saccharum?tripal_pane=group_polymorphic_ssrs

* https://www.hardwoodgenomics.org/organism/Gleditsia/triacanthos?tripal_pane=group_polymorphic_ssrs
* https://www.hardwoodgenomics.org/organism/Fraxinus/pennsylvanica?tripal_pane=group_polymorphic_ssrs
* https://www.hardwoodgenomics.org/organism/Fraxinus/americana?tripal_pane=group_polymorphic_ssrs
* https://www.hardwoodgenomics.org/organism/Prunus/serotina?tripal_pane=group_confirmed_polymorphic_ssrs
* https://www.hardwoodgenomics.org/organism/Persea/borbonia  (note: no field, its just in the organism description)
* https://www.hardwoodgenomics.org/organism/Liriodendron/tulipifera?tripal_pane=group_polymorphic_ssrs
* https://www.hardwoodgenomics.org/organism/Liquidambar/styraciflua?tripal_pane=group_confirmed_polymorphic_ssrs
* https://www.hardwoodgenomics.org/organism/Quercus/rubra?tripal_pane=group_polymorphic_ssrs
* https://www.hardwoodgenomics.org/organism/Quercus/alba?tripal_pane=group_confirmed_polymorphic_ssrs

**Comment by bradfordcondon** [comment]
I'm going to take a break and afterwards we can disable the drupal fields that previously housed this information.

If we want a "confirmed SSR" pane we can do that by converting these analyses into a custom analysis type.
