### ISSUE TITLE
Iron Walnut Transcriptome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#324]
https://link.springer.com/article/10.1007/s11295-018-1263-z

We haven't been hosting chloroplasts from any species, so lets just focus on trying to capture the transcriptome. Also, like J. nigra, we can put a track on the J. regia JBrowse that shows mappings from this transcriptome to the J. regia genome. (Jiali has notes on how to do this on the github wiki using GMap)

**Comment by almasaeed2010** [comment]
Looks like raw data for this one: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA393481

**Comment by cricha59** [comment]
Organism link
http://160.36.205.61:9090/bio_data/206

**Comment by cricha59** [comment]
Analysis link
http://160.36.205.61:9090/bio_data/207

**Comment by cricha59** [comment]
mRNA FASTA file
/data/www/html/undergrads/sites/default/files/sequences/ironWalnut/iron-walnut.fasta

**Comment by cricha59** [comment]
- [ ] FASTA mRNA job http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22017

**Comment by cricha59** [comment]
- [ ] FASTA mRNA job updated http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22094

**Comment by almasaeed2010** [comment]
I had to rerun the job because the server was somehow filled up and the job got terminated. Here is the link to the new mRNA job:
- [ ] [FASTA Import Job](http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22366)

**Comment by cricha59** [comment]
Contact author for full analysis.
pengzhao@nwu.edu.cn

**Comment by mestato** [comment]
We're going to load the genome instead.
