### ISSUE TITLE
Interproscan module not utilized

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#326]
### Feature description
The interproscan module has a field that displays the results.  Right now we only have interproscan results in the annotations https://www.hardwoodgenomics.org/bio_data/264446

but theres a field which should visualize.

I've checked and we have the necessary chado stuff for it to work.
```
select  cvtt.name from chado.analysisfeatureprop afp INNER JOIN chado.cvterm cvt ON afp.type_id = cvt.cvterm_id
INNER JOIN chado.analysisfeature af ON af.analysisfeature_id = afp.analysisfeature_id INNER JOIN chado.feature f ON af.feature_id = f.feature_id INNER JOIN chado.cvterm cvtt ON cvtt.cvterm_id = f.type_id where  cvt.name = 'analysis_interpro_xmloutput_hit';
```

shows mRNA, not proteins.

I think that the field has a problem...

**Comment by almasaeed2010** [comment]
That field is enabled in mRNA Contig - Polypeptide but not in mRNA - polypeptide.

<img width="1364" alt="screen shot 2018-07-25 at 1 08 40 pm" src="https://user-images.githubusercontent.com/1512664/43216109-024009ec-900c-11e8-8a59-3e16f362afb7.png">


It also won't even show up as a field in mRNA - polypeptide.

**Comment by almasaeed2010** [comment]
If the field was functioning properly, it would've showed up on this page: https://www.hardwoodgenomics.org/feature/Cornusflorida12062016isotig23888

Since that page has interpro annotations and is mRNA Contig, it should show up but it isn't currently.

**Comment by bradfordcondon** [comment]
> mRNA - polypeptide.

i removed and attempted to re-add.  this broke the field because it is missing the vocab fiedl instance setting ( a new requirement since the field was made)

stephen is aware.

**Comment by bradfordcondon** [comment]
>It also won't even show up as a field in mRNA - polypeptide.


If I recall, this is from the module being coded to attach to features **named** mRNA (ie searching  by the label, instead of by the term).  Let me check that...

**Comment by bradfordcondon** [comment]
So the formatter is running, which makes it much easier to debug (no clearing cache involved).

![screen shot 2018-09-11 at 10 55 48 am](https://user-images.githubusercontent.com/7063154/45368296-44a06000-b5b1-11e8-85f4-2c73e03c2926.png)

So the first item is null which could be the problem.  Second item in the array looks about right.

**Comment by bradfordcondon** [comment]
given the above, I  actually wonder if the issue is our theme?  Is that possible?

**Comment by bradfordcondon** [comment]
confirmed its our theme.  setting the htem to bartik and the pane and data shows up:

![screen shot 2018-09-11 at 2 08 34 pm](https://user-images.githubusercontent.com/7063154/45378741-4af00580-b5cc-11e8-87e0-abe30692e22a.png)

**Comment by almasaeed2010** [comment]
I don't understand why the field simply disappears using our theme. I'll try removing the JS code to see if it causes the issue. 

Note that I am not experiencing the weird chart issue with Bartik.

**Comment by almasaeed2010** [comment]
This puzzles me. I removed all the JS from our theme (with clearing cache) and the pane still won't show up! There is no other part of our theme that removes fields/panes.

**Comment by almasaeed2010** [comment]
I switched all of our `tripal_analysis_*` repos to our forks and activated the fields. Everything is working as expected on both content types `Gene` and `mRNA- polypeptide`

https://hardwoodgenomics.org/feature/FRAEX38873v20001857401?tripal_pane=group_interpro

![download](https://user-images.githubusercontent.com/1512664/45510989-ca670b80-b769-11e8-9bd6-58d2951a945d.png)

**Comment by bradfordcondon** [comment]
so something that we're going to notice is our plots are wrong.  The coordinates correspond to the proteins.  However, the map corresponds to the mRNA.  That's why the linked image goes from 1-200 only instead of 600.

I might be wrong in this assertion: easy to see, if im right we will *never have domains mapped past the first third of the mRNA*.

To fix we would have to do something with the importer to note that the coordinates were generated with a protein not mRNA  and then probably also modify the plot.
