### ISSUE TITLE
stout camphor tree reference genome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#328]
Paper:
https://www.biorxiv.org/content/early/2018/07/18/371112

This is a bioarxiv paper, so we need to update to the real version if/when it is published by a peer reviewed journal.

**Comment by CaseyRichards92** [comment]
@mestato Reading through the link you provided and the recent "tweets" that the page has it appears that they published the paper. Is this the right paper?

https://www.nature.com/articles/s41477-018-0337-0.epdf?shared_access_token=Mr-8Yk_zHjrEvZi2Zp0Fw9RgN0jAjWel9jnR3ZoTv0NBt_Tx9pzgo_4MvWXl4utxKdTbVtTE-bcXBVwgh794uCrX42QnyxpqeDE9bcSzyA6yOixMRAEUhEwXa6bTHu1vm_kdkbfbeZZwpIrIUHRKfSJO5oPciSuN8bAPL5t5pDY%3D

Also, the accession # from this paper leads to a different organism. Are these the same organism? if so, can I go ahead and start since it has a protein and genome file?
NCBI: https://www.ncbi.nlm.nih.gov/genome/57158

**Comment by mestato** [comment]
Yes, the nature paper looks correct. Good find. For the differing species names, I found this page: http://tropical.theferns.info/viewtropical.php?id=Cinnamomum+micranthum which says the C. kanehirae is now viewed as a form of Cinnamomum micranthum. Since the paper is linked on NCBI, I think you are good to use that data for loading.

**Comment by CaseyRichards92** [comment]
### Cinnamomum micranthum AG site ###
Organism created: https://hardwoods.ag.utk.edu/organism/Cinnamomum/micranthum
Publication created: https://hardwoods.ag.utk.edu/Publication/2892971
Reference Genome: https://hardwoods.ag.utk.edu/Genome-assembly/2892972?tripal_pane=group_downloads
IPS Annotation https://hardwoods.ag.utk.edu/InterProScan-annotation/2892973
SwissProt Annotation https://hardwoods.ag.utk.edu/BLAST-annotation/2892974
TrEMBL Annotation https://hardwoods.ag.utk.edu/BLAST-annotation/2892975
KEGG Annotation https://hardwoods.ag.utk.edu/KEGGresults/2892976
CDS loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/517081
Protein loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/517085
Published mRNA polypeptide https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/517087
KEGG Loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/534647
IPS Loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/534652
Trembl loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/534653
Swissprot Loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs
JBrowse w/ track https://hardwoods.ag.utk.edu/admin/tripal/extension/tripal_jbrowse/management/instances/11

**Comment by CaseyRichards92** [comment]
SwissProt
```
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/stout_camphor/splits_cds/GCA_003546025.1_ASBRC_Ckan_1.0_cds_from_genomic.fna.fixed.filtered.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/stout_camphor/blast/swissprot/stout_camphor_swissprot_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5

```

**Comment by CaseyRichards92** [comment]
TrEMBLE
```
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=15:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/stout_camphor/splits_cds/GCA_003546025.1_ASBRC_Ckan_1.0_cds_from_genomic.fna.fixed.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/stout_camphor/blast/trembl/stout_camphor_trembl_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
IPS
```
#PBS -A ACF-UTK0011
#PBS -S /bin/bash
#PBS -t 1-200
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=3:30:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/interproscan-5.28-67.0/interproscan.sh \
 -i /lustre/haven/gamma/staton/projects/undergrads/stout_camphor/splits_peptides/GCA_003546025.1_ASBRC_Ckan_1.0_protein.faa.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/gamma/staton/projects/undergrads/stout_camphor/blast/ips \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/gamma/staton/projects/undergrads/stout_camphor/blast/ips/tmp \
 > /lustre/haven/gamma/staton/projects/undergrads/stout_camphor/blast/ips/tmp/$PBS_ARRAYID.out
```

**Comment by CaseyRichards92** [comment]
@almasaeed2010 I received this error multiple times when trying to upload the Blast db

![image](https://user-images.githubusercontent.com/43444146/53524218-d68f1d00-3aac-11e9-93e5-5ee0997303eb.png)

**Comment by CaseyRichards92** [comment]
## Live site ##
Organism https://www.hardwoodgenomics.org/organism/Cinnamomum/micranthum
Publication https://www.hardwoodgenomics.org/Publication/2843417
Reference genome https://www.hardwoodgenomics.org/Genome-assembly/2843418
CDS Loader https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/722436
Protein loader https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/733576
Published mRNA polypeptide https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/722441
Swissprot Annotation https://www.hardwoodgenomics.org/BLAST-annotation/2986206
Trembl Annotation https://www.hardwoodgenomics.org/BLAST-annotation/2986207
IPS Annotation https://www.hardwoodgenomics.org/InterProScan-annotation/2986208
Kegg Annotation https://www.hardwoodgenomics.org/InterProScan-annotation/2986208
Swissprot loader https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/742953 CHECK
TrEMBL Loader https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/742957 CHECK
IPS Loader https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/733197
KEGG Loader https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/733198
BLAST DB transcripts https://www.hardwoodgenomics.org/content/cinnamomum-micranthum-transcripts
BLAST DB peptides https://www.hardwoodgenomics.org/content/cinnamomum-micranthum-peptides

**Comment by CaseyRichards92** [comment]
lcl files need to be removed from cds file so BLAST can run correctly. Fixed.

Check re ran blast files on ACF when complete. Fixed.

**Comment by patricksis** [comment]
Jbrowse instance:
https://www.hardwoodgenomics.org/admin/tripal/extension/tripal_jbrowse/management/instances/11

**Comment by patricksis** [comment]
@cricha59 
This organism is good to go
