### ISSUE TITLE
GO CV Browser permissions issue

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#329]
### Bug description

GO CV browser has non-GO terms at top of tree (ends_during, regulates, both of which are relationship terms) and when I click on a set of records, I get a "You are not authorized to access this page."

### Location

*  Go to https://hardwoodgenomics.org/organism/Fraxinus/excelsior
*  Click on 'Ontology Browser'
*  Click on " 7561 records." next to biological process term
*  Get error

**Comment by bradfordcondon** [comment]
OK, I think this was a noob module developer mistake.  Created an issue for module, just need to set permissions for this page.
