### ISSUE TITLE
Organism image and description

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#33]
The organism page is not rendering the image or the description from the original site. (tested on 8095)

**Comment by almasaeed2010** [comment]
Note: description fields are broken in all content types. Only happening on 8095.

**Comment by almasaeed2010** [comment]
@jwest60:
 Images don't exist for the following organisms:
* Alnus rhombifolia (White Alder)
* Alnus rubra (Red Alder)
* Fagus grandifolia (American Beech)
* Fraxinus excelsior (European Ash)
* Juglans regia (English Walnut)
* Populus trichocarpa (Poplar)
* Quercus lobata (Valley Oak)

**Comment by bradfordcondon** [comment]
I don't think this is a Tripal 3 issue.

Every tree on this list missing an image and description is also missing an image and description in the tripal 2 content type.  On both dev and live.

Acer Saccharum has the image and description (albeit it lost the bold formatting in the labels):  http://160.36.205.61:8095/bio_data/11

**Comment by bradfordcondon** [comment]
Sorry was late to the party, these tripal 3 descriptions and images were added manually.

Joe's list above are trees without images or descriptions for the Tripal 2 content though.

**Comment by bradfordcondon** [comment]
Plan of attack:  
* manually readd images, or hope we fix migration
 - https://github.com/tripal/tripal/issues/230
* Manually change description Text Format type to correct type.

**Comment by bradfordcondon** [comment]
organism image migration has been fixed in core.

**Comment by bradfordcondon** [comment]
>I had to completely delete the description field and readd it for it to work

Hey @almasaeed2010 I'm running into this issue migrating i5k.  Don't you think it merits a tripal core issue?  Did we ever find a better solution than just deleting the field and manually adding hte descriptions back?  or perhaps just a note in the migration documentation?

**Comment by almasaeed2010** [comment]
We created new description fields that attached directly to CHADO columns instead of some public schema table and manually migrated content. I am pretty sure we could write a script that copies the content of the old fields and places them in a new text field but I don't think it's needed unless you are migrating hundreds of fields.

Maybe we could also ask Stephen and Shawna if they've encountered it. There might be a simple way to fix this.

**Comment by bradfordcondon** [comment]
in my case the data IS in the chado.description column, but hte field wont let me set the filter type.  very weird.
