### ISSUE TITLE
Ontology browser needs to specify GO and other requests for GO browser

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#331]
### Bug description

Currently, when clicking on "ontology browser" pane, it is not clear that the ontology displayed is the gene ontology. This should be specified with a link out to the GO homepage. In the future when we have more than one ontology, this will need to be thought about too, how to tell users what ontology they are browsing or allow them to select among ontologies. It would make more sense for now to change the pane title to "GO Browser" or "Gene Ontology Browser"

### Location

*  Go to https://hardwoodgenomics.org/organism/Juglans/regia?tripal_pane=group_ontology

**Comment by almasaeed2010** [comment]
I am gonna go ahead and change the pane names to `Gene Ontology Browser`

**Comment by almasaeed2010** [comment]
So we reloaded GO and reindexed the browser but we still have the issue of incorrect terms being displayed or terms from GOSlim: https://hardwoodgenomics.org/organism/Fraxinus/excelsior?tripal_pane=group_ontology

What do u make of that?

**Comment by bradfordcondon** [comment]
big improvement.
Now the obsolete terms that were loaded via the mini GO are still there, but all overlapping terms are tucked away in their proper location.

I will manualy delete all obsolete terms rather than delete the CV and reload

**Comment by bradfordcondon** [comment]
I'm also going to dleete the weird go terms where the name and accessions are mixed up:
ie
select * from chado.cvterm where name='GO:1903046';
cvterm_id	cv_id	name	definition	dbxref_id	is_obsolete	is_relationshiptype
135294	92	GO:1903046		246175	0	0

**Comment by bradfordcondon** [comment]
the last term to deal with is 

biofilm matrix.

```
select * from chado.cvterm where name = 'biofilm matrix';
cvterm_id	cv_id	name	definition	dbxref_id	is_obsolete	is_relationshiptype
138276	58	biofilm matrix	A structure lying external to microbial cells. A biofilm is an aggregate of surface-associated cells, and the biofilm matrix is the envelope of polymeric substances that surrounds the cells. [GOC:BHF, PMID:22571672, PMID:27129222, PMID:28516088]251885	0	0
(1 row)
```

so its not an easy solution where theres 2x terms.

the term appears twice in the gene ontology, both in cellular_component.  It's the correct accession:

https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0062039

**Comment by bradfordcondon** [comment]
insert it as `biofilm matrix is a extracellular matrix ` (see obo def below)

```

[Term]
id: GO:0062039
name: biofilm matrix
namespace: cellular_component
def: "A structure lying external to microbial cells. A biofilm is an aggregate of surface-associated cells, and the biofilm matrix is the envelope of polymeric substances that surrounds the cells." [GOC:BHF, PMID:22571672, PMID:27129222, PMID:28516088]
is_a: GO:0031012 ! extracellular matrix
created_by: dph
creation_date: 2018-05-04T12:49:17Z

```

`insert (54711, 138276,  61120) into chado.cvterm_relationship`

**Comment by bradfordcondon** [comment]
* all anomalous terms fixed.  this was mostly deleting bad terms, with 1 case of adding the relationship to a term (biofilm matrix -> extracellular matrix).
* updating cvtermpath and then the indexer
* seperate issue for not displaying relaitonship terms: https://github.com/statonlab/tripal_cv_xray/issues/54

**Comment by bradfordcondon** [comment]
![screen shot 2018-08-02 at 1 54 13 pm](https://user-images.githubusercontent.com/7063154/43601600-904c6f1e-965b-11e8-862e-d851456f168f.png)

Strange: new problems have popped up: NFAT protein and the unnamed term.

**Comment by bradfordcondon** [comment]
* add the relationship from the obsolete term to the new term
* rename the obsolete term from GO_xxxx to receptor activity
* delete the obsolete, unused NFAT term.
```
insert into chado.cvterm_relationship (type_id, subject_id, object_id) VALUES (54711, 56488, 55020);
`update chado.cvterm set name = 'receptor activity' where name = 'GO_0004872';`
delete from chado.cvterm where name = 'NFAT protein import into nucleus';
```

Now, repopualte cvtermpath for molecular function, and the root mview, and then reindex.

**Comment by bradfordcondon** [comment]
deleting the obsolete unused term just means that now its child terms are root.  oops.

`regulation of NFAT protein import into nucleus [GO:0051532]`.  Let's add it where it belongs in the ontology.  I htink linking it to the NOT OUTDATED term ie calcineurin-NFAT signaling cascade should do the trick.


calcineurin-NFAT signaling cascade

https://www.ebi.ac.uk/QuickGO/term/GO:0033173

`insert into chado.cvterm_relationship (type_id, subject_id, object_id) VALUES (54711,89166, 74952);`

**Comment by bradfordcondon** [comment]
our go ontology got messed up somehow.  rerunning the importer. 
 previous problems shouldnt persist because they were due to goslim... https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/415271

**Comment by bradfordcondon** [comment]
from http://planteome.org/node/1

<img width="491" alt="screen shot 2018-08-16 at 4 40 28 pm" src="https://user-images.githubusercontent.com/7063154/44233890-1aef4700-a173-11e8-941f-e736f263d3b7.png">


* TO - plant triat ontology
* PO - plant ontology
* PATO - phenotypic qualty ontology, reference heavily in TO giving us problems in terms of tidy display
