### ISSUE TITLE
GO terms for transcriptomes

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#332]
### Feature description
The IPS results from the transcriptomes also have associated GO terms that could be used to population the ontology browser for those organisms. Are the GO terms already stored? Or do we need to rerun IPS? Maybe we should rerun things anyway, as some are getting quite old.

**Comment by bradfordcondon** [comment]
@matthuff we thought this would be good for you down the road possibly

**Comment by bradfordcondon** [comment]
we're doing this in #362 .  I wont close this issue for tracking purposes but when #362 is closed this one should be too.

**Comment by bradfordcondon** [comment]
transcriptomes have go terms.  see for example https://www.hardwoodgenomics.org/organism/Prunus/serotina?tripal_pane=group_ontology
