### ISSUE TITLE
What if we rewrite the EntityController to use Ajax? Much faster site!

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#335]
The current site is pretty slow when visiting pages that are not cached/haven't been visited before. The initial iteration of Tripal 3 used AJAX to load fields lazily as users click on the pane. The only reason they reverted that feature and removed ajax was that they needed to know whether the field has data which means the load function must run to determine if the field needs to be visible. But we can get around that by using First Paint and AMD methods and lazily populate the rest of the panes.

In theory, this will reduce the page's load time to only the first pane in the list (summary pane in most cases). The rest of the panes will be loaded asynchronously. Browser history (to open a pane using the browser link) can be taken into consideration when decided which pane should be loaded first.

**Comment by bradfordcondon** [comment]
seems sound enough to me.  any outstanding questions or homework that neds to be done before we could add it as an issue on core?

**Comment by almasaeed2010** [comment]
I don't think core will accept to do this without seeing a working example since they attempted to do this before. I want to override core's implementation and test it out before bringing it to their attention.

**Comment by almasaeed2010** [comment]
So this is actually available in tripal but we need to explore how to do it. There is an issue on core so I'll close this one.
