### ISSUE TITLE
CVTerm usage on tripal.info

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#339]
Dorrie's group is interested in seeing what CV terms we've used for fields and entity types, we thought it would be helpful to somehow share our CV term choices across groups more broadly. Should we create a page on tripal.info to share this? Ask anyone in T3 to chime in...

**Comment by bradfordcondon** [comment]
see:

https://github.com/tripal/tripal/issues/407

https://github.com/tripal/tripal/issues/441

https://docs.google.com/spreadsheets/d/1wJbekYwaw4qULHdjh4hapWwrj82-w9IqiHs_1flr3iM/edit?usp=sharing

**Comment by bradfordcondon** [comment]
/remind me in 24 hours to do the TERMS spreadsheet

**Comment by bradfordcondon** [comment]
https://docs.google.com/spreadsheets/d/1KRunFjy-E_ml1VKrFqwkmO0SwKN8RjcTYMm00Prsd1M/edit?usp=sharing

Here's the fields we use.

We can send her our fields, and hte links above.

**Comment by bradfordcondon** [comment]
Thanks for sending @mestato

**Comment by bradfordcondon** [comment]
bad robot
