### ISSUE TITLE
new fixed KEGG OBO needs to be PRd to tripal repo

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#341]
We have fixed the OBO generator and the resulting KEGG OBO file for the tripal_analysis_kegg module, but not pushed the changes to the main repo.

@jwest60 i did the previous pR but this was largely your work so i'd like you to try doing it.  This is good for you, it makes your contributions easier to trace and down the road you can say " I contributed to this open source project, with X lines of code".

So:

* PR to this branch: https://github.com/tripal/tripal_analysis_kegg/tree/7.x-3.x
* IN your PR, you need to write a brief summary of what changes were made in why.  In your case, the previous OBO was just buggy as heck, wrong relationships, etc.  Describe improvements to the OBO generator.  Maybe a screenshot of the fixed ontology tree.

All of this info including screenshots is already in https://github.com/statonlab/hardwoods_site/issues/99

**Comment by jwest60** [comment]
https://github.com/tripal/tripal_analysis_kegg/pull/11

i'm an idiot and accidentally forgot to change the base and head forks so i had to close my first pr and create a new one so i'm hoping that doesn't cause any kind of issue

**Comment by bradfordcondon** [comment]
thanks Joe looks good to me.  I'm leaving this issue open until the PR is merged.

**Comment by bradfordcondon** [comment]
/remind me in one week to follow up on this

**Comment by almasaeed2010** [comment]
Merged.
