### ISSUE TITLE
collaborate with lacey to improve jbrowse?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#343]
lacey would like to improve the jbrowse module ot make it embeddable.   I think this would be a good collaboration, possibly making good use of @almasaeed2010 without requiring Chado work.

**Comment by almasaeed2010** [comment]
I'll start installing the module to see what current issues are there:
https://github.com/tripal/tripal_jbrowse/

**Comment by almasaeed2010** [comment]
Unfortunately, I don't think we really have the time to do this so I am gonna close. Please reopen if you feel you can help.

Thanks!
