### ISSUE TITLE
Standardize analysis names

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#345]
We need a standard, consistent pattern for all analysis names.

- For reference genome, I suggest "<Latin organism name> Reference Genome <version>"
- For gene expression, I suggest "<Latin organism name> Gene Expression <1-2 keywords about tissue/treatment>". Might need more here for specificity? Like an author name or year?
- For blast, this one is already pretty consistent, but a few changes:
  - lets update to latin name, so "<Latin organism name> mRNA BLASTX against <database>"
  - sprot is probably confusing, lets use "SwissProt"
- For interpro, this one is also pretty consistent, but a few changes:
  - right now tends to have latin name and common name, lets limit to just latin name 
  - also the only anlaysis where organism name is last instead of first
  - so lets move to "<Latin organism name> peptides InterProScan"
- For transcriptome, "<Latin organism name> Transcriptome Assembly"

Can we add these patterns to loader pages? Where else can we put it so it stays consistent?

The gene expression analyses need to be updated to not only fit the above pattern but to be accurate (many say ozone when ozone actually many abiotic stresses are present).

Black Walnut Ozone Treatments -> "Juglans nigra Gene Expression - Abiotic Stress"
Northern Red Oak Ozone Treatments	-> "Quercus rubra Gene Expression - Abiotic Stress"
Green Ash Ozone Treatments -> "Fraxinus pennsylvanica Gene Expression - Abiotic Stress"
American Sweetgum Ozone Treatments -> "Liquidambar styraciflua Gene Expression - Abiotic Stress"	
Sugar Maple Ozone Treatments -> "Acer saccharum Gene Expression - Abiotic Stress"
Honey Locust Ozone Treatments -> "Gleditsia triacanthos Gene Expression - Ozone Stress"
Tulip Poplar Ozone Treatments -> "Liriodendron tulipifera Gene Expression - Ozone Stress"
Blackgum Ozone Treatments -> "Nyssa sylvatica Gene Expression - Ozone Stress"

**Comment by bradfordcondon** [comment]
>Can we add these patterns to loader pages? Where else can we put it so it stays consistent?

We can add them to the "name" field by editing the field settings on the bundle.  The pattern we want should definitely go there, and i think putting it there will be sufficient.

**Comment by bradfordcondon** [comment]
#367 and views for other analysis types make it very easy (and glaring) to see the consistency of naming.

**Comment by bradfordcondon** [comment]
- [ ] rename existing analyses

- [ ] update field to display instructions

**Comment by bradfordcondon** [comment]
As we can see previous genome assembly names are all over the map.

we'l change them all to follow waht the instructions will say:


```
Names should follow the form

[Full latin name ] - Reference Genome [additional version info]
For example:

Fraxinus pennsylvanica - Reference Genome

```` 

<img width="596" alt="screen shot 2018-09-04 at 2 53 25 pm" src="https://user-images.githubusercontent.com/7063154/45051693-ca248d00-b052-11e8-8710-a340c4590f57.png">

**Comment by bradfordcondon** [comment]
Here's how this looks now.

I'm going to double check on our meeting tomorrow this is what we want before i edit *all analyses*
<img width="526" alt="screen shot 2018-09-04 at 3 30 19 pm" src="https://user-images.githubusercontent.com/7063154/45053257-75cfdc00-b057-11e8-8396-e87fa5512ce7.png">

**Comment by bradfordcondon** [comment]
approved.  I can go ahead.

**Comment by bradfordcondon** [comment]
>Draft reference genomes for six Juglans species and Pterocarya stenoptera


I'm leaving this name as is for now and say we just expect to have some oddball names for analyses that arent for a single organism.

The alternative would be to list all 7 species.

**Comment by bradfordcondon** [comment]
almost done.  Edge cases:

[TulipPoplar_v1 BLAST to Populus peptides](https://www.hardwoodgenomics.org/BLAST-annotation/1962950)

Chinese Chestnut QTL and regular have 2x, blastp and blastx.  for example:  https://www.hardwoodgenomics.org/BLAST-annotation/1962957

**Comment by bradfordcondon** [comment]
```
select * from chado.analysis where name='TulipPoplar_v1 BLAST to Populus peptides';
analysis_id	name	description	program	programversion	algorithm	sourcename	sourceversion	sourceuri	timeexecuted
13	TulipPoplar_v1 BLAST to Populus peptides		blastx	2.2.19	blast	TulipPoplar_v1_454Isotigs-vs-Pt156pep.blastx10.xml			2011-11-03 00:00:00
(1 row)
hardwoods_06112018=> select * from chado.analysisfeature where analysis_id = 13;
analysisfeature_id	feature_id	analysis_id	rawscore	normscore	significance	identity
(0 rows)
```

so i think the tulip poplar BLAST ones can be safely deleted since they aren't linked to anything.
Chinese Chestnut QTL I'm just going leave as is because that organism is a rule-breaker.
