### ISSUE TITLE
Update gene expression analyses

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#346]
All descriptions need updating for all 10 organisms with gene expression experiments. Need to find a better way to visualize the biosamples all on one page.

**Comment by almasaeed2010** [comment]
Looks like he already finished it:

<img width="523" alt="screen shot 2018-09-17 at 3 27 21 pm" src="https://user-images.githubusercontent.com/1512664/45645384-4032e600-ba8e-11e8-9da9-fe67823b3a1a.png">

Thanks @bradfordcondon

**Comment by bradfordcondon** [comment]
>All descriptions need updating for all 10 organisms with gene expression experiments. Need to find a better way to visualize the biosamples all on one page.



note the issue is for the *descriptions* not the names.

Also note the request for better visualization.

**Comment by almasaeed2010** [comment]
Ok I'll try to address this issue but I'll probably need a bit more info on this from @mestato

**Comment by almasaeed2010** [comment]
Add search bar above the tabel

**Comment by mestato** [comment]
I'm redoing the expression analysis pages now.
- most are more than just ozone treatments, so renaming analysis
- removing list of biosamples that is hard coded (again not exhaustive, only contains some samples)
- removing library/reads/bases tables (again not exhaustive, only contains some samples)
- removing assembly stats, as that should be on assembly analysis page

This leaves the description pretty bare, but at least no longer inaccurate/incomplete.
