### ISSUE TITLE
jbrowse from old dev site needs to be added to new dev site for green ash

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#347]
request from meg:

>just realized, before you take down the 160 dev site, the green ash jbrowse needs to be moved over to the new dev site and all the folks in the UK need to know the new URL

**Comment by almasaeed2010** [comment]
done

**Comment by almasaeed2010** [comment]
the url: https://hardwoods.ag.utk.edu/tools/jbrowse/index.html?data=greenash

**Comment by almasaeed2010** [comment]
I am gonna reopen this until @mestato acknowledges that it's available now.

**Comment by almasaeed2010** [comment]
Got an email that shows it has been acknowledged.
