### ISSUE TITLE
Add Pink Ipe to genome list, gene search, and BLAST databases

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#348]
### Bug description
Needs to be added to 

- the genome page: https://hardwoodgenomics.org/genomes
- the gene search: https://hardwoodgenomics.org/gene-search
- the BLAST list of databases: https://hardwoodgenomics.org/blast/protein/protein

Is there any way to automate some or all of these? Also need to update documentation for how to load reference genomes.

**Comment by bradfordcondon** [comment]
Pink IPE:

* Flat files need to be hosted
* need description for genome assembly analysis

**Comment by almasaeed2010** [comment]
The genome analysis should show up automatically now in the genomes page.

**Comment by bradfordcondon** [comment]
We will need to format the blast db and create a dbxref for it.

**Comment by bradfordcondon** [comment]
i'm closing this to do the blast db adding in #368 since it involves the same things (find the sequences...)
