### ISSUE TITLE
Logged in users get 'access denied' for galaxy workflows

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#351]
### Bug description
Even when logged in, selecting a galaxy workflow yields "access denied". Only admin can access the workflows.

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Should be fixed. Testing now

**Comment by mestato** [comment]
Add authenticated user permission for the permission category "Execute Published Galaxy Workflows". Fixed on live site.

**Comment by almasaeed2010** [comment]
Yep fixed. I tested with a new account that is not an admin.
