### ISSUE TITLE
Galaxy doesn't show up in tool menu

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#352]
### Bug description
Galaxy doesn't show up in tool menu. The page of workflows https://hardwoodgenomics.org/content/tripal-galaxy-workflows does include the menu setting with "tool" as the parent menu. 

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Added to tools menu
