### ISSUE TITLE
"Forbidden" when uploading file to Galaxy workflow

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#353]
### Bug description
Logged in an authenticated user (not admin), get "forbidden" when trying to upload a file to a galaxy workflow.

Specifically seen in bowtie2 single end mapping workflow: https://hardwoodgenomics.org/content/mapping-bowtie2-single-end

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
This seems like a tripal file permissions issue again. See https://github.com/tripal/tripal/issues/293

I'll look into the code and see if we can reapply the fix temporarily and report to tripal

**Comment by MingChen0919** [comment]
I was able to run the workflow with an authenticated user (not admin) without any problems on the dev site, i am creating a new account on the live site to test.

**Comment by MingChen0919** [comment]
The permission issue was fixed by checking the permission boxes for both admin and authenticated users. 

However, i got a new issue:

<img width="469" alt="screen shot 2018-08-07 at 12 39 46 pm" src="https://user-images.githubusercontent.com/1262709/43789896-1d7bfd14-9a3f-11e8-96c4-f46b36646db6.png">

**Comment by mestato** [comment]
Yes, I get that issue too.

**Comment by MingChen0919** [comment]
it has been a week. I just created a new account on the live and tested the upload functionality. I was able to upload files without problems. Will test this again next week.

**Comment by almasaeed2010** [comment]
The issue was likely because the job runner uses a different user than user than `apache`. If the issue shows up again, we'll need to switch cron from root to apache.

**Comment by almasaeed2010** [comment]
Seems like it's still working so I am gonna close this.
