### ISSUE TITLE
Site Speed Profiling

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#354]
A tripal site with less modules performs significantly better than a site with many custom modules. This could be the case because we have a module that's populating the cache before it's needed. Let's try to profile our dev sites with each module enabled/disabled to see if one module makes a bigger difference than the rest.

Testing steps per module:

1. [x] Disable all custom modules
1. [x] Clear the cache (measure the speed using chrome's network tab)
1. [x] Enable 1 custom module
1. [x] load the home page (measure the speed when that's happening)
1. [x] Start from step 1 again

**Comment by almasaeed2010** [comment]
local site results:

|Enabled Modules|Time to Clear Cache|
|All|2.1 minutes|
|tripal only (no custom modules at all)|1.9 minutes|
|none (no tripal!)|6.2 seconds|

So according to this, enabling Tripal alone makes the site 2 minutes slower. We need to figure out which part of tripal is causing this issue and whether this is true for a completely new site.

**Comment by almasaeed2010** [comment]
**Note:** time have been obtained by clearing cache at least 3 times and picking the minimum time.

**Completely new site (no modules or content at all):**
cache: 107 milliseconds

**tripal installed without preparing:**
cache: 400 milliseconds

**tripal, tripal_chado, tripal_chado_views enabled and site prepared (no content yet):**
cache: 4.88 seconds

**tripal, tripal_chado, tripal_chado_views, tripal_ds with 200 mRNAs, 1 Organism and 1 Analysis:**
cache: 4.93 seconds

---

### Everything from here after will be enabled and disabled before moving to the next module

**tripal_analysis_expression:**
cache: 5.33 seconds
**Note:** disabling tripal_analysis_expression kept the cache clearing time at 5.50 seconds. This could indicate improper clean up of fields or some other type of data?

**tripal_analysis_interpro:**
cache: 5.86 seconds
after disabling: 5.81 seconds

**tripal_analysis_blast**
cache: 6.17 seconds
disabled: 6.13

**tripal_blast**
cache: 15 seconds
disabled: 15.59 seconds

**Comment by bradfordcondon** [comment]
are those times to clear the cache or rebuild?  2 minutes is insane long for clearing, i'd believe rebuilding though.

Thanks for doing this.  Any ideas for how to use this info to improve?

**Comment by almasaeed2010** [comment]
That's the rebuild part (visiting the home page after `drush cc all`)

I am still performing tests to try to figure out where it's all going wrong.

**Comment by almasaeed2010** [comment]
This is now fixed! See our merged PR for details: https://github.com/tripal/tripal/pull/542
