### ISSUE TITLE
Chinese Chestnut Features Missing Parents

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#356]
As discussed, here is a list of features that have no parents. They are all Chinese Chestnut features that appear to be proteins. They are indexed in the site and do have entities but the entities are practically empty. 

[hwg_missing_parent_features.txt](https://github.com/statonlab/hardwoods_site/files/2274661/hwg_missing_parent_features.txt)

**Comment by bradfordcondon** [comment]
these are organism_id's not entity_id's.

since its therefore hard for someone without db to access, here is an example:

```
select * from chado.feature where feature_id = 2129094;
2129094		24	maker-scaffold05536-augustus-gene-0.22-mRNA-2	maker-scaffold05536-augustus-gene-0.22-mRNA-2	MDRSFLFSLLLLFSVVASTFSADEINGDDLLIEQVVSSSDGGDDPLLHAEHHFSSFKARFGKSYGSVEEHDYRFGVFKANLRRAKIHQKLDPSAEHGVTKFSDLTPAEFRRNFLGLKRLRLPSDAQKAPILPTNDLPTDFDWRDHGAVTGVKDQGACGSCWAFSTAGALEGAHFLETGELVSLSEQQLVDCDHECDPEEYGACDSGCNGGLMTSAFEYTLKAGGLEKEEDYPYTGTDRGTCKFDKDKIVASVANFSVVSTDEEQIAANLVKNGPLARVVTYAEWIQWSQLWLLYIPPVTRL	301	05ba63f493ffc90fab9bd9576e43bccd	236	f	f	2015-10-19 19:03:57.064724	20
```


https://hardwoodgenomics.org/bio_data/170046

**Comment by mestato** [comment]
When I search for "maker-scaffold05536-augustus-gene-0.22" in hardwoods, it gives me 3 results. 

![screen shot 2018-08-14 at 9 04 56 am](https://user-images.githubusercontent.com/508122/44093284-157b05d0-9fa1-11e8-9612-ed5c35069ec4.png)

We've got to weird issues here. When I click on maker-scaffold05536-augustus-gene-0.22 (https://hardwoodgenomics.org/bio_data/2047286) it returns "Access denied". This implies that elasticsearch both indexes and presents results from non-public data.

Second, for the maker-scaffold05536-augustus-gene-mRNA-2, this is related to #258  I think. From JBrowse, the mRNAs that aren't a 1 auto redirect from maker-scaffold05536-augustus-gene-mRNA-2 to maker-scaffold05536-augustus-gene-mRNA-1. I think they must have all been loaded but not deleted?

**Comment by bradfordcondon** [comment]
* feature name: maker-scaffold05536-augustus-gene-0.22
* its a chado GENE feature (type_id 215).  however it's listed as a mRNA entity

**Comment by bradfordcondon** [comment]
Alchemist can handily convert genes to mRNA and vice versa.  In fact, any mRNA entities whose chado record says gene SHOULD be automatically converted by alchemist.

![screen shot 2018-08-20 at 10 15 02 am](https://user-images.githubusercontent.com/7063154/44345656-ed034e80-a461-11e8-8638-abd307915946.png)


However there are no elligible entities.  why not?

**Comment by bradfordcondon** [comment]
```
select * from chado_bio_data_26 where entity_id = 2047286;
mapping_id	entity_id	record_id	nid
21861	2047286	2034782
(1 row)
```

eww so its listed as a gene in its chado_bio_data table.  maybe its cross-listed?

**Comment by bradfordcondon** [comment]
ok.  issue is that tripal_alchemist didnt trigger entity_update hook so ES did not re-index as the new type.

@almasaeed2010 has said he will manually change in ES.  and I created issue to improve alchemist:  https://github.com/statonlab/tripal_alchemist/issues/34

**Comment by almasaeed2010** [comment]
I'll lest the steps here so you can check the logic

- [ ] Get all entity ids from chado_bio_data_26 that have features with organism chinese chestnut (inner joins)
- [ ] Update the `type` column to say `Gene` instead of mRNA - polypeptide.

**Comment by bradfordcondon** [comment]
this issue is secondary to the original issue: `maker-scaffold05536-augustus-gene-0.22-mRNA-2` is a naked feature https://hardwoodgenomics.org/bio_data/170046

**Comment by bradfordcondon** [comment]
> type column 
this is in the ES index right?

**Comment by almasaeed2010** [comment]
correct

**Comment by almasaeed2010** [comment]
it looks like all the features in chado_bio_data_26 belong to Chinese chestnut. So I am gonna covert all of them in ES to bio_data_26

**Comment by almasaeed2010** [comment]
Doing bulk update on dev deletes the records except and inserts only the new bundle_label ... need another way to loop through and update instead of bulk updating

**Comment by bradfordcondon** [comment]
or, we could fix alchemist, convert to a new type, then convert back to gene so they get reindexed.

**Comment by almasaeed2010** [comment]
That might be a good choice since we have a test case for it

**Comment by bradfordcondon** [comment]
* create "insert" feature type
* update features that are gene to insert so alchemist will see them as convertible 
   - we could also make a collection but thats hard because ES doesnt have them indexed right!
* run alchemist to convert
* redo in opposite direction

**Comment by bradfordcondon** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/564012

job converting genes to insert

**Comment by almasaeed2010** [comment]
I don't remember where we got with this. We convert the tripal job to drupal queues but then did we rerun it on dev/live?

**Comment by bradfordcondon** [comment]
this one was small enough to not need the queues.  

Its possible we need to run the job to convert *back* to genes to get them indexed.

**Comment by bradfordcondon** [comment]
>this one was small enough to not need the queues.

Not true?  I see the job has erroered.  Let's finish the mRNA_contig -> mRNA conversion issue first then return to this.

**Comment by bradfordcondon** [comment]
We now have genes, and mRNA.

![screen shot 2018-09-18 at 10 33 24 am](https://user-images.githubusercontent.com/7063154/45695047-98212980-bb2e-11e8-8c30-0c44712cdbda.png)

but what happened to maker-scaffold05536-augustus-gene-0.22-mRNA-2 ?  he is no longer indexed by ES.

**Comment by bradfordcondon** [comment]
```

hardwoods_06112018=> select * from chado.feature where name = 'maker-scaffold05536-augustus-gene-0.22-mRNA-2';
2129094		24	maker-scaffold05536-augustus-gene-0.22-mRNA-2	maker-scaffold05536-augustus-gene-0.22-mRNA-2	MDRSFLFSLLLLFSVVASTFSADEINGDDLLIEQVVSSSDGGDDPLLHAEHHFSSFKARFGKSYGSVEEHDYRFGVFKANLRRAKIHQKLDPSAEHGVTKFSDLTPAEFRRNFLGLKRLRLPSDAQKAPILPTNDLPTDFDWRDHGAVTGVKDQGACGSCWAFSTAGALEGAHFLETGELVSLSEQQLVDCDHECDPEEYGACDSGCNGGLMTSAFEYTLKAGGLEKEEDYPYTGTDRGTCKFDKDKIVASVANFSVVSTDEEQIAANLVKNGPLARVVTYAEWIQWSQLWLLYIPPVTRL	301	05ba63f493ffc90fab9bd9576e43bccd	236	f	f	2015-10-19 19:03:57.064724	2015-10-19 19:03:57.064724
hardwoods_06112018=> select * from chado.feature where name = 'maker-scaffold05536-augustus-gene-0.22-mRNA-1';
2090764		24	maker-scaffold05536-augustus-gene-0.22-mRNA-1	maker-scaffold05536-augustus-gene-0.22-mRNA-1	ACACTCACAACACAGTGTTTGCTTGCAACGACGTTAAATGGACCGCTCTTTTCTCTTCAGCCTCTTGCTCTTATTCTCTGTGGTCGCGTCCACCTTTTCCGCCGATGAAATCAACGGCGATGATCTTCTGATCGAGCAAGTGGTGTCGTCATCGGACGGCGGTGACGATCCTCTCCTCCACGCGGAGCACCACTTCTCGAGCTTCAAGGCGAGGTTTGGGAAAAGCTATGGGAGCGTAGAGGAGCACGATTACAGGTTCGGCGTGTTCAAGGCGAACCTGCGCAGAGCCAAGATTCACCAGAAGCTGGACCCCAGCGCTGAACACGGTGTCACCAAGTTCTCGGATCTCACTCCGGCTGAGTTCCGGCGAAACTTTCTTGGGTTGAAGCGGCTTCGGTTGCCTTCCGATGCTCAGAAGGCTCCTATTCTTCCCACCAACGATCTCCCCACCGACTTTGACTGGCGTGATCACGGCGCCGTCACCGGCGTCAAAGACCAGGGTGCTTGTGGATCGTGCTGGGCGTTTAGTACTGCAGGGGCATTGGAAGGAGCTCATTTTTTGGAGACTGGGGAGCTAGTGAGCCTCAGTGAGCAACAGCTTGTGGATTGTGACCATGAGTGTGATCCCGAGGAATATGGTGCATGCGACTCAGGCTGCAATGGTGGGCTGATGACTTCCGCCTTTGAGTACACGCTCAAGGCTGGTGGACTTGAGAAAGAGGAGGATTATCCTTACACTGGAACTGATCGTGGCACCTGCAAATTTGACAAGGACAAAATTGTTGCTTCTGTAGCTAACTTCAGTGTTGTTTCAACTGATGAAGAACAAATTGCCGCGAATTTGGTGAAGAATGGCCCTCTTGCAATAAATCATTGATGGATGGAAATAAATAATGACTCTTTTGCTCTGTATTGTGCAGTTGGCATCAATGCAGTATTCATGCAGACCTACATTGGAAAAGTTTCATGCCCATACATCTGTGGGAAGCAATTGGATCACGGGGTGCTTCTAGTGGGCTATGGTTCTGCTGGTTATGCTCCTATCCGGTTCAAGGAAAAGCCATTCTGGATCATAAAGAACTCTTGGGGAGAAAACTGGGGAGAGAATGGATATTACAAGATCTGCAGGGGTCGTAACGTATGCGGAGTGGATTCAATGGTCTCAACTGTGGCTGCTATACATACCACCAGTGACTAG	1198	d41d8cd98f00b204e9800998ecf8427e	145	f	f	2015-10-18 14:24:00.001719	2015-10-18 14:24:00.001719
2129093		24	maker-scaffold05536-augustus-gene-0.22-mRNA-1	maker-scaffold05536-augustus-gene-0.22-mRNA-1	MDRSFLFSLLLLFSVVASTFSADEINGDDLLIEQVVSSSDGGDDPLLHAEHHFSSFKARFGKSYGSVEEHDYRFGVFKANLRRAKIHQKLDPSAEHGVTKFSDLTPAEFRRNFLGLKRLRLPSDAQKAPILPTNDLPTDFDWRDHGAVTGVKDQGACGSCWAFSTAGALEGAHFLETGELVSLSEQQLVDCDHECDPEEYGACDSGCNGGLMTSAFEYTLKAGGLEKEEDYPYTGTDRGTCKFDKDKIVASVANFSVVSTDEEQIAANLVKNGPLAINH	279	a4ce1493845d5379a187132d32aee4c6	236	f	f	2015-10-19 19:03:57.064724	2015-10-19 19:03:57.064724
hardwoods_06112018=>
```

**Comment by bradfordcondon** [comment]
solutions:

* delete these parent-less proteins.
* load the parents.  they wouldnt have the relationship, so we'd also have to reload the peptides.

**Comment by almasaeed2010** [comment]
Ok the files are available here:
https://hardwoodgenomics.org/Genome-assembly/1962958?tripal_pane=group_downloads

I think we can filter them down to only the transcripts/peptides that have `mRNA-2` in the name and give them to @MattHuff to run both interpro and blast and I can take care of the reloading. Since those don't have entities, I am gonna go ahead and remove them from chado:

```sql
delete from chado.feature where name like '%mRNA-2' and organism_id = 24
```

How does this sound @bradfordcondon?

**Comment by almasaeed2010** [comment]
Features deleted.

/remind me tomorrow at 9 am to delete orphaned mRNA entities

**Comment by almasaeed2010** [comment]
The trimmed fasta files are located at `/var/www/html/sites/default/files/sequences/chineseChestnut09182018`

Once we clear the orphans, we can reload these files with ips and blast.

**Comment by almasaeed2010** [comment]
According to tripal_alchemist we have 0 orphaned mRNA entities. So deleting the features didn't create orphaned entities? (I don't understand how or why that is)

**Comment by almasaeed2010** [comment]
Oh so it runs out all of the features that were published as entities and have `mRNA-2` in their name are actually part of the QTLs organism!

https://hardwoodgenomics.org/bio_data/1753356?tripal_pane=group_summary_tripalpane

and there are only 33 of them:
```sql
select count(*) from tripal_entity where title like '%mRNA-2';
 count 
-------
    33
(1 row)
```

**Comment by almasaeed2010** [comment]
- [ ] Load mRNA ([Job submitted](https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/443691))
- [ ] Publish mRNA
- [ ] Load peptides

**Comment by almasaeed2010** [comment]
Sequences reloaded successfully. @MattHuff will ask for the fasta files once the ACF clears. Let's close this issue and open a new one for blast and ips
