### ISSUE TITLE
Better Visibility for Our Modules

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#358]
Most of the Drupal and Tripal community are used to downloading and installing modules through interfaces and/or drush. I think we should consider spending a little time trying to get trusted dev account on drupal

We have small modules that we can submit and ask Lacey and Stephen to review. I don't think it'll take us long to get approved.

**Comment by bradfordcondon** [comment]
https://www.drupal.org/node/1047190

**Comment by bradfordcondon** [comment]
also need to set up ssh access https://www.drupal.org/node/1027094

**Comment by bradfordcondon** [comment]
https://github.com/statonlab/tripal_cv_xray/issues/61

**Comment by bradfordcondon** [comment]
- [x] cv_xray

- [x] elasticsearch


I havent been super excited about this.  IMO we can add if people request drush access for further modules.
