### ISSUE TITLE
8095 (Tripal 3) organism/analysis content problems

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#36]
- [x] Transcriptome page (Menu item Genomic Data -> Transcriptomes) is empty. 

- [x]  Other than chestnut, the organisms with reference genomes (F. excelsior, J. regia, Q. lobata) have no links to their genome analysis page or transcript search or jbrowse

- [x] European ash (Fraxinus excelsior) genome page (http://160.36.205.61:8095/content/European-Ash) has a hard coded link to wrong organism page:
http://160.36.205.61:8095/organism/Fraxinus/excelsior

- [x] Organism pages don't link to transcriptomes (used to appear in sidebar)

- [x]  Organism pages don't link to transcript search

- [x]  gSSR page (http://160.36.205.61:8095/content/gssrs) hard coded to wrong organism links

**Comment by bradfordcondon** [comment]
>Transcriptome page (Menu item Genomic Data -> Transcriptomes) is empty.
Created by Tripal_transcriptomes_table module, [resolved](https://github.com/statonlab/tripal_transcriptomes_table/pull/1)

**Comment by almasaeed2010** [comment]
>Other than chestnut, the organisms with reference genomes (F. excelsior, J. regia, Q. lobata) have 
> no links to their genome analysis page or transcript search or jbrowse
Resolved

**Comment by bradfordcondon** [comment]
> Organism pages don't link to transcript search

implemented via feature search field
