### ISSUE TITLE
Load IPR with GO into HWG

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#362]
See the project board for all the required tasks: 

https://github.com/orgs/statonlab/projects/9

**Comment by almasaeed2010** [comment]
So we have the data for the dev site located at: `/var/www/html/sites/default/files/sequences/hwg_ips_08132018`

An analysis has been created for this on dev too: https://hardwoods.ag.utk.edu/InterProScan-annotation/2209440

**Comment by almasaeed2010** [comment]
We launched 32 jobs with 102 files in each job (dev)

**Comment by almasaeed2010** [comment]
To see results output (progress that's usually printted by the importer job) you can run: 
```
cat /var/www/html/sites/default/files/sequences/hwg_ips_08132018/xmls/ips_batch_*.out
```

**Comment by almasaeed2010** [comment]
Parallel importer completed in 15 minutes (3239 xml files)!

Going to run the tripal_cv_xray indexer

**Comment by almasaeed2010** [comment]
I can't see see an "annotations" tab on any of the organism pages :-|

**Comment by almasaeed2010** [comment]
We shouldn't need a regular expression to do the feature matching since the data came directly from the site do we?

**Comment by bradfordcondon** [comment]
no regular expression. i would also not specify a sequence type, since its actually a mix (mrna and mrna_contig)

**Comment by bradfordcondon** [comment]
* Seperate run/load required for chinese chestnut and HAIMP due to proteins/mRNA having the same name.

**Comment by almasaeed2010** [comment]
After file 2427 of 3239, we ended up with a memory leak

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes) in phar:///usr/bin/drush/lib/Drush/Log/Logger.php on line 47

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8388616 bytes) in phar:///usr/bin/drush/lib/Drush/Log/Logger.php on line 47
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Allowed memory size of 134217728 bytes exhausted (tried to
allocate 8388616 bytes) in
phar:///usr/bin/drush/lib/Drush/Log/Logger.php, line 47
```

We are gonna have to split those files into separate directories and run them in sequential jobs

**Comment by almasaeed2010** [comment]
Split into 5 jobs:

- [job 1](https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/538482)
- [job 2](https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/538485)
- [job 3](https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/538486)
- [job 4](https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/538487)
- [job 5](https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/538488)

they are running in sequence so when 5 is done, we are good to test.

**Comment by bradfordcondon** [comment]
first batch of xml files at: `/var/www/html/sites/default/files/ips_aug2018_prots_from_145/`

**Comment by almasaeed2010** [comment]
Annotations show up for live 

Examples from different organisms: 

https://hardwoodgenomics.org/bio_data/2209213?tripal_pane=gp_sio__annotation14713

https://hardwoodgenomics.org/feature/Cornusflorida12062016isotig36140?tripal_pane=gp_sio__annotation53572

https://hardwoodgenomics.org/feature/Potri014G0678001?tripal_pane=gp_sio__annotation14713

Next steps?

- [ ] Run for mRNA Contig (will take longer than 9 hours)
- [ ] Once done with mRNA Contig, run the genes ES indexer on live

**Comment by almasaeed2010** [comment]
**Update**: mRNA Contig job is still running and at 314 out of 400 files.

**Comment by almasaeed2010** [comment]
Job completed. All of our features should now be annotated with both GO and IPR. Will run the gene indexer tomorrow

**Comment by almasaeed2010** [comment]
Only the following organisms have GO terms

 ```organism_id | common_name  
-------------+--------------
          48 | Valley Oak
          22 | Sugar Maple
          30 | Black Cherry
          46 | European Ash```

here is the query I used to get this:
```select distinct(organism.organism_id), organism.common_name 
  from chado.feature_cvterm 
  inner join chado.cvterm on cvterm.cvterm_id = feature_cvterm.cvterm_id 
  inner join chado.feature on feature.feature_id = feature_cvterm.feature_id
  inner join chado.cv on cv.cv_id = cvterm.cv_id
  inner join chado.organism on organism.organism_id = feature.organism_id 
where cv.cv_id in (56, 57, 58);```

All organisms have interpro terms though. What does this mean? Do we not have GO terms in the XMLs? Is the job failing to match against feature names?

**Comment by almasaeed2010** [comment]
This was an interpro loader error that we fixed. Rerunning the job for mRNA_contig

- [ ] [mRNA_contig job](https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/420254)
- [ ] mRNA job (link coming after contigs are done)

**Comment by almasaeed2010** [comment]
Job 2 running. Updated comment above with urls.

**Comment by bradfordcondon** [comment]
```
select distinct(organism.organism_id), organism.common_name
hardwoods_06112018->   from chado.feature_cvterm
hardwoods_06112018->   inner join chado.cvterm on cvterm.cvterm_id = feature_cvterm.cvterm_id
hardwoods_06112018->   inner join chado.feature on feature.feature_id = feature_cvterm.feature_id
hardwoods_06112018->   inner join chado.cv on cv.cv_id = cvterm.cv_id
hardwoods_06112018->   inner join chado.organism on organism.organism_id = feature.organism_id
hardwoods_06112018-> where cv.cv_id in (56, 57, 58);
23	Green Ash
28	American Beech
39	White Alder
25	American Chestnut
37	Chinese Chestnut Disease Resistant  QTL Regions
13	Tulip Poplar
48	Valley Oak
22	Sugar Maple
38	Red Alder
19	Northern Red Oak
15	Honeylocust
45	Hydrangea
31	Blackgum
44	Dogwood
27	White Oak
30	Black Cherry
46	European Ash
18	Black Walnut
14	American Sweetgum
```

NICE!

**Comment by almasaeed2010** [comment]
Fully Loaded!!

- [ ] Run Gene Search Indexer
- [ ] Run CV XRay Indexer

**Comment by almasaeed2010** [comment]
All indexers completed.

**Comment by almasaeed2010** [comment]
Here are all the organisms that current have go terms

```
23	Green Ash
28	American Beech
39	White Alder
25	American Chestnut
37	Chinese Chestnut Disease Resistant  QTL Regions
13	Tulip Poplar
22	Sugar Maple
48	Valley Oak
38	Red Alder
19	Northern Red Oak
15	Honeylocust
45	Hydrangea
31	Blackgum
50	Eastern Cottonwood
44	Dogwood
51	Pink Ipe
27	White Oak
24	Chinese Chestnut
30	Black Cherry
42	English Walnut
46	European Ash
49	Poplar
18	Black Walnut
14	American Sweetgum
```

24 organisms out of 34

**Comment by bradfordcondon** [comment]
that sounds about right.  i think if you do a search for organisms without features and it'll be about 10.

**Comment by bradfordcondon** [comment]
<img width="815" alt="screen shot 2018-08-23 at 5 14 08 pm" src="https://user-images.githubusercontent.com/7063154/44552330-f9083e00-a6f7-11e8-8ca0-e64b5a08c7c7.png">


GO browser looking good.

KEGG browser not showing up.

**Comment by bradfordcondon** [comment]
it looks like having both browsers in the same field doesnt work.  I'm only seeing kEGG OR GO browsers, never both.

let's put them in seperate tripal panes.

**Comment by bradfordcondon** [comment]
transcriptomes now have both.

![screen shot 2018-08-24 at 10 25 37 am](https://user-images.githubusercontent.com/7063154/44590040-2270aa80-a788-11e8-8f64-3ec93d97c82a.png)

Genomes only have GO: did the KEGG terms for mRNA not get associated correctly/fail?

**Comment by bradfordcondon** [comment]
this issue is accomplished.

**Comment by almasaeed2010** [comment]
Indexer completed. In case there is something we wanna check.

**Comment by bradfordcondon** [comment]
thanks.  i had the kegg mRNA field misconfigured.  kegg annotations now present for all.
