### ISSUE TITLE
genomes section of page needs to link to chado records not pages

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#367]
while youre at it, copy the html from the pages to the chado records

**Comment by almasaeed2010** [comment]
Steps to get this done: 

- [ ] create analyses for the genomes that don't have one in https://hardwoods.ag.utk.edu/genomes (you can match against `https://hardwoods.ag.utk.edu/genome` since this one has only analysis not simple pages)
- [ ] copy data from pages to analyses
- [ ] Make sure downloadables go in a downloads tab

**Comment by almasaeed2010** [comment]
Discovered we have 3 genome analyses for English Walnut

1. https://hardwoods.ag.utk.edu/Genome-assembly/1963051
1. https://hardwoods.ag.utk.edu/Genome-assembly/1963053

I think we can delete both though and create a new one that has the correct info

**Comment by almasaeed2010** [comment]
Ok Genomes converted and data search is available: https://hardwoodgenomics.org/data_search/genome_assembly

**Comment by almasaeed2010** [comment]
@mestato if you can let us know which fields you'd like to show up on the genomes page, we can add them then add then links to the menu.

See https://hardwoodgenomics.org/data_search/genome_assembly
And view located at: https://hardwoodgenomics.org/admin/structure/views/view/Genome_Assembly_search/edit

**Comment by bradfordcondon** [comment]
definitely want the organism linker field if we can have it, as that will make it searchable etc by organism

**Comment by almasaeed2010** [comment]
Done

**Comment by bradfordcondon** [comment]
i like this view because it gives us something to easily proof.


* citrus has an analysis but no organism page (and therefore no features etc)[https://hardwoodgenomics.org/Genome-assembly/1962952?tripal_pane=group_details]
* duplicate j regia (one with, one without the organism linker)
* it doesnt know what to do with Draft reference genomes for six Juglans species and Pterocarya stenoptera, which does indeed have all organisms linked correctly (*but there are multiple*)

**Comment by bradfordcondon** [comment]
pages are very different so does warrant discussions.


old page
![screen shot 2018-08-22 at 5 04 34 pm](https://user-images.githubusercontent.com/7063154/44490851-7f0b8280-a62d-11e8-9f06-39ccee46858a.png)


new page

![screen shot 2018-08-22 at 5 04 28 pm](https://user-images.githubusercontent.com/7063154/44490844-7ca92880-a62d-11e8-8aa2-29e8dc4220d5.png)

**Comment by bradfordcondon** [comment]
we're going ahead with this view unless there are objections from @mestato .

However I'm going to resolve #390 first, since all 3 will show up on this page.

**Comment by almasaeed2010** [comment]
Since the analyses got deleted, I think we can move forward with this. I'll deploy the view to live.

**Comment by almasaeed2010** [comment]
Done
