### ISSUE TITLE
mrna contigs add no value and confuse users

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#370]
### Feature description
@mestato has requested that we convert them to mRNA.  I'm in agreement.

**Comment by bradfordcondon** [comment]
## Pros of mRNA contig

* more biologically relevant label
* makes manipulation of transcriptomes vs genomes a little easier since you can specify the feature type

## Cons

* doubles administrative work of configuring the content type
* causes confusion for users when they are forced to deal with both types, ie creating collections


Either way we should not change until the recent annotation (KEGG/interproscan) are loaded.  see #99 #360

**Comment by almasaeed2010** [comment]
KEGG, GO and IPS are loaded so we can move forward with this. Should I go ahead and do it? Should I take a DB backup first?

**Comment by bradfordcondon** [comment]
yes, back up db first.

Yes, you can go ahead and convert all mrna_contigs to mRNA.

We will need to remove the mRNA contig custom fields attached to organism as well (for hte ontology browsers) once its done.

**Comment by almasaeed2010** [comment]
Back up started `/data2/backups/`

**Comment by almasaeed2010** [comment]
The process number to check on this next week: 21197

**Comment by bradfordcondon** [comment]
```

hardwoods_dev=# select * from chado.cvterm where name = 'mRNA_contig';
cvterm_id	cv_id	name	definition	dbxref_id	is_obsolete	is_relationshiptype
101394	7	mRNA_contig	A contig composed of mRNA_reads. [SO:ke]	195916	0	0
(1 row)
hardwoods_dev=# select * from chado.cvterm where name = 'mRNA';
cvterm_id	cv_id	name	definition	dbxref_id	is_obsolete	is_relationshiptype
145	7	mRNA	Messenger RNA is the intermediate molecule between DNA and protein. It includes UTR and coding sequences. It does not contain introns. [SO:ma]	153	0	0
```

so 
```
update chado.feature SET (type_id) = 145 WHERE  type_id =  101394
```

then you can run alchemist on automatic , selecting source = mRNA_contig destination = mRNA

**Comment by bradfordcondon** [comment]
<img width="1057" alt="screen shot 2018-08-28 at 3 49 49 pm" src="https://user-images.githubusercontent.com/7063154/44747019-08153480-aada-11e8-9e29-cbfe44e61749.png">


alchemist automatic mode runs out of memory trying t oconvert.

**Comment by bradfordcondon** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/594932

fixed, definitely an improvement (instead of fetching ALL entities, just do a count and then fetch the first 10 to show table).

**Comment by almasaeed2010** [comment]
Great! I am glad we having pagination here. 

Note that the job failed within 1 minute from launching :( I tried to find the logs but it doesn't seem like there is anything in them. Did you run the job using `nohup`?

**Comment by bradfordcondon** [comment]
shoot.  cron beat me to it.

**Comment by bradfordcondon** [comment]
job is now running after resolving issue.

**Comment by almasaeed2010** [comment]
I vote to replace the hooks with the new importer hooks. I can do that tomorrow.

**Comment by almasaeed2010** [comment]
The issue with that though is that the importer hooks don’t provide entity ids and therefore we’ll need to rerun the entire indexing process.

**Comment by bradfordcondon** [comment]
>importer hooks don’t provide entity ids  

nothing we can do about that unfortunately.


 Better than needlessly rerunning indexer when we know that the new entities wont have the annotations loaded.

**Comment by almasaeed2010** [comment]
Ok, then we are gonna have to save the admin settings first to be able to rerun it with the same settings.

**Comment by bradfordcondon** [comment]
However I made a mistake in the paging which abdullah has fixed.

with the fix, time  for 200 entities: `7.452s`

So for ~1 million entities, i believe thats only 10 hours.

**Comment by bradfordcondon** [comment]
@almasaeed2010 has implemented queues.  Let's try rerunning on dev with this new feature.

**Comment by bradfordcondon** [comment]
Tripal alchemist triggers this hook:

```
        // Trigger entity update hook
        $entities = tripal_load_entity('TripalEntity', [$entity_id], TRUE, [], FALSE);
        $entity = reset($entities);
        module_invoke_all('entity_update', $entity, $entity->type);
      }
```

Desired behavior:  **no running** for cv_xray.  I thinkwe just want to manually re-run the cv_xray indexer afterwards.

Reindex for ES: entities should be re-indexed because new fields might be attached, and we need them to display as the new bundle type.

**Comment by bradfordcondon** [comment]
Job viewable at: 
https://hardwoods.ag.utk.edu/admin/config/system/queue-ui

Note the tripal_alchemist queue:
<img width="1354" alt="screen shot 2018-09-04 at 10 57 05 am" src="https://user-images.githubusercontent.com/7063154/45039270-4c03be80-b031-11e8-9c8b-03dd83b20a5f.png">

**Comment by bradfordcondon** [comment]
It's finished running!  However it only converted about half: we got to 590294.  I resubmitted another job

**Comment by almasaeed2010** [comment]
Ok so again same problem. At first the numbers lined up but by the time it was done, we have half still not converted.

Here is my suggestion: let's take it back to a single job but in the queue instead of tripal jobs.

**Comment by almasaeed2010** [comment]
Job is running. To see the log: `tail -f /var/log/tripal_cron`

**Comment by almasaeed2010** [comment]
So in the tripal content page, it says we have 2 mRNA Contigs left. But in Alchemist, it says we have 4 with 0 qualifying for automatic transformation. I don't know what to make of that.

**Comment by bradfordcondon** [comment]
running the query to convert mrna_contigs to mrna on live (ie `update chado.feature SET (type_id) = (145) WHERE  type_id =  101394`.

Once it finishes, I'll run alchemist on automatic and link the job.

**Comment by bradfordcondon** [comment]
Queue at:  https://www.hardwoodgenomics.org/admin/config/system/queue-ui

![screen shot 2018-09-10 at 9 32 32 am](https://user-images.githubusercontent.com/7063154/45300512-8c08ec80-b4dc-11e8-9524-f8d391586378.png)

**Comment by bradfordcondon** [comment]
/remind me in 24 hours to check on job

**Comment by bradfordcondon** [comment]
after it finishes, we need to manually reindex elasticsearch

**Comment by bradfordcondon** [comment]
progress:  763956

Thats very roughly 3 hours per 100k entities converted.

**Comment by almasaeed2010** [comment]
Progress: 64848 remaining

**Comment by bradfordcondon** [comment]
success.

![screen shot 2018-09-12 at 3 08 40 pm](https://user-images.githubusercontent.com/7063154/45447522-d1284c80-b69d-11e8-8490-6d4e59c5cde4.png)


@almasaeed2010 can you trigger rebuiling the ES index?  Then we can close this out.

**Comment by almasaeed2010** [comment]
Great! Yep I'll trigger ES

**Comment by almasaeed2010** [comment]
Indexing is still running. Once that’s done, we need to verify that ES has updated the types correctly and that there are no contingency left in the index.

**Comment by almasaeed2010** [comment]
**progress** 281k `mRNA Contig` entities left in the index and we have about 1.01million `mRNAs`, which means the updating is successful and should finish by Monday.

/remind me to check on the indexing progress monday at 9 am

**Comment by almasaeed2010** [comment]
This is completed. No longer do we have mRNA contigs in the site and the bundle can be deleted safely.
<img width="487" alt="screen shot 2018-09-17 at 8 16 34 am" src="https://user-images.githubusercontent.com/1512664/45622475-1b208200-ba52-11e8-94c5-c82226e43f97.png">

**Comment by almasaeed2010** [comment]
Done!
