### ISSUE TITLE
Libraries page broken

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#372]
### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by bradfordcondon** [comment]
https://hardwoodgenomics.org/libraries

>There are no libraries matching the current criteria. If you think there should be, check that all chado libraries are sync'd with your website.

This isnt in the codebase so i'd bet its a view.

**Comment by bradfordcondon** [comment]
https://www.hardwoodgenomics.org/admin/structure/views/view/all_libraries/edit

this view is configured for `/libraries`


```
SELECT node_chado_library.nid AS node_chado_library_nid, library.uniquename AS library_uniquename, library.name AS library_name, organism_library__node.nid AS organism_library__node_nid, organism.common_name AS organism_common_name, cvterm.name AS cvterm_name
FROM 
{library} library
LEFT JOIN {chado_library} chado_library ON library.library_id = chado_library.library_id
LEFT JOIN {node} node_chado_library ON chado_library.nid = node_chado_library.nid
LEFT JOIN {organism} organism_library ON library.organism_id = organism_library.organism_id
LEFT JOIN {chado_organism} organism_library__chado_organism ON organism_library.organism_id = organism_library__chado_organism.organism_id
LEFT JOIN {chado_organism} organism_library_organism_library__chado_organism ON organism_library.organism_id = organism_library_organism_library__chado_organism.organism_id
LEFT JOIN {node} organism_library__node ON organism_library__chado_organism.nid = organism_library__node.nid
LEFT JOIN {organism} organism ON library.organism_id = organism.organism_id
LEFT JOIN {cvterm} cvterm ON library.type_id = cvterm.cvterm_id
ORDER BY organism_common_name ASC
LIMIT 30 OFFSET 0
```

So it's been broken since Tripal 3 migration and we just haven't noticed.

Note currently have two library content types: BAC and Genomic.

```
select * from chado.library;
library_id	organism_id	name	uniquename	type_id	is_obsolete	timeaccessioned	timelastmodified
1	24	BAC library CMCMBb	CMCMBb	34	0	2011-08-29 15:11:36.550989	2011-08-29 15:11:36.550989
2	24	BAC library CMCMBd	CMCMBd	34	0	2011-08-30 13:50:13.293015	2011-08-30 13:50:13.293015
3	25	American Chestnut BAC library CDC_Ba	CDC_Ba	34	0	2011-10-06 12:58:06.614434	2011-10-06 12:58:06.614434
5	13	Tulip Poplar BAC Library (LT__Ba)	LT__Ba	34	0	2011-10-06 13:17:41.493803	2011-10-06 13:17:41.493803
6	26	Quercus robur HindIII BAC Library	Qro-B-3Ph	34	0	2011-10-06 13:49:14.004145	2011-10-06 13:49:14.004145
7	26	Quercus robur EcoRI BAC library	Qro-B- EnglishOak 3P	34	0	2011-10-06 13:50:15.829113	2011-10-06 13:50:15.829113
8	19	BAC Library QRNRBa	QRNRBa	34	0	2014-01-10 12:50:15.617303	2014-01-10 12:50:15.617303
9	19	BAC Library QRNRBb	QRNRBb	34	0	2014-01-10 13:13:48.902647	2014-01-10 13:13:48.902647
10	18	BAC Library JNC_Ba	JNC_Ba	34	0	2014-01-10 13:14:54.277386	2014-01-10 13:14:54.277386
11	18	BAC Library JNC_Bb	JNC_Bb	34	0	2014-01-10 13:15:25.829623	2014-01-10 13:15:25.829623
12	24	CM_MBc	BAC Library CM_MBc	2073	0	2016-03-31 14:29:37.38318	2016-03-31 14:29:37.38318
```
* all libraries are BAC libraries exept one.  The sole genomic library has BAC library in the name.  So... we should probably change its type.
* Regardless, I propose we use a single library type, as i dont think we would display different content on one vs the other.  
* we can then make this page a simple view of Libraries.

**Comment by bradfordcondon** [comment]
https://www.hardwoodgenomics.org/admin/structure/views/view/organism_library
Need to figure out how to filter by the library field not being null and we can use this view instead.

**Comment by almasaeed2010** [comment]
How about this: https://hardwoodgenomics.org/data_search/bac_library

The data_search that tripal provides seems to work

**Comment by bradfordcondon** [comment]
yeah thats good too (better perhaps).

Before we do that, i want to convert all libraries to a single type, though.

**Comment by almasaeed2010** [comment]
Conversion done on dev. Check the `Library` on https://hardwoods.ag.utk.edu/admin/content/bio_data

**Comment by almasaeed2010** [comment]
Conversion done on live and a view to search libraries is ready: https://hardwoodgenomics.org/data_search/library

**Comment by bradfordcondon** [comment]
looks good to me. ⚡️

**Comment by almasaeed2010** [comment]
Cool then I'll clean up the old bundles and close this 👏
