### ISSUE TITLE
Host european ash flat files for genome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#373]
### Feature description
Currently, we link to Richard Bugg's website for the european ash genome (https://hardwoodgenomics.org/bio_data/1963052). We need to download and host the files locally, as his site links may change or the site may go away.

Link to Richard's site:
http://www.ashgenome.org/data

**Comment by almasaeed2010** [comment]
Steps: 

- [ ] Create a downloads tab for genome assembly
- [ ] Download data from the URL above and add to the downloads tab

**Comment by almasaeed2010** [comment]
Done https://hardwoodgenomics.org/Genome-assembly/1963052?tripal_pane=group_downloads
