### ISSUE TITLE
Tripal 2 to Tripal 3 Tabs (Features)

### ISSUE THREAD

**Issue by jwest60** [statonlab/hardwoods_site#38]
**QlobV1.0_scaffold83_0000050-RA** [**Tripal 2**](http://160.36.205.61:8095/feature/qlobv10scaffold830000050-ra) [**Tripal 3**](http://160.36.205.61:8095/bio_data/287755)
* Tripal 3 has an empty expression tab that does not exist in Tripal 2
* Tripal 3 has an annotations tab that does not exist in Tripal 2
* Annotated Terms
* Analyses
* Interpro

**FRAEX38873_v2_000160240.1** [**Tripal 2**](http://160.36.205.61:8095/feature/fraex38873v20001602401) [**Tripal 3**](http://160.36.205.61:8095/bio_data/134379)
* Tripal 3 has an empty expression tab that does not exist in Tripal 2
* Tripal 3 has an annotations tab that does not exist in Tripal 2
* Annotated Terms
* Analyses
* Interpro

**Juglans_regia_01182017_WALNUT_00001622-RA_mRNA** [**Tripal 2**](http://160.36.205.61:8095/feature/Juglans_regia_01182017_WALNUT_00001622-RA_mRNA) [**Tripal 3**](http://160.36.205.61:8095/bio_data/214243)
* Tripal 3 has an empty expression tab that does not exist in Tripal 2
* Analyses

**maker-scaffold01741-snap-gene-0.23-mRNA-1** [**Tripal 2**](http://160.36.205.61:8095/feature/maker-scaffold01741-snap-gene-0.23-mRNA-1) [**Tripal 3**](http://160.36.205.61:8095/bio_data/145913)
* Tripal 3 has an empty expression tab that does not exist in Tripal 2
* Analyses

**Comment by bradfordcondon** [comment]
OK, broken down into individual tasks:

- [ ] Expression tab should not appear if empty
- [ ] Annotations tab should not appear if empty

I think thats it?  I think this is closable.

**Comment by almasaeed2010** [comment]
Is the annotations tab appearing when it's empty?

**Comment by bradfordcondon** [comment]
example of annotation tab and expression tab not appearing when empty:

http://160.36.205.61:8095/bio_data/2038198
