### ISSUE TITLE
J regia has THREE genomes

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#390]
### Bug description
https://www.hardwoodgenomics.org/organism/Juglans/regia?tripal_pane=group_reference_genome

<img width="1430" alt="screen shot 2018-09-05 at 1 42 00 pm" src="https://user-images.githubusercontent.com/7063154/45110897-8a70aa80-b111-11e8-88d4-d706fd0d7208.png">

not a bug necessarily, but certainly a casuality of #345

**Comment by almasaeed2010** [comment]
Looks like we want to delete the old one since it has less info. How do we go about doing that? Anything we need to check before deleting an analysis (like if there are features associated with)?

**Comment by bradfordcondon** [comment]
we can archive the old one if t's truly a different assembly version.  Before doing so, we should ensure there are no features assocated with it.

**Comment by bradfordcondon** [comment]
similarly  red oak has 3 transcriptomes.  On the organism page the labels are correct:

https://www.hardwoodgenomics.org/organism/Quercus/rubra?tripal_pane=group_transcriptome

however in the Tripal view:

<img width="1411" alt="screen shot 2018-09-05 at 1 47 28 pm" src="https://user-images.githubusercontent.com/7063154/45111185-5053d880-b112-11e8-8222-cbdb294b9625.png">

**Comment by bradfordcondon** [comment]
```
 select count(*) from chado.analysisfeature where analysis_id = 125;
220340

select count(*) from chado.analysisfeature where analysis_id = 150;
64992

select count(*) from chado.analysisfeature where analysis_id = 191;
0
```

records: 125,  150, 191.  125 and 150 look almost identical in the analysis table.

**Comment by bradfordcondon** [comment]
analysis foreign keys to worry about:


quantification, project_a , phylotree, nd_experiment_a, aprop, afeature, a_relationship, a_pub, a_dbxref,a_cvterm.

I think only afeature is of relevence.

**Comment by bradfordcondon** [comment]
Only analysisprop and analysisfeature

```
select count(*) from chado.analysisprop where analysis_id in(125, 150, 191);
9
```

**Comment by bradfordcondon** [comment]
Something is very wrong.

analysis 125 has 16852 genes and mRNA.  analysis 150 has 32496 mRNA and polypeptide.  125 also has the supercontigs: 186636 of them.


```
select analysis_id, type_id, cvt.name, count(type_id) from chado.analysisfeature inner join chado.feature on feature.feature_id = analysisfeature.feature_id INNER JOIN chado.cvterm cvt ON cvt.cvterm_id = feature.type_id where analysis_id in (125, 150, 191) group by cvt.name, analysis_id, type_id;
analysis_id    type_id    name    count
125    215    gene    16852
125    145    mRNA    16852
150    145    mRNA    32496
150    236    polypeptide    32496
125    290    supercontig    186636
```

**Comment by bradfordcondon** [comment]
matt has re-annotated the IPS.

What about blast?  I'm guessing we didn't do that.

**Comment by almasaeed2010** [comment]
Yeah we are gonna need blast too. Since ACF is gonna be down, is it possible to use Staton server? Or is that also going through prepping the new drives?

**Comment by almasaeed2010** [comment]
Let's start loading the ips files at least. Did we already delete the old analyses?

**Comment by bradfordcondon** [comment]
no... we can delete the two older analyses, keep the one with no records, and reload pointing to that one.

**Comment by almasaeed2010** [comment]
>its real easy. delete teh two anlayes i say to delete in the issue, delete all features
>
>reload, associating with the third not-deleted analysis

**Comment by almasaeed2010** [comment]
Steps:

- [x] Delete old analyses (125, 150)
- [x] Delete all features
- [ ] Load mRNA 
- [ ] Load proteins and associate to mRNA
- [ ] Load IPR Scans
- [ ] Update genes index

**Comment by almasaeed2010** [comment]
Oh I need to somehow find and delete the old mRNA entities. Since Tripal doesn't provide an `unpublish` method yet. We need to figure out a way to identify them now since the actual features are deleted from chado so there is no association to an organism. I think a simple `LIKE` query can return those entities but since we also want trigger delete hooks so they are removed from whatever index uses them, I am gonna write a little script to do it.

**Comment by almasaeed2010** [comment]
Ok I am adding a new very simple but super useful feature to tripal alchemist to clear orphaned entities, entities that have no associated chado records. This feature, if good enough can then be ported over to the main tripal repo.

**Comment by almasaeed2010** [comment]
Publishing mRNAs job: https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/443269

**Comment by almasaeed2010** [comment]
This issue on `tripal_manage_analysis` will fix the fields pointing to both deleted analyses: https://github.com/statonlab/tripal_manage_analyses/issues/42

**Comment by almasaeed2010** [comment]
So checking the files in `/var/www/html/sites/default/files/IPS_aug_17_2018` looks like those are files for the entire site. We only want those for j regia. Have those been added to the server?

**Comment by almasaeed2010** [comment]
The xml files have the names abbreviated from `Juglans_regia_01182017_WALNUT_00003300-RA_mRNA` to `WALNUT_00003300-RA`. I'll run `sed` on them to add the missing part. This will keep JBrowse happy too.

**Comment by almasaeed2010** [comment]
IPR job: https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/443277
