### ISSUE TITLE
J Regia Needs Blast

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#398]
After fixing #390 we had to reload all the data for j regia. We are currently missing BLAST.

**Comment by MattHuff** [comment]
I've begun BLAST analysis for J. regia, starting with swissprot. Data was split into 200 individual files, and BLAST was carried out as described [here](https://github.com/mestato/statonlabprivate/wiki/ACF---Create-BLAST-and-IPS-XML-files-for-HWG).

**Comment by MattHuff** [comment]
Swissprot BLAST is complete, the files are located in `/var/www/html/sites/default/files/english_walnut_BLAST/sprot`.

**Comment by almasaeed2010** [comment]
- [ ] Load sprot ([Job](https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/443748))
- [ ] Load tremble

**Comment by MattHuff** [comment]
Trembl BLAST is complete, the files are located in `/var/www/html/sites/default/files/english_walnut_BLAST/trembl.

**Comment by almasaeed2010** [comment]
Blast loaded on live. Thanks @MattHuff for running the blast jobs.
