### ISSUE TITLE
Blast and IPS for Chinese Chestnut

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#402]
This needs to be done for a subset of the genome. The Fasta files are located at: `/var/www/html/sites/default/files/sequences/chineseChestnut09182018`

**Comment by MattHuff** [comment]
Swissprot BLAST for the Chinese Chestnut is underway.

**Comment by MattHuff** [comment]
Swissprot BLAST is complete, and the XML output files are located in `/var/www/html/sites/default/files/sequences/chineseChestnut09182018/BLAST_results/sprot`. Trembl and IPS analyses are underway.

**Comment by MattHuff** [comment]
Trembl output located in `/var/www/html/sites/default/files/sequences/chineseChestnut09182018/BLAST_results/trembl`.

**Comment by almasaeed2010** [comment]
Jobs submitted

**Comment by almasaeed2010** [comment]
IPS Job: https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/445745

**Comment by almasaeed2010** [comment]
Jobs done. Thanks @MattHuff.
