### ISSUE TITLE
Casey Devseed training

### ISSUE THREAD

**Issue by cricha59** [statonlab/hardwoods_site#404]
https://tripal-devseed.readthedocs.io/en/latest/

Guide to upload a new organism.

**Comment by cricha59** [comment]
mRNA and peptides have been loaded.

**Comment by cricha59** [comment]
Needed regular expression.

http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/8082

**Comment by cricha59** [comment]
Use >(.*)  for regular expression for the parent

**Comment by cricha59** [comment]
### Using BLAST
`ps aux | grep 15625`

**Comment by almasaeed2010** [comment]
training completed
