### ISSUE TITLE
Patrick dev seed training 

### ISSUE THREAD

**Issue by patricksis** [statonlab/hardwoods_site#405]
https://tripal-devseed.readthedocs.io/en/latest/loading_FASTA.html#
this is the documentation I'm following to create a new organism

**Comment by patricksis** [comment]
mRNA and peptides have been uploaded

**Comment by patricksis** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/8081
Loading polypeptide sequence job, first one failed due to not adding a > to regular expression
Regular expression used (>FRA.*?)(?=:)

**Comment by patricksis** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/8117
Loading polypeptide sequences other failed due to wrong regular expression 
This is the real expression >(.*)

**Comment by almasaeed2010** [comment]
training completed
