### ISSUE TITLE
Live site warning: tripal__dev_stage already exists

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#407]
We keep getting the following warning in job logs:

```
[site http://default] [TRIPAL WARNING] [CHADO_FIELDS] A field of type tripal__dev_stage already exists, yet a property wants to use the same term. The property cannot be added.
A field of type tripal__dev_stage already exists, yet a property       [warning]
wants to use the same term. The property cannot be added.
```

Does this mean we have 2 fields with the same property?

**Comment by bradfordcondon** [comment]
this is a chado prop attached to biomaterial i believe.

**Comment by almasaeed2010** [comment]
it looks like this prop is coming from `feature_property.obo`

**Comment by almasaeed2010** [comment]
Yep you are right. This is from the bundle's fields 

<img width="625" alt="screen shot 2018-09-24 at 11 44 22 am" src="https://user-images.githubusercontent.com/1512664/45962592-36aa0080-bfef-11e8-8144-08bddbd8a223.png">

**Comment by almasaeed2010** [comment]
When checking for new fields I get the following warning on the biomaterials bundle:

```
A field of type tripal__dev_stage already exists, yet a property wants to use the same term. The property cannot be added.
```

**Comment by bradfordcondon** [comment]
https://www.hardwoodgenomics.org/admin/tripal/extension/tripal_curator/CV_usage/42
we have two of those terms: dev_stage and dev-stage.  For now to kill the warning, just use curator to convert dev-stage to dev_stage.

**Comment by almasaeed2010** [comment]
Fixed thanks to @bradfordcondon's tripal curator module 👍
