### ISSUE TITLE
Images don't exist for organisms

### ISSUE THREAD

**Issue by jwest60** [statonlab/hardwoods_site#41]
Images don't exist for the following organisms:
* Alnus rhombifolia (White Alder)
* Alnus rubra (Red Alder)
* Fagus grandifolia (American Beech)
* Fraxinus excelsior (European Ash)
* Juglans regia (English Walnut)
* Populus trichocarpa (Poplar)
* Quercus lobata (Valley Oak)

**Comment by almasaeed2010** [comment]
See #33
