### ISSUE TITLE
Raymond Data Training

### ISSUE THREAD

**Issue by RaymondS1** [statonlab/hardwoods_site#410]
http://160.36.205.61:9090/bio_data/209
 link to organism

**Comment by RaymondS1** [comment]
http://160.36.205.61:9090/bio_data/213
Link to genome reference analysis

**Comment by RaymondS1** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22099
- [ ] FASTA file for mRNA.
- [ ] FASTA file for peptides.

**Comment by RaymondS1** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22121
mRNA published records

**Comment by RaymondS1** [comment]
`ps aux | grep 15163` 
Training blast job #

**Comment by almasaeed2010** [comment]
training completed
