### ISSUE TITLE
Amanda Data Training

### ISSUE THREAD

**Issue by adevine4** [statonlab/hardwoods_site#411]
http://160.36.205.61:9090/bio_data/208 link to organism

**Comment by adevine4** [comment]
http://160.36.205.61:9090/bio_data/214 link to genome reference analysis

**Comment by adevine4** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22096 mRNA loading job

**Comment by adevine4** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22100 polypeptide loading job

**Comment by adevine4** [comment]
http://160.36.205.61:9090/admin/tripal/tripal_jobs/view/22119 publishing job

**Comment by almasaeed2010** [comment]
training completed.
