### ISSUE TITLE
Testing collections

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#414]
We now have collections on our site, but haven't properly tested to see how they work, especially in being turned into downloadable files. Lets test out a few use cases and open bug issues for any that don't work:

* Search for a set of transcripts, create a collection
   * Download as fasta
   * Download functional annotation
   * Download gene expression values
* Search for a set of reference genomes and download details
* Search for a set of biosamples and download details

Test getting sequences into a galaxy workflow as well.

**Comment by almasaeed2010** [comment]
Let's add a search bar to this

**Comment by MingChen0919** [comment]
Testing process and results:

# Collections of transcripts
1. Download as fasta
**Search "heat shock" -> Select "Gene" -> Click "Create Downloadable Collection" -> Select "Gene" -> Click "Next Step" -> Select "Name", "Sequence" -> Click "Next Step" -> Add a name for this collection -> Click "Create Collection".**

I got this error:
```
Failed to create the collection 'gene sequence': Cannot create the collection. One with this name already exists
```

2. Download functional annotation

**Search "heat shock" -> Select "mRNA- polypeptide" -> Click "Create Downloadable Collection" -> Select "mRNA-polypeptide" -> Click "Next Step" -> Select "Name", "Protein Sequence" -> Click "Next Step" -> Add a name for this collection -> Click "Create Collection" -> Click "Create Files".**

Results: 
Cron job status is `error`.

3. Download gene expression values

**Search "heat shock" -> Select "mRNA- polypeptide" -> Click "Create Downloadable Collection" -> Select "Gene Expression Profiles" -> Click "Next Step" -> Select "Name", "Expression" -> Click "Next Step" -> Add a name for this collection -> Click "Create Collection" -> Click "Create Files".**

I got this error:
```
Failed to create the collection 'gene expression data': Must provide a 'ids' to TripalEntityCollection::addFields().
```

**Comment by almasaeed2010** [comment]
Gene Expression Profile errors:

```
2018-10-12 11:11:03: Calling: tripal_create_collection_files(51)
Writing tab delimeted file.
Writing comma separated file.
Getting entities for ids 0 to 8 of 8
Got 8 entities.
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
[site http://default] [TRIPAL ERROR] [TRIPAL] Unable to find field name for field id: 0
WD php: DivisionByZeroError: Modulo by zero in                           [error]
TripalJob->setItemsHandled() (line 510 of
/var/www/html/sites/all/modules/tripal/tripal/includes/TripalJob.inc).
DivisionByZeroError: Modulo by zero in TripalJob->setItemsHandled() (line 510 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalJob.inc).
Drush command terminated abnormally due to an unrecoverable error.       [error]
```

**Comment by almasaeed2010** [comment]
Same bundle (gene expression) using Tripal's default data search views:

```
2018-10-12 11:17:03: Calling: tripal_create_collection_files(53)
Writing tab delimeted file.
Writing comma separated file.
Getting entities for ids 0 to 8 of 8
Got 8 entities.
WD php: DivisionByZeroError: Modulo by zero in                           [error]
TripalJob->setItemsHandled() (line 510 of
/var/www/html/sites/all/modules/tripal/tripal/includes/TripalJob.inc).
DivisionByZeroError: Modulo by zero in TripalJob->setItemsHandled() (line 510 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalJob.inc).
Drush command terminated abnormally due to an unrecoverable error.       [error]
```

**Comment by almasaeed2010** [comment]
Verdict: remove collections until they are usable.

**Comment by bradfordcondon** [comment]
they are still useful for admin purposes (alchemist namely) so maybe just change permission to admin if we can?

**Comment by almasaeed2010** [comment]
Yeah that's possible

**Comment by almasaeed2010** [comment]
done.
