### ISSUE TITLE
Make it easier to add file links

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#415]
### Feature description

It's hard for users to use HTML to add links files on our site. How can we make it easier for them to paste links in?

- Can this be solved with a field?
- Maybe it's easier to develop a little web based tool to print the wanted HTML?
- Any other options?

### Link to relevant info

See this for an example: https://hardwoodgenomics.org/Genome-assembly/1963056?tripal_pane=group_downloads

**Comment by jwest60** [comment]
follow on #437
