### ISSUE TITLE
New Chinese Chestnut Assembly JBrowse

### ISSUE THREAD

**Issue by MattHuff** [statonlab/hardwoods_site#416]
Meg has provided us with updated scaffolds for the Chinese Chestnut (_Castanea mollissima_), and would like us to create a new Jbrowse genome browser for it. So far, I have the softmasked genome, BRAKER annotations with RNASeq results and either no additional gene models or gene models from the European Oak, and a single BigWig file for all RNASeq files used in BRAKER.

**Comment by almasaeed2010** [comment]
Do we want to create a new track or a new jbrowse instance?

**Comment by MattHuff** [comment]
A new instance. This is a different scaffold than what is currently on the website.

**Comment by almasaeed2010** [comment]
Steps to get this done:

- [ ] Move data to main dev server from staton server
- [ ] Add apache config for the new organism
- [ ] Create the jbrowse instance in `/data/apollo/[organism_name]`

**Comment by almasaeed2010** [comment]
Done: https://hardwoods.ag.utk.edu/tools/jbrowse/index.html?data=chinese_chestnut_3-2&loc=lcl_contig0000009%3A265115..397700&tracks=DNA&highlight=

**Comment by MattHuff** [comment]
@mestato - new Chestnut Jbrowse instance is up.

**Comment by MattHuff** [comment]
Run GenomeThreader analyses on the following species:
* Peach
* Poplar
* Arabidopsis

**Comment by almasaeed2010** [comment]
Is this done @MattHuff?

**Comment by MattHuff** [comment]
Yes.

**Comment by almasaeed2010** [comment]
Great! You can close issues when they are completed 👍 

Thanks!
