### ISSUE TITLE
Hide fields from entity forms

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#418]
We have fields such as Reference Genome that show up on the add/edit entity form. We should hide it.

**Comment by almasaeed2010** [comment]
Issue is on core: https://github.com/tripal/tripal/issues/703

**Comment by almasaeed2010** [comment]
As pointed out by @bradfordcondon we can use this [field permissions module](https://www.drupal.org/node/2802067)

**Comment by bradfordcondon** [comment]
I wrote a guide

https://tripal.readthedocs.io/en/latest/user_guide/content_types/field_permissions.html

**Comment by almasaeed2010** [comment]
@jwest60 try using the permissions module on your dev site. I'll assign you and @cricha59 this issue to figure out what fields need to be present and what can be hidden.

**Comment by bradfordcondon** [comment]
>Reference Genome that show up on the add/edit entity form

are you sure this isnt a case where the field provides a widget, but shouldnt?

**Comment by almasaeed2010** [comment]
Possibly. I don't remember where I saw this field (probably taking notes during a meeting lol). To clarify, we need to look at all fields on all bundles and anything that doesn't make sense or the curators (aka undergrads) never use should be hidden.

**Comment by bradfordcondon** [comment]
i know you know this, but making sure whoever does this knows too: CHECK AGAINST THE CHADO DOCUMENTATION.   Do not hide fields that are required for that table.

https://laceysanderson.github.io/chado-docs/index.html

**Comment by jwest60** [comment]
this is done on dev, viewing permissions have been modified on the following entities:

- [genome assembly](https://hardwoods.ag.utk.edu/bio_data/add/21)
- [organism](https://hardwoods.ag.utk.edu/bio_data/add/1)
- [publication](https://hardwoods.ag.utk.edu/bio_data/add/5)
- [blast annotation](https://hardwoods.ag.utk.edu/bio_data/add/23)
- [interproscan annotation](https://hardwoods.ag.utk.edu/bio_data/add/24)
- [kegg annotation](https://hardwoods.ag.utk.edu/bio_data/add/28)

enabling or disabling publication on genome assembly will enable or disable it on organism, there doesn't seem to be a way to get it to show up on one but not the other

**Comment by almasaeed2010** [comment]
@bradfordcondon here are the issues with this approach

- As mentioned by @jwest60 above, disabling a field on one bundle, disables it on all bundles.
- The super user always sees the fields no matter what (not a big deal to us in particular).

**Comment by almasaeed2010** [comment]
doesn't work for us.
