### ISSUE TITLE
Galaxy DESeq2 Workflow description bugs

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#422]
### Bug description
Step 2 of differential-expression-deseq2-analysis says "The first column are sample names". This is not true - the first column is gene or transcript names. 

Overall, this instruction needs to be much more explicit and include the header line.

Input read counts data in CSV format.

This file is formatted with a transcript on each row and individual samples as columns. Numbers must be raw counts of reads from each sample mapped uniquely to each reference transcript (not normalized data). Importantly for the analysis pipeline, the first row is a header row. It must contain unique sample (library) IDs for each column, and these sample names need to match with the sample IDs in the treatment data (Step 2).

Example:
,untreated1,untreated2,untreated3,untreated4,treated1,treated2
gene1,0,0,0,0,0,0
gene2,92,161,76,70,140,88

More information can be found on formatting in the "Count matrix input" section of the DESeq2 manual. (link to https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#count-matrix-input)

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by mestato** [comment]
And lets work on Step 2 instructions as well. Change to:

- Input sample information data in CSV format.
- The first column are sample names. Sample names have to match with column names in the count data from step 2.
-  The remaining columns are experimental factors.
- A header line must specify a label for each experimental factor

Example:
,condition,type
,treated1,treated,ingle-read
,treated2,treated,paired-end
,treated3,treated,paired-end
,untreated1,untreated,single-read
,untreated2,untreated,single-read
,untreated3,untreated,paired-end

More information can be found on formatting in the "Count matrix input" section of the DESeq2 manual, specifically see "coldata". (link to https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#count-matrix-input)

**Comment by mestato** [comment]
And Step 4. lots of repeated text that needs to go away. Also link to DESeq2 manual, specifically multi factor designs: https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#multi-factor-designs

(Otherwise its not clear how to set up the design correctly).

**Comment by MingChen0919** [comment]
Updated step 2:

<img width="705" alt="screen shot 2018-10-16 at 11 37 53 am" src="https://user-images.githubusercontent.com/1262709/47028760-fc3c0b00-d137-11e8-8289-53e304070f9a.png">

**Comment by MingChen0919** [comment]
The repeated text at step 4 is caused by a bug in the tripal galaxy module. I have submitted a PR for this.
