### ISSUE TITLE
Expression data downloads

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#423]
### Bug description
On ozone pages (https://www.hardwoodgenomics.org/bio_data/1962981, https://www.hardwoodgenomics.org/bio_data/1962969, https://www.hardwoodgenomics.org/bio_data/1962972)

Each has a link to "Download all expression data associated with this analysis." Clicking on this link results in "Generating file. Download will start automatically...". However, after waiting quite some time no download has started.

-- | --

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Related: https://github.com/tripal/tripal_analysis_expression/issues/222

**Comment by bradfordcondon** [comment]
yeah.  i think we just kind of lost the bead on this one/realized that what is really needed is a file field that lets people download flat file that attaches to analysis, but we never followed through/

**Comment by MingChen0919** [comment]
I'll send you the files I used for my dissertation.

**Comment by almasaeed2010** [comment]
Ok the data is up on the live site:

-[Red Oak](https://hardwoodgenomics.org/Gene-expression-profiling/1962981?tripal_pane=group_description)
-[Black Walnut](https://hardwoodgenomics.org/Gene-expression-profiling/1962972?tripal_pane=group_description)
-[Green Ash](https://hardwoodgenomics.org/Gene-expression-profiling/1962969?tripal_pane=group_description)

**Comment by almasaeed2010** [comment]
Until the issue on tripal_analysis_expression module is fixed, the broken expression download link will stay disabled on the live site.

**Comment by mestato** [comment]
This isn't disabled on the live site, at least not from features, eg https://www.hardwoodgenomics.org/bio_data/1409879?tripal_pane=group_expression

**Comment by bradfordcondon** [comment]
did we ever find the raw files?  If so very easy to host it via a drupal file field.

**Comment by mestato** [comment]
I put where to find the files in #222 . Is the proposal to link to download all expression values even if you are only looking at a single feature? Not optimal but ok.

**Comment by bradfordcondon** [comment]
hmmm i didnt realize the field was broken for individual features.  i wonder if thats a permission issue.

analysis, we use the file field.  features, we keep as is but fix what i would guess is the permission issue.

**Comment by almasaeed2010** [comment]
issue 222 in the analysis expression repo: https://github.com/tripal/tripal_analysis_expression/issues/222#issuecomment-435904784

**Comment by almasaeed2010** [comment]
Thanks to @jwest60 we now have the expression module automatically cache the file and offer for it download when available. 

We should add the files as analysis props manually for the few organisms that are already there.

**Comment by almasaeed2010** [comment]
Added to everything that had files.

**Comment by almasaeed2010** [comment]
I think this is done. If you encounter any issues, please open a new issue.
