### ISSUE TITLE
Markdown description fields do not work

### ISSUE THREAD

**Issue by cricha59** [statonlab/hardwoods_site#426]
### Bug description
Markdown description does not work so we have to create a new field so that description markdown will read correctly.

**Comment by cricha59** [comment]
There are over 30 organisms and this needs to be done for all of them.

**Comment by almasaeed2010** [comment]
Done for both Organisms and Genome Assemblies. Might need to do it for Transcriptome Assemblies but we'll get to that when we start working with Transcriptomes.

Thanks @cricha59!
