### ISSUE TITLE
Deleted analysis still appears on the organism page under analysis details tab

### ISSUE THREAD

**Issue by RaymondS1** [statonlab/hardwoods_site#429]
### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by RaymondS1** [comment]
Analysis: F. sylvatica

**Comment by almasaeed2010** [comment]
The deleted analysis is still present in the analysis details tab on the organism page. @jwest60 you worked on the tripal_manage_analyses module. Would you care to investigate this issue?

**Comment by jwest60** [comment]
this is now fixed on master, `git pull` the latest version of tripal_manage_analyses and it should work
