### ISSUE TITLE
Email goes to spam

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#43]
Check SPF, DKIM and rDNS records.

**Comment by almasaeed2010** [comment]
All records are valid but our server's reputation is almost nonexistent which makes email providers (gmail, etc) send mail to spam. There isn't much we can do about this. We'd have to use a middleware service such as Mailgun but Drupal isn't really set to support such services at this point.

**Comment by bradfordcondon** [comment]
I'll add that this is a perennial issue.

https://www.drupal.org/forum/support/post-installation/2010-07-30/how-to-prevent-email-sent-from-drupal-from-going-into
