### ISSUE TITLE
Automated(ish) annotation of all new features

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#432]
### Feature description
Idea...Right now the biocurators are spending a lot of time running blast and IPS on each new dataset. This seems very inefficient. What if we could psuedo-automate annotation of new features. For example:

- At the beginng of each month a cron jobs emails the admins and says there are x number of features (limited to mRNA and gene types) with no blast annotation and no IPS annotation. There are x number of features with blast annotation or IPS annotation that is more than 3 years old.
- The fasta creation module is able to generate a fasta file of these features.
- Matt or someone else runs all the features as a giant blast and ips job on the ACF
- A new analyses get created for blast and a new analysis for IPS, and the data uploaded. The analyses are not linked to particular organisms at this point, but can still give details on blast version, cutoff, etc.

This means features could go live on the website without annotation, but annotation should be added within about a month. Only one person deals with annotation and its done as one big batch once a month.

**Comment by almasaeed2010** [comment]
Testing on dev succeeds. I'll write up documentation and deploy live. Follow progress here: https://github.com/statonlab/automated_annotation
