### ISSUE TITLE
Add publication to all organisms

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#433]
All reference genomes should have publications.

**Comment by almasaeed2010** [comment]
@cricha59 I am gonna assign you this task. Let's discuss the next time you are here.

**Comment by mestato** [comment]
Data not published in peer review:
- Acer
- Alnus (both)
- Castanea dentata
- Castanea mollissima
- Cornus florida
- Fagus grandifolia
- Fraxinus americana
- Gleditsia
- Hydrangea
- Liquidambar
- Liriodendron
- Nyssa
- Persea
- Populus deltoides

To add:
- Castanea crenata - https://link.springer.com/article/10.1007/s11295-014-0829-7
- Castanea sativa - https://link.springer.com/article/10.1007/s11295-014-0829-7 (same)
- Castanea mollissima Blight QTLs - https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-1942-1
- Fraxinus excelsior - https://www.nature.com/articles/nature20786
- Fraxinus pennsylvanica - https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-3052-0
- Juglans regia - https://onlinelibrary.wiley.com/doi/full/10.1111/tpj.13207
- Morus notabilis - its there but lets make it a link
- Populus trichocarpa - http://science.sciencemag.org/content/313/5793/1596

Already Done:
- actinida
- fagus sylvatica
- handroanthus
- hevea

**Comment by cricha59** [comment]
**Completed pubs from above:**
Castanea crenata - https://www.hardwoodgenomics.org/Publication/2530343
Castanea sativa - https://www.hardwoodgenomics.org/Publication/2530343

**Comment by cricha59** [comment]
@adevine4 could you do a publication for Quercus robur when you get a chance.

**Comment by almasaeed2010** [comment]
This seems to be done. Thanks all!
