### ISSUE TITLE
Import from Google Scholar

### ISSUE THREAD

**Issue by jwest60** [statonlab/hardwoods_site#434]

**Comment by almasaeed2010** [comment]
@jwest60 I'll assign you this to look at after thanksgiving

**Comment by almasaeed2010** [comment]
So Google Scholar doesn't have an API. Makes it pretty difficult to parse.

**Comment by bradfordcondon** [comment]
how about another service, like web of science

**Comment by almasaeed2010** [comment]
From what I can tell, I don't think this is possible.
