### ISSUE TITLE
blast analyses with no hits are confusing

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#440]
### Feature description

Blast pages are confusing if no results (but an analysis).  the field shows up, with no db listed.

see:

https://hardwoods.ag.utk.edu/gene/2222467?tripal_pane=gp_format__blast_results17982

![screen shot 2018-11-08 at 10 23 13 am](https://user-images.githubusercontent.com/7063154/48208906-daeacb00-e341-11e8-9452-8cd5edee3267.png)

![screen shot 2018-11-08 at 10 15 49 am](https://user-images.githubusercontent.com/7063154/48208938-f0f88b80-e341-11e8-804d-e4c42b5574ef.png)

I made an issue to propose a fix for this:

https://github.com/tripal/tripal_analysis_blast/issues/26

**Comment by almasaeed2010** [comment]
addressed on the blast repo
