### ISSUE TITLE
Taxodium (bald cypress) genetic map

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#444]
### Data description
Yang et al.
High-density genetic map construction and quantitative trait loci identification for growth traits in (Taxodium distichum var. distichum × T. mucronatum) × T. mucronatum

https://bmcplantbiol.biomedcentral.com/articles/10.1186/s12870-018-1493-0

dense genetic map and QTL map:
"The final map harbored 6156 SLAF markers on 11 linkage groups, and was 1137.86 cM in length, with an average distance of 0.18 cM between adjacent markers. Separate QTL analyses of traits in different years by CIM detected 7 QTLs. While combining multiple-year data, 13 QTLs were detected by ICIM."

**Comment by jwest60** [comment]
im having difficulties finding the file containing the genetic map for this paper too

i look through all the xlsx files under the additional files header and it doesnt look like any of them contain map accessions

**Comment by mestato** [comment]
This map looks confusing. Lets skip it.
