### ISSUE TITLE
Juglans Cathayensis Genome 

### ISSUE THREAD

**Issue by patricksis** [statonlab/hardwoods_site#447]
https://treegenesdb.org/FTP/Genomes/Juct

**Comment by patricksis** [comment]
Files can bu found here:
https://treegenesdb.org/FTP/Genomes/Juct/v1.0/annotation/

**Comment by patricksis** [comment]
Organism page already created and reference genome have already been created:
https://hardwoods.ag.utk.edu/organism/Juglans/cathayensis?tripal_pane=group_summary_tripalpane
https://hardwoods.ag.utk.edu/Genome-assembly/2209433

**Comment by patricksis** [comment]
Ag site
InterProScan Annotation - https://hardwoods.ag.utk.edu/InterProScan-annotation/2640335
SwissProt Annotation - https://hardwoods.ag.utk.edu/BLAST-annotation/2640336
Trembl Annotation - https://hardwoods.ag.utk.edu/BLAST-annotation/2640337

**Comment by patricksis** [comment]
ACF trembl
```#PBS -N trembl_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=08:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/juglans_cathayensis/raw_data/BLAST-split/Juct.$
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/juglans_cathayensis/BLAST/trembl/juglans_c_tremb$
 -evalue 1e-5 \
 -outfmt 5

```

**Comment by patricksis** [comment]
swissprot 
```#PBS -N swissprot_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/juglans_cathayensis/raw_data/raw_data/BLAST-sp$
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/juglans_cathayensis/BLAST/swissprot/juglans_c_sw$
 -evalue 1e-5 \
 -outfmt 5

```

**Comment by patricksis** [comment]
ips 
```#PBS -N juglans_c_ips
#PBS -A ACF-UTK0011
#PBS -S /bin/bash
#PBS -t 1-200
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=3:30:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/interproscan-5.28-67.0/interproscan.sh \
 -i /lustre/haven/gamma/staton/projects/undergrads/juglans_cathayensis/raw_data/raw_data/ips-split/Juct.1_0.peptides.fa.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/gamma/staton/projects/undergrads/juglans_cathayensis/ips/xmls \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/gamma/staton/projects/undergrads/juglans_cathayensis/ips/tmp \
 > /lustre/haven/gamma/staton/projects/undergrads/juglans_cathayensis/ips/tmp/$PBS_ARRAYID.out```

**Comment by patricksis** [comment]
Had to run trembl again for 368 and 357 because those were the only two that exceeded walltime.

**Comment by patricksis** [comment]
Live site:
BLAST db for cds:
https://www.hardwoodgenomics.org/content/juglans-cathayensis-transcripts
for peptides:
https://www.hardwoodgenomics.org/content/juglans-cathayensis-peptides

**Comment by patricksis** [comment]
Dev site:
Trembl upload job:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/504979
Swissprot upload job:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/505038
ips upload job: 
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/505044
KEGG annotation: 
https://hardwoods.ag.utk.edu/KEGGresults/2803333
KEGG import:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/505111

**Comment by patricksis** [comment]
Live site:
Swissprot annotation:
https://www.hardwoodgenomics.org/BLAST-annotation/2665694
Trembl annotation:
https://www.hardwoodgenomics.org/BLAST-annotation/2665695
InterProScan annotation:
https://www.hardwoodgenomics.org/InterProScan-annotation/2665696
cds upload: 
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/608487
peptide upload:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/610103
Published mRNA:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/612179
Trembl data upload:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/622953
Swissprot data upload:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/624508

**Comment by MattHuff** [comment]
It looks like the peptide files were loaded as mRNA sequences:

https://www.hardwoodgenomics.org/feature/Juct_18549.t1?tripal_pane=group_sequence_tripalpane

This caused issues for our Automated Annotation files, because we ran `blastn` - a nucleotide-to-nucleotide alignment - and there are protein sequences present in the database:

```
>Fraxinus_pennsylvanica_120313_comp46602_c0_seq1
GGTATAGAATCTTGTTGGTTTGAGCCATTTATCTGCAAGCAAAAATTTTGTCGAGAACTTTCAGCAGTCCCTGAA
GCATTTAGATTCAGAGGACATGTAGAGGCAGATCTTCCAACACAAAGCCCCAGTCTTGGGTTTTCCTGTGCTGAC
ACTTCATCAATGGAAAGAATGTCATCAATTGGTGTTGACATACTTATGCCACTCATGGCACCCCGAGTAGCCGGC
ACAGTATGCCACAGACTTCTTTCAGCATGCTGAAAATACGTTGAACTGCCAGTTCCAGAATATTGTCCCACATTT
CCTTCAAATGCTTTTCTTTTGCAAGATAAGCGTCGACCATCCAAAGAA
>Juct_16199.t1
MRPPLSPRTLLFFTSYSSPLLVKISHFSSSSHYASHSVHPGRRHDEESRNVRVSVWWDFENCNLPSGVNVFKVAH
SITAAVRASGIKGPVTITAFGDVFQLSRAKQEALSSTGINITHIPNGGKNSADRSLLVDLMYWVSQNPPPAHLFL
ISGDRDFASILHRLRMNNYNILLASPESTPGVLCSAASIMWHWPSLIRGETPTGKHFNQPPDGPYGSWYGHSKVP
LEDPFSVTDQSASRAEDLPEPSPDSKPRPVPKIMTKLIRCILNSHPEGISIRELRSKLGNTLNIDRDFYGYKKFS
NLLLSMPHILKLQSERDGQFVVRGITSKSPEPFQSNPALFPEPASNNGVQDFSATSKSNGELGSVAGVVNGKPSL
SPSPESNVKVPPKKIQEPSVTGVMDEKSAVPSSPESNVEEVQQQSPHEEKGVEQVKNRHLPPVVELDSASAVGFL
NRVWRKCFGRIDGGPMNKIQSILEKCSTSGVMSEKKGHETAEYGSTVNGSKMAKAEDKCVNSTSLDAKPICQVPY
SSANNGLAIDSKTATVSEAYGNNSSTGPGFFNQMVHWCKVWRSNPNSYILNDQPRDKLEQNLSKNKVEQNLSKNK
LEQINSRSEKHSLFSMDSFWSDMESFLGTVNGSVIVSQSRNREQMAQNLQKEGPPALRSLSESDVLHLVDLLISE
MKWMEECPSQTSPFKLTRPVGQSSLVQARGSNGLSSIFLGTTLQTAEHGERKYQNIPHTGVSPPAVQKKPSVRSR
SDILADCQKLVNEILKNYPNGFNMGSFRKTFLERHGYPLDLQKLGHQSLVSLLQIMPGVKIVSTQIFPSSEASSS
SGQEIALPDSQENSASHSVPNSDSELSDSTKKNDDFDSPWEELGPVGDTSSTQNEMESVSRKKTIEQTERQKYPD
YEPSISDDDFSDSEGETSLLAGGERHGKRMNEEDSSLVRILDSWYSTKEGDNRKNELENVDGIVDCSTNGSKPSG
SSAIGTGSETCTGNSVRRQRAQKTFSFVADPVEANKDKLIDGILGSLKKSDESRVQG
```

**Comment by almasaeed2010** [comment]
all features have been deleted from the live server. The job is running here: https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/709992

Once the above job completes, @patricksis can re-add the features along with their annotations.

Thanks!

**Comment by patricksis** [comment]
Live:
cds upload:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/719160
Peptides upload:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/719161
Published mRNA:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/719641
Trembl xml loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/719645
Swissprot xml loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/719646
IPS xml loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/719647
KEGG annotation:
https://www.hardwoodgenomics.org/KEGGresults/3012284
KEGG loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/745762

**Comment by CaseyRichards92** [comment]
@patricksis 
- [x] Needs cross reference added
- [x] KEGG issues. I see it was loaded but there are not any KEGG features associated w/ the organism when you search for them on the Live site. https://www.hardwoodgenomics.org/organism/Juglans/cathayensis?search_term=kegg&op=Search&is_es_gene_form=is_es_gene_form&organism=Juglans+cathayensis&tripal_pane=group_feature_search&form_build_id=form-ZPAa4AxugXVYXAa2T1gS-EArB6M35ElgjP0EhDLQldc&form_token=5BxWw40EvW6XfIAhS24lx6Gt4-yEPm0-2rhyj8z2iOg&form_id=tripal_elasticsearch_gene_search_form

**Comment by patricksis** [comment]
Cross references was added. Let's bring up the KEGG issue again at the next meeting. For now this organism should be done, but i'll leave it open until KEGG is resolved.

**Comment by patricksis** [comment]
Yeah you're right @cricha59 there aren't any KEGG records for this organism...weird. Above comment still applies.

**Comment by almasaeed2010** [comment]
Odd issue happening to me when I try to access a feature page. I keep getting logged out when attempting to access an mRNA page for this organism. The issue does not happen on other organisms.

**Comment by patricksis** [comment]
@almasaeed2010 Are you doing a mRNA- polypeptide Search?

**Comment by almasaeed2010** [comment]
I am using the Feature Search on the organism page but I'll try the mrna search

**Comment by patricksis** [comment]
Gotcha. mRNA- polypeptide Search works fine for me. I tried using the features search on the organism's page, and it works fine for me.

**Comment by patricksis** [comment]
KEGG records are showing up know for some reason, maybe it was a cache thing. Closing issue. 
<img width="532" alt="Screen Shot 2019-07-09 at 2 54 57 PM" src="https://user-images.githubusercontent.com/38140425/60915768-ac1f4e80-a25a-11e9-9680-dc0ea0d57766.png">
