### ISSUE TITLE
Juglans microcarpa

### ISSUE THREAD

**Issue by RaymondS1** [statonlab/hardwoods_site#451]
Genome: https://treegenesdb.org/FTP/Genomes/Jumi/

**Comment by almasaeed2010** [comment]
@RaymondS1, please follow this wiki post step by step to add this organism to the staging/dev site. https://github.com/mestato/statonlabprivate/wiki/How-to-create-a-new-organism

**Comment by RaymondS1** [comment]
`/var/www/html/sites/default/files/sequences/texas_walnut/Juglans_microcarpa_cds.fasta`
Pathway to CDS files 

`/var/www/html/sites/default/files/sequences/texas_walnut/Juglan_microcarpa_prot.fasta`
Pathway to Protein files

`/var/www/html/sites/default/files/sequences/texas_walnut/blast/trembl`
Pathway to Trembl 

`/var/www/html/sites/default/files/sequences/texas_walnut/blast/swissprot`
Pathway to Swissprot

**Comment by RaymondS1** [comment]
https://hardwoods.ag.utk.edu/organism/Juglans/microcarpa?tripal_pane=group_summary_tripalpane
link to organism

https://hardwoods.ag.utk.edu/BLAST-annotation/2676687
SwissProt Annotation 

https://hardwoods.ag.utk.edu/BLAST-annotation/2676691
Trembl Annotation

https://hardwoods.ag.utk.edu/KEGGresults/2768041?tripal_pane=group_summary_tripalpane
KEGG Annotation

**Comment by RaymondS1** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502867
CDS Fasta Loaded
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/501407
Polypeptide
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/504018
Kegg Loaded

**Comment by RaymondS1** [comment]
- [x] Upload Trembl 
-  [x] Upload swissprot
- [x] Publish mRNA

**Comment by RaymondS1** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502860
mRNA published 

https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502871
Swissprot uploaded 

https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/503374
Trembl uploaded

**Comment by RaymondS1** [comment]
IPS

```
#PBS -N juglans_microcarpa_ips
#PBS -A ACF-UTK0011
#PBS -S /bin/bash
#PBS -t 1-200
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=10:00:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/interproscan-5.28-67.0/interproscan.sh \
 -i /lustre/haven/gamma/staton/projects/undergrads/texas_walnut/raw_data/IPS_splits/Juglan_microcarpa_prot.fasta.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/gamma/staton/projects/undergrads/texas_walnut/IPS/xml \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/gamma/staton/projects/undergrads/texas_walnut/IPS/TMP \
 >& /lustre/haven/gamma/staton/projects/undergrads/texas_walnut/IPS/TMP/$PBS_ARRAYID.out
```

**Comment by RaymondS1** [comment]
- [x] Transfer Interpro
- [ ] Transfer to live site

**Comment by RaymondS1** [comment]
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502873
Interpro uploaded

**Comment by RaymondS1** [comment]
**Live Site** 

https://hardwoodgenomics.org/organism/Juglans/microcarpa
Link to organism

https://hardwoodgenomics.org/InterProScan-annotation/2586125
Link to Interpro annotation  

https://hardwoodgenomics.org/BLAST-annotation/2509827
Link to SwissProt annotation 

https://hardwoodgenomics.org/BLAST-annotation/2509828
Link to Trembl annotation 

https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/548277
CDS Fasta Upload 

https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/548278
Polypeptide Fasta Upload

https://hardwoodgenomics.org/KEGGresults/2630417
Kegg Annotation

**Comment by RaymondS1** [comment]
**Live Site**
`/var/www/html/sites/default/files/sequences/european_beech/texas_walnut/texas_walnut`
Pathway to files 

`/var/www/html/sites/default/files/sequences/european_beech/texas_walnut/texas_walnut/blast/swissprot`
Swissprot

`/var/www/html/sites/default/files/sequences/european_beech/texas_walnut/texas_walnut/blast/trembl`
Trembl

**Comment by RaymondS1** [comment]
https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/566979
mRNA published

https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/575028
Swissprot Upload 

https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/596353
Trembl Upload

https://hardwoodgenomics.org/admin/tripal/tripal_jobs
Interpro Scan Upload 

https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/620670
Kegg Upload

**Comment by RaymondS1** [comment]
https://hardwoodgenomics.org/organism/Juglans/microcarpa
Link to the finished organism 

https://hardwoodgenomics.org/feature/Jumi_03626.t2?tripal_pane=group_summary_tripalpane
Link to the mRNA page

**Comment by patricksis** [comment]
Could not find gff

**Comment by patricksis** [comment]
@RaymondS1 This organism is good to close, just add cross reference to organism page.
