### ISSUE TITLE
Sweet osmanthus genome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#453]
### Feature description
Yang et al.

The chromosome-level quality genome provides insights into the evolution of the biosynthesis genes for aroma compounds of Osmanthus fragrans

https://www.nature.com/articles/s41438-018-0108-0

**Comment by RaymondS1** [comment]
https://hardwoods.ag.utk.edu/organism/Osmanthus/fragrans
Organism 

https://hardwoods.ag.utk.edu/Publication/2768059?tripal_pane=group_summary_tripalpane
Publication

https://hardwoods.ag.utk.edu/Genome-assembly/2768063
Reference Genome

**Comment by RaymondS1** [comment]
Author Correction to add the accession numbers:
https://www.nature.com/articles/s41438-019-0144-4 

Accession 
PRJNA529305

**Comment by RaymondS1** [comment]
Author does not provide the assembled genome for the plant
