### ISSUE TITLE
New Walnut Genome

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#454]
Here is the file that Annarita Marano sent us. Lets look at the file to determine what of it we can actually do.

[HWG_Jregia_V2.docx](https://github.com/statonlab/hardwoods_site/files/2630635/HWG_Jregia_V2.docx)

**Comment by mestato** [comment]
> Walnut project homepage: https://nealelab.ucdavis.edu/wgmb/

Added to home page to replace treegenes link

**Comment by mestato** [comment]
Updated description of organism to clarify the 3 genome versions now available. pubs and links to analyses added.

**Comment by mestato** [comment]
Link for "fort lauderdale":
https://www.sanger.ac.uk/legal/assets/fortlauderdalereport.pdf

Link for "toronto":
https://www.nature.com/articles/461168a

**Comment by almasaeed2010** [comment]
Downloadable links:

```html
<a href="/sites/default/files/sequences/juglans_regia/persian_walnut_junglans_regia_chrs_sept18.fasta">persian_walnut_junglans_regia_chrs_sept18.fasta</a>

<a href="/sites/default/files/sequences/juglans_regia/persian_walnut_junglans_regia_unanchored_oct9.fasta">persian_walnut_junglans_regia_unanchored_oct9.fasta</a>
```

**Comment by mestato** [comment]
Some more text for the description:
While this is the newest and most complete version of the genome, gene annotation has not yet been completed. <a href="https://www.hardwoodgenomics.org/Genome-assembly/2209485?tripal_pane=group_downloads">Visit the gene features and JBrowse from Version 1 of the reference genome.</a>

**Comment by cricha59** [comment]
@mestato 

Link to the new reference genome V 2.0 
https://www.hardwoodgenomics.org/Genome-assembly/2539069?tripal_pane=group_downloads

Link to Juglans regia
https://www.hardwoodgenomics.org/organism/Juglans/regia?tripal_pane=group_summary_tripalpane

**Comment by mestato** [comment]
links missing, reopening
