### ISSUE TITLE
NCBI Taxon link needs to go to correct NCBI page

### ISSUE THREAD

**Issue by cricha59** [statonlab/hardwoods_site#455]
This issue can be found on most organisms under the cross reference section. Link does not take you to the appropriate page.

**Comment by almasaeed2010** [comment]
@bradfordcondon's suggestion: 
> redirect to `https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id={accession}`

**Comment by almasaeed2010** [comment]
@cricha59 this has been fixed on the live site. Could you please test and close this issue if it works for you?

**Comment by cricha59** [comment]
@almasaeed2010  I have checked and it works
