### ISSUE TITLE
quercus ilex drought transcriptome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#459]
https://apsjournals.apsnet.org/doi/pdfplus/10.1094/PBIOMES-04-18-0021-R

**Comment by mestato** [comment]
Huh, looks like theres anohter quercus ilex with other stresses too:
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-018-5260-2

Could do a combined analysis?

**Comment by RaymondS1** [comment]
> https://apsjournals.apsnet.org/doi/pdfplus/10.1094/PBIOMES-04-18-0021-R

@mestato the first article is about populus deltoides

**Comment by mestato** [comment]
Hmm, I don't know what that was. Lets just focus on the second article.

**Comment by RaymondS1** [comment]
@mestato There is no SRA associated with the accession (PRJNA490658) in the 2nd article

**Comment by RaymondS1** [comment]
not available at the accession number
