### ISSUE TITLE
Pterocarya stenoptera Genome

### ISSUE THREAD

**Issue by cricha59** [statonlab/hardwoods_site#462]
P. stenoptera: https://treegenesdb.org/FTP/Genomes/Ptst/

**Comment by CaseyRichards92** [comment]
### AG Site ###
FASTA CDS loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502365
FASTA PROTEIN loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502369
Published mRNA -polypeptide https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502370
SwissProt Annotation https://hardwoods.ag.utk.edu/BLAST-annotation/2676692
TrEMBL Annotation https://hardwoods.ag.utk.edu/BLAST-annotation/2676693
IPS Annotation https://hardwoods.ag.utk.edu/InterProScan-annotation/2676695
KEGG Annotation https://hardwoods.ag.utk.edu/KEGGresults/2680061
KEGG job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502569
BLAST SwissProt job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502660
IPS Job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/502665

**Comment by CaseyRichards92** [comment]
SwissProt
```#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=03:30:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/splits_cds/Ptst.1_0.cds.fa.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/blast/swissprot/pterocarya_stenoptera_swissprot_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
TrEMBL 1-200
```#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=12:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/splits_cds_trembl/Ptst.1_0.cds.fa.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/blast/trembl/pterocarya_stenoptera_trembl_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
TrEMBL 201-400
```#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 201-400
#PBS -l nodes=1:ppn=2
#PBS -l walltime=12:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/splits_cds_trembl/Ptst.1_0.cds.fa.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/blast/trembl/pterocarya_stenoptera_trembl_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
IPS
```#PBS -S /bin/bash
#PBS -t 1-200
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=3:30:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/interproscan-5.28-67.0/interproscan.sh \
 -i /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/splits_peptides/Ptst.1_0.peptides.fa.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/ips \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/ips/tmp \
 > /lustre/haven/gamma/staton/projects/undergrads/pterocarya_stenoptera/ips/tmp/$PBS_ARRAYID.out
```

**Comment by CaseyRichards92** [comment]
## Live site ##
FASTA CDS Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/540247
FASTA Protein Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/540251
Published mRNA polypeptides https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/540252
SwissProt Annotation https://www.hardwoodgenomics.org/BLAST-annotation/2539074
TrEMBL Annotation https://www.hardwoodgenomics.org/BLAST-annotation/2539075
IPS Annotation https://www.hardwoodgenomics.org/InterProScan-annotation/2539076

**Comment by CaseyRichards92** [comment]
### Live Site ###
Swissprot job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/575033
IPS Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/575038
KEGG Annotation created https://www.hardwoodgenomics.org/KEGGresults/2630416
KEGG Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/575039
Downloads added for CDS and peptide files added https://www.hardwoodgenomics.org/Genome-assembly/2209433
TrEMBL Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/579303
BLAST db for CDS https://www.hardwoodgenomics.org/content/pterocarya-stenoptera-transcripts
BLAST db for protein https://www.hardwoodgenomics.org/content/pterocarya-stenoptera-peptides

**Comment by CaseyRichards92** [comment]
Could not transfer all of the xml files for trembl to Hardwoods server due to "No space left on device"

**Comment by CaseyRichards92** [comment]
Re running xmls 133-134 for trembl as they are the only ones that failed.

**Comment by MattHuff** [comment]
Trembl job on live site with added 133 and 134 files [https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/598798](https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/598798)

**Comment by patricksis** [comment]
No gff file found.

**Comment by patricksis** [comment]
@cricha59 No cross reference added. Other than that, I think this organism looks good.
