### ISSUE TITLE
Liriodendron chinense reference genome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#466]
### Publication and Data Information
https://www.nature.com/articles/s41477-018-0323-6

### Checklist
See [New Genome Documentation](https://github.com/mestato/statonlabprivate/wiki/How-to-load-a-new-organism-and-genome) for detailed instructions.
- [x] Create Organism
- [x] Create Publication
- [x] Create Reference Genome
- [x] Create InterProScan Annotation
- [x] Create BLAST Annotation
- [x] Run Chado FASTA Loader for CDS
- [x] Run Chado FASTA Loader for Polypeptides
- [x] Publish Tripal content
- [x] Create KEGG Annotation
- [x] Run Chado KEGG Loader
- [x] Run Chado BLAST XML results loader
- [x] Run Chado InterProScan XML results loader
- [x] Create Blast Database

**Comment by CaseyRichards92** [comment]
## AG SITE ##
Organism created https://hardwoods.ag.utk.edu/organism/Liriodendron/chinense
Publication created https://hardwoods.ag.utk.edu/Publication/2768043
Reference Genome w/ publication https://hardwoods.ag.utk.edu/Genome-assembly/2768044?tripal_pane=group_summary_tripalpane
IPS Annotation https://hardwoods.ag.utk.edu/InterProScan-annotation/2768045
BLAST Swissprot Annotation https://hardwoods.ag.utk.edu/BLAST-annotation/2768046
BLAST TrEMBL Annotation https://hardwoods.ag.utk.edu/BLAST-annotation/2768047
KEGG Annotation https://hardwoods.ag.utk.edu/KEGGresults/2768048
CDS FASTA Job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/504595
Peptides FASTA Job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/504596
Published Peptides https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/504597
BLAST Swiss-prot job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/504847
BLAST TrEMBL job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/504848
BLAST db CDS https://hardwoods.ag.utk.edu/content/liriodendron-chinese-transcripts
BLAST db PEPTIDES https://hardwoods.ag.utk.edu/content/liriodendron-chinese-peptides
JBrowse https://hardwoods.ag.utk.edu/admin/tripal/extension/tripal_jbrowse/management/instances/8

**Comment by CaseyRichards92** [comment]
@mestato We cannot seem to find the .cds or the .peptides files for this organism with the accession number provided in the article. I have looked on NCBI and EBI and was only able to find the GFF and FNA files. Any help would be great.

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/013/855/GCA_003013855.2_NJFU_Lchi_2.0/

**Comment by mestato** [comment]
I sent a message to the first and last author. For a template for future use/update, here's what I sent:

> I enjoyed reading your recent paper on the Liriodendron genome. I am able to find the genome on NCBI but not able to find any gene annotation. Would you be willing to share the gene annotation as fasta and gff (or gtf) files? 
> 
> I run the hardwood genomics website (https://hardwoodgenomics.org/), a web portal to provide open access tools for exploring tree genomes and transcriptomes. I would like to include the Liriodendron genome. I would provide links to your paper and any other sites you request to make sure you receive credit for this work. This would be a great addition, as we already have a Liriodendron tulipifera transcriptome available at the site, and researchers interested in this genus could do some comparative genomics.
> 
> By providing the gene information, we would be able to make the genes available on the site for BLAST, functional annotation searching, GO term searching, and browseable through JBrowse. If you have any additional tracks or information we could host (repeat annotations, SNPs, etc), we would be happy to have those as well, and to give you credit for the work and link to your papers.
> 
> 
> Thanks,
> Meg Staton
> Assistant Professor
> University of Tennessee, Institute of Agriculture

**Comment by CaseyRichards92** [comment]
Use this link for appropriate downloadable files (cds, peptide, gff, and fasta)
https://pan.genomics.cn/ucdisk/s/QjABju

**Comment by CaseyRichards92** [comment]
Swissprot
```
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/liriodendron_chinense/splits_cds/Final.cds.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/liriodendron_chinense/blast/swissprot/liriodendron_chinense_swissprot_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
TrEMBL
```
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=15:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/liriodendron_chinense/splits_cds/Final.cds.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/liriodendron_chinense/blast/trembl/liriodendron_chinense_trembl_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
IPS
```
#PBS -A ACF-UTK0011
#PBS -S /bin/bash
#PBS -t 1-200
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=3:30:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/interproscan-5.28-67.0/interproscan.sh \
 -i /lustre/haven/gamma/staton/projects/undergrads/liriodendron_chinense/splits_peptides/Final.pep.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/gamma/staton/projects/undergrads/liriodendron_chinense/blast/ips \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/gamma/staton/projects/undergrads/liriodendron_chinense/blast/ips/tmp \
 > /lustre/haven/gamma/staton/projects/undergrads/liriodendron_chinense/blast/ips/tmp/$PBS_ARRAYID.out
```

**Comment by CaseyRichards92** [comment]
## LIVE SITE ##
Organism created https://www.hardwoodgenomics.org/organism/Liriodendron/chinense
Publication created https://www.hardwoodgenomics.org/Publication/2630419
Reference Genome w/ publication w/ downloads https://www.hardwoodgenomics.org/Genome-assembly/2630420
IPS Annotation https://www.hardwoodgenomics.org/InterProScan-annotation/2630421
BLAST Swissprot Annotation https://www.hardwoodgenomics.org/BLAST-annotation/2630422
BLAST TrEMBL Annotation https://www.hardwoodgenomics.org/BLAST-annotation/2630423
KEGG Annotation https://www.hardwoodgenomics.org/KEGGresults/2630424
CDS FASTA Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/606934
Peptides FASTA Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/606938
Published Peptides https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/606939
BLAST Swiss-prot job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/606940
BLAST TrEMBL https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/606941
BLAST db CDS https://www.hardwoodgenomics.org/content/liriodendron-chinese-transcripts
BLAST db PEPTIDES https://www.hardwoodgenomics.org/content/liriodendron-chinese-peptides
KEGG Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/608492
IPS Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/608491
JBrowse

**Comment by mestato** [comment]
- [x] From annotations pane, the KEGG should link out
- [x] since we have kegg and go terms, we need the xray pane on the L. chinense organism page
- [x] dbxref for the analysis should link to ncbi record

**Comment by CaseyRichards92** [comment]
@almasaeed2010 as discussed, could you fix KEGG so it links out from the annotations page.

**Comment by CaseyRichards92** [comment]
@almasaeed2010 Cross Reference will not save when accesion # is placed into the space. Error recieved 
![image](https://user-images.githubusercontent.com/43444146/51768109-5c363c00-20ad-11e9-93f4-b9961ee09a36.png)

**Comment by bradfordcondon** [comment]
can you show us what you tried to put for the cross reference field?
(when filling out the form?)

**Comment by almasaeed2010** [comment]
I think he had NCBTaxon and simply a number in the accession field. He also tried BioProject which failed with a similar error.

**Comment by CaseyRichards92** [comment]
@bradfordcondon I did NCBITaxon and NCBI BioProjet with the accession number and neither worked.

So NCBI Taxon w/ accession # 418360 and NCBI Bio Project w/ accession # 418360

I also tried putting PRJNA418360 which didnt work either

**Comment by bradfordcondon** [comment]
when trying to do so on dev:

![screen shot 2019-01-28 at 8 45 03 am](https://user-images.githubusercontent.com/7063154/51840103-29708b80-22d9-11e9-8730-3a37688fd422.png)


```
Could not save the TripalEntity: SQLSTATE[42703]: Undefined column: 7 ERROR: column "featuremap_id" of relation "organism" does not exist LINE 1: ...organism_id = '66', abbreviation = 'C. papaya', featuremap... ^

```

this is the Tripal Map module.

Your error might be different.  im going to create a seperate issue to resolve.

**Comment by bradfordcondon** [comment]
this should be resolved on both live and dev (#484 ) please try again @cricha59

**Comment by almasaeed2010** [comment]
I believe all of Meg's concerns have been addressed 👍

**Comment by CaseyRichards92** [comment]
@bradfordcondon It works! Thank you for the help.

**Comment by patricksis** [comment]
Jbrowse added:
https://www.hardwoodgenomics.org/admin/tripal/extension/tripal_jbrowse/management/instances/9

**Comment by patricksis** [comment]
gff track is not showing up for Jbrowse

**Comment by patricksis** [comment]
@cricha59 This organism looks good, I'm going to go ahead and close it for you.
