### ISSUE TITLE
microsatellite viewer is a mess on live

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#467]
### Bug description
see:
https://www.hardwoodgenomics.org/bio_data/1072255?tripal_pane=group_summary_tripalpane

the microsatellite field is looking horrible on live attached ot mRNA. 

![screen shot 2019-01-04 at 5 39 24 pm](https://user-images.githubusercontent.com/7063154/50714675-bceecd80-1047-11e9-930b-7a592d701f5b.png)

looks like the columns need to wrap, and they dont.

**Comment by almasaeed2010** [comment]
<img width="898" alt="screen shot 2019-01-07 at 2 14 51 pm" src="https://user-images.githubusercontent.com/1512664/50788185-a2eefe00-1286-11e9-9e25-a1de7dbab64f.png">
This is what it would look like if we allow it to wrap. A little better but still a mess. My opinion is to find a way to make the table smaller. E,g: 



|Key|Value|
|---|-----|
|Name|Gene21|
|Unique Name| Gene21.m|
|Motif|test|

**Comment by bradfordcondon** [comment]
yeah agreed that would look a lot better.

We can also probably get away with only displaying the name and not the uniquename.

**Comment by almasaeed2010** [comment]
Issue fixed on live. PR can be merged once approved.
