### ISSUE TITLE
Add analysis origin to feature summary

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#472]
### Feature description
If you are looking at a feature page, from the summary pane, you should be able to find out where this feature came from (and click through to it). in the case of a reference genome or a reference transcriptome or other.

**Comment by bradfordcondon** [comment]
simple field. for the analysisfeature table, IMO would be happy in core.  Need to make sure that both the GFF loader and the FASTA loaders are linking the feature to the analysis.

Alternatively extend the manage_analyses fields to also attach to feature.

**Comment by almasaeed2010** [comment]
What does it mean when you have more analysisfeature records than features?

```sql
hardwoods_06112018=# select count(*) from chado.analysisfeature;
  count  
---------
 8,290,278
(1 row)

hardwoods_06112018=# select count(*) from chado.feature;
  count  
---------
 3,397,394
(1 row)
```

Are those "orphaned" links?

**Comment by almasaeed2010** [comment]
Ok sorry I get it.

```sql
select count(*) from chado.analysisfeature af left join chado.feature f on f.feature_id = af.feature_id where af.feature_id is null;
 count 
-------
     0
(1 row)
```
This means that all features actually exist.

I guess this is linking the same features to multiple analyses which is what we want.


Then yeah, this is a simple field that we can easily PR to core.

**Comment by almasaeed2010** [comment]
Added live in summary table.
 
**Example feature** https://hardwoodgenomics.org/bio_data/1830155

@mestato please let me know if you'd like to change location of the field, add more info etc.

**Comment by mestato** [comment]
Looks good, lets go with it

**Comment by almasaeed2010** [comment]
Done.
