### ISSUE TITLE
XRay ontology explorer from/for an analysis?

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#473]
### Feature description
As a user if I was looking at a reference genome or a reference transcriptome, I might want to explore the GO terms or the KEGG terms for the features derived from that analysis (genes or mRNA-polypeptides). However, you have to know to go back to the organism page to do this, which isn't very intuitive and might make it difficult to discover. Two possible solutions:
- make a link on the analysis page to the XRay pane on the organism page
- make an XRay pane on the analysis page (would it be terribly slow to load XRay using features limited by analysis instead of organism?)

**Comment by almasaeed2010** [comment]
Both options are feasible. XRay already limits by analysis which means the code to get annotations from an analysis instead of organism is already there and would just need a little tweaking to work.

**Comment by almasaeed2010** [comment]
Done on live.

**Example analysis**: https://hardwoodgenomics.org/Genome-assembly/2243625 
Look for ontology browser in the summary table.

@mestato does this suffice?

**Comment by mestato** [comment]
Yes. Lets change to "Gene Ontology" instead of just ontology and also add a KEGG link

**Comment by almasaeed2010** [comment]
done
