### ISSUE TITLE
Missing data for organisms

### ISSUE THREAD

**Issue by CaseyRichards92** [statonlab/hardwoods_site#474]
FASTA files can be found at:
/files/files/automated_annotation/gene.fasta
/files/files/automated_annotation/mRNA.fasta
/files/files/automated_annotation/polypeptide.fasta

Castanea crenata (Japanese Chestnut):
- [x] BLAST UNIPROT/TREMBL is missing
- [x] BLAST Swiss-Prot is missing
- [x] INTERPRO annotations are missing
- [x] KEGG annotations are missing
- [x] GO annotations are missing

Castanea sativa (European Chestnut):
- [x] BLAST UNIPROT/TREMBL is missing
- [x] BLAST Swiss-Prot is missing
- [x] INTERPRO annotations are missing
- [x] KEGG annotations are missing
- [x] GO annotations are missing

Fagus sylvatica (European Beech):
- [x] KEGG annotations are missing

Fraxinus americana (White Ash):
- [ ] BLAST UNIPROT/TREMBL is missing
- [ ] BLAST Swiss-Prot is missing
- [ ] INTERPRO annotations are missing
- [ ] KEGG annotations are missing
- [ ] GO annotations are missing

Fraxinus pennsylvanica (Green Ash):
- [ ] BLAST Swiss-Prot is missing

Handroanthus impetiginosus (Pink Ipe):
- [x] BLAST Swiss-Prot is missing (Casey)

Juglans cathayensis (Chinese Walnut):
- [x] BLAST UNIPROT/TREMBL is missing
- [x] BLAST Swiss-Prot is missing
- [x] INTERPRO annotations are missing
- [ ] KEGG annotations are missing
- [ ] GO annotations are missing

Juglans microcarpa (Texas walnut ):
- [x] BLAST UNIPROT/TREMBL is missing
- [x] BLAST Swiss-Prot is missing
- [x] INTERPRO annotations are missing
- [x] KEGG annotations are missing
- [ ] GO annotations are missing

Juglans regia (English Walnut):
- [ ] KEGG annotations are missing

Morus notabilis (Mulberry):
- [ ] KEGG annotations are missing

Olea europaea (Olive Tree):
- [x] BLAST UNIPROT/TREMBL is missing
- [x] BLAST Swiss-Prot is missing
- [x] INTERPRO annotations are missing
- [ ] KEGG annotations are missing
- [x] GO annotations are missing

Persea borbonia (Redbay):
- [ ] BLAST UNIPROT/TREMBL is missing
- [ ] BLAST Swiss-Prot is missing
- [ ] INTERPRO annotations are missing
- [ ] KEGG annotations are missing
- [ ] GO annotations are missing

Populus deltoides (Eastern Cottonwood):
- [ ] BLAST UNIPROT/TREMBL is missing

Populus trichocarpa (Poplar):
- [ ] BLAST UNIPROT/TREMBL is missing
- [ ] BLAST Swiss-Prot is missing

Punica granatum (pomegranate):
- [ ] KEGG annotations are missing

Quercus lobata (Valley Oak):
- [ ] BLAST UNIPROT/TREMBL is missing

Quercus robur (Pedunculate Oak):
- [x] KEGG annotations are missing

**Comment by almasaeed2010** [comment]
Is this issue related to either of these issues #483 or #470 ?

**Comment by CaseyRichards92** [comment]
@almasaeed2010 I think this issue was organisms that were never completely finished. I will look at each one and see what is actually missing and isnt

**Comment by almasaeed2010** [comment]
I don't think this is up to date. Instead of tracking info here, let's record progress for each organism in its own issue.

Thanks!
