### ISSUE TITLE
Macadamia integrifolia genome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#475]
### Publication and Data Information
https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-3272-3

### Checklist
See [New Genome Documentation](https://github.com/mestato/statonlabprivate/wiki/How-to-load-a-new-organism-and-genome) for detailed instructions.
- [x] Create Organism
- [x] Create Publication
- [x] Create Reference Genome
- [x] Create InterProScan Annotation
- [x] Create BLAST Annotation
- [x] Run Chado FASTA Loader for CDS
- [x] Run Chado FASTA Loader for Polypeptides
- [x] Publish Tripal content
- [x] Create KEGG Annotation
- [x] Run Chado KEGG Loader
- [x] Run Chado BLAST XML results loader
- [x] Run Chado InterProScan XML results loader
- [x] Create Blast Database
- [x] JBrowse

**Comment by CaseyRichards92** [comment]
## Ag Site ##
Organism created https://hardwoods.ag.utk.edu/organism/Macadamia/integrifolia?tripal_pane=group_summary_tripalpane
Publication https://hardwoods.ag.utk.edu/Publication/2803356?tripal_pane=group_summary_tripalpane
Reference Genome https://hardwoods.ag.utk.edu/Genome-assembly/2803357?tripal_pane=group_downloads
IPS Annotation https://hardwoods.ag.utk.edu/InterProScan-annotation/2803358
Swissprot Annotation https://hardwoods.ag.utk.edu/BLAST-annotation/2803359
TrEMBL Annotation https://hardwoods.ag.utk.edu/BLAST-annotation/2803360
KEGG Annotation https://hardwoods.ag.utk.edu/KEGGresults/2803361
CDS FASTA LOADER https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/506404
Protein FASTA LOADER https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/506405
Published mRNA https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/506406
KEGG loader https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/506413
Swissprot job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/506466
IPS Job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/506467
BLAST DB CDS https://hardwoods.ag.utk.edu/content/macadamia-integrifolia-transcripts
BLAST DB PEPTIDES https://hardwoods.ag.utk.edu/content/macadamia-integrifolia-peptides
JBROWSE https://hardwoods.ag.utk.edu/tools/jbrowse/?data=data%2Fmacadamia_integrifolia__macadamia_nut%2Fdata&tracks=DNA&loc=UZVR01000001.1%3A330230..330286&highlight=
TrEMBL Job https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/506616

**Comment by CaseyRichards92** [comment]
@mestato cannot find cds or protein files for this organism
NCBI https://www.ncbi.nlm.nih.gov/genome/?term=PRJEB13765
EBI https://www.ebi.ac.uk/ena/data/view/GCA_900087525
NCBI Downloads ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/900/631/585/GCA_900631585.1_Macadamia_Integrifolia_v2/

**Comment by CaseyRichards92** [comment]
@MattHuff Looking to convert gff to cds file using bedtools.

**Comment by MattHuff** [comment]
The GFF file available on the NCBI ftp page does not contain any information on what parts are CDS regions:

```
##sequence-region UZVR01000066.1 1 260536
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=60698
UZVR01000066.1  EMBL    region  1       260536  .       +       .       ID=id1234;Dbxref=taxon:60698;gbkey=Src;mol_type=genomic DNA;note=contig: scaffold_66
##sequence-region UZVR01000199.1 1 565291
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=60698
UZVR01000199.1  EMBL    region  1       565291  .       +       .       ID=id1235;Dbxref=taxon:60698;gbkey=Src;mol_type=genomic DNA;note=contig: scaffold_199
##sequence-region UZVR01001950.1 1 189075
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=60698
UZVR01001950.1  EMBL    region  1       189075  .       +       .       ID=id1236;Dbxref=taxon:60698;gbkey=Src;mol_type=genomic DNA;note=contig: scaffold2089
```

**Comment by MattHuff** [comment]
@mestato email the authors of this paper to see if they will provide us the annotation for Macademia.

**Comment by mestato** [comment]
Email sent to Cathy Nock:
I enjoyed reading your recent paper on the Macadamia genome in BMC Genomics. I am able to find the genome on EMBL but not able to find any gene annotation. Would you be willing to share the gene annotation as fasta and gff (or gtf) files?

I run the hardwood genomics website (https://hardwoodgenomics.org/), a web portal to provide open access tools for exploring tree genomes and transcriptomes. I would like to include the Macadamia genome. I would provide links to your paper and any other sites you request to make sure you receive credit for this work.

By providing the gene information, we would be able to make the genes available on the site for BLAST, functional annotation searching, GO term searching, and browseable through JBrowse. If you have any additional tracks or information we could host (repeat annotations, SNPs, etc), we would be happy to have those as well, and to give you credit for the work and link to your papers.

Thanks,
Meg Staton

**Comment by mestato** [comment]
Response from Cathy (a gold star author that responded to my 10pm email at 11pm!):
Thanks for your email and for your interest. We hope to publish an improved version of the M. integrifolia cultivar 741 genome later this year. In the meantime, some of the requested information for the v1 assembly (Nock et al. 2016) is available at https://cloudstor.aarnet.edu.au/plus/s/VjgtrU5iBVafNfz

Files look to be available through the link.

Lets remember to shoot her an email when the genome is live and get her feedback.

/remind me in a month to check on this and email cathy

**Comment by CaseyRichards92** [comment]
Swissprot
```
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/macadamia_integrifolia/splits_cds/maca.v1.1_transcripts.fasta.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/macadamia_integrifolia/blast/swissprot/macadamia_integrifolia_swissprot_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
TrEMBL 
```
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=15:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/macadamia_integrifolia/splits_cds/maca.v1.1_transcripts.fasta.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/macadamia_integrifolia/blast/trembl/macadamia_integrifolia_trembl_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
IPS
```
#PBS -A ACF-UTK0011
#PBS -S /bin/bash
#PBS -t 1-200
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=3:30:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/interproscan-5.28-67.0/interproscan.sh \
 -i /lustre/haven/gamma/staton/projects/undergrads/macadamia_integrifolia/splits_peptides/maca.v1.1_proteins.fasta.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/gamma/staton/projects/undergrads/macadamia_integrifolia/blast/ips \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/gamma/staton/projects/undergrads/macadamia_integrifolia/blast/ips/tmp \
 > /lustre/haven/gamma/staton/projects/undergrads/macadamia_integrifolia/blast/ips/tmp/$PBS_ARRAYID.out
```

**Comment by CaseyRichards92** [comment]
## Live Site ##
Organism created https://www.hardwoodgenomics.org/organism/Macadamia/integrifolia
Publication https://www.hardwoodgenomics.org/Publication/2702058
Reference Genome https://www.hardwoodgenomics.org/Genome-assembly/2702059
IPS Annotation https://www.hardwoodgenomics.org/InterProScan-annotation/2702060
Swissprot Annotation https://www.hardwoodgenomics.org/BLAST-annotation/2702061
TrEMBL Annotation https://www.hardwoodgenomics.org/BLAST-annotation/2702062
KEGG Annotation https://www.hardwoodgenomics.org/KEGGresults/2702063
CDS FASTA LOADER https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/655139
Protein FASTA LOADER https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/655140
Published mRNA https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/655141
KEGG loader https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/655142
Swissprot job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/655143
Trembl job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/655144
IPS Job https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/655156
BLAST DB CDS https://www.hardwoodgenomics.org/content/macadamia-integrifolia-transcripts
BLAST DB PEPTIDES https://www.hardwoodgenomics.org/content/macadamia-integrifolia-peptides
JBrowse

**Comment by CaseyRichards92** [comment]
@mestato  refer to reminder from above

**Comment by patricksis** [comment]
@almasaeed2010 I got this error message when trying to upload the gff file 
```The file /var/www/html/sites/default/files/sequences/macadamia_integrifolia/maca.v1.1.gff could not be copied because a file by that name already exists in the destination directory.```
```Failed to copy file /var/www/html/sites/default/files/sequences/macadamia_integrifolia/maca.v1.1.gff to /data2/apollo/apache/macadamia_integrifolia__macadamia_nut/data```

**Comment by almasaeed2010** [comment]
I deleted the duplicate file. Please try again

**Comment by patricksis** [comment]
Worked thanks, sadly I got a lot of errors when uploading it. We may have to wait on this one. 
I'm just going to past them all for reference.

**Comment by patricksis** [comment]
```FF3 parse error: some features reference other features that do not exist in the file (or in the same '###' scope).  A list of them:
 ID                 |           Cannot Find
----------------------------------------------------------------------
Maca028446-RA|size3 | Parent=Maca028446-RA|size3701-augustus-gene-0
Maca028446-RA|size3 | Parent=Maca028446-RA|size3701-augustus-gene-0
Maca028446-RA|size3 | Parent=Maca028446-RA|size3701-augustus-gene-0
Maca028446-RA|size3 | Parent=Maca028446-RA|size3701-augustus-gene-0
Maca028446-RA|size3 | Parent=Maca028446-RA|size3701-augustus-gene-0
Maca028446-RA|size3 | Parent=Maca028446-RA|size3701-augustus-gene-0
Maca028446-RA|size3 | Parent=Maca028446-RA|size3701-augustus-gene-0
 at /var/www/html/tools/jbrowse/bin/../src/perl5/Bio/JBrowse/ConfigurationManager.pm line 7, <$f> line 10.
	Bio::JBrowse::ConfigurationManager::__ANON__('\x{a}GFF3 parse error: some features reference other features tha...') called at /var/www/html/tools/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/Bio/GFF3/LowLevel/Parser.pm line 195
	Bio::GFF3::LowLevel::Parser::_buffer_all_under_construction_features('Bio::GFF3::LowLevel::Parser=HASH(0x1575b58)') called at /var/www/html/tools/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/Bio/GFF3/LowLevel/Parser.pm line 111
	Bio::GFF3::LowLevel::Parser::_buffer_items('Bio::GFF3::LowLevel::Parser=HASH(0x1575b58)') called at /var/www/html/tools/jbrowse/bin/../src/perl5/../../extlib/lib/perl5/Bio/GFF3/LowLevel/Parser.pm line 73
	Bio::GFF3::LowLevel::Parser::next_item('Bio::GFF3::LowLevel::Parser=HASH(0x1575b58)') called at /var/www/html/tools/jbrowse/bin/../src/perl5/Bio/JBrowse/FeatureStream/GFF3_LowLevel.pm line 15
	Bio::JBrowse::FeatureStream::GFF3_LowLevel::next_items('Bio::JBrowse::FeatureStream::GFF3_LowLevel=HASH(0x159a520)') called at /var/www/html/tools/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/NCFormatter.pm line 52
	Bio::JBrowse::Cmd::NCFormatter::_format('Bio::JBrowse::Cmd::FlatFileToJson=HASH(0xc8fb70)', 'trackConfig', 'HASH(0x145a790)', 'featureStream', 'Bio::JBrowse::FeatureStream::GFF3_LowLevel=HASH(0x159a520)', 'featureFilter', 'CODE(0x1467e68)', 'trackLabel', 'macadamia_nut', ...) called at /var/www/html/tools/jbrowse/bin/../src/perl5/Bio/JBrowse/Cmd/FlatFileToJson.pm line 128
	Bio::JBrowse::Cmd::FlatFileToJson::run('Bio::JBrowse::Cmd::FlatFileToJson=HASH(0xc8fb70)') called at /var/www/html/tools/jbrowse/bin/flatfile-to-json.pl line 9
Job execution failed: Unable to add track. See errors above.             [error]```

**Comment by almasaeed2010** [comment]
Are you sure you chose the correct gff? I think I saw a few there

**Comment by almasaeed2010** [comment]
try using this one for good measure GCA_900631585.1_Macadamia_Integrifolia_v2_genomic.gff

**Comment by patricksis** [comment]
That one doesn't have the genes in it, we're trying to use the ones the author provided above.

**Comment by patricksis** [comment]
One sec, we might of figured it out

**Comment by patricksis** [comment]
So I had to copy the file into one of my directories to edit it, but I'm not getting the same error again, would mind deleting the duplicate file again? @almasaeed2010 
```The file /var/www/html/sites/default/files/sequences/vernicia_fordii/maca.v1.1.gff could not be copied because a file by that name already exists in the destination directory.```
```Failed to copy file /var/www/html/sites/default/files/sequences/vernicia_fordii/maca.v1.1.gff to /data2/apollo/apache/macadamia_integrifolia__macadamia_nut/data```

**Comment by almasaeed2010** [comment]
done

**Comment by patricksis** [comment]
Okay thanks, got the same error again, Dr. Staton told me to slack her if it happened again. So I'm just going to move on to the next organism.

**Comment by patricksis** [comment]
```The file /var/www/html/sites/default/files/sequences/macadamia_integrifolia/maca.v1.1.gff.fixed could not be copied because a file by that name already exists in the destination directory.
Failed to copy file /var/www/html/sites/default/files/sequences/macadamia_integrifolia/maca.v1.1.gff.fixed to /data2/apollo/apache/macadamia_integrifolia__macadamia_nut/data```

**Comment by mestato** [comment]
Note on how to fix the AWFUL gff file:
1. Wrote a python script to fix all the names of all the features in the gff, fix_gff.py, in directory with gf f file.
2. Also need to change |size to -size using a regular expression (to make gff scaffold names match the scaffold names in maca.v1.1_scaffolds.fasta.

**Comment by patricksis** [comment]
gff track is still not showing up on Jbrowse.

**Comment by mestato** [comment]
Suggestions to troubleshoot:
- Clear the cache for your browser
- Do the scaffold names from the fasta file match the scaffold names in the gff file?
- Are the track files in the expected location in the jbrowse folders? Does the data in those files match the scaffold fasta file and gff file you uploaded?
- Is the track listed in the .conf file for the organism? Does it look to be formatted correctly?
- Check Apache error log (see @almasaeed2010)
- Try adding the track manually instead of via Tripal module (if this works, tell abdullah so he can troubleshoot module)
- Try to redo the Jbrowse instance completely.

**Comment by patricksis** [comment]
@mestato. @almasaeed2010 and I tried all of your suggestions, but none of them worked

**Comment by almasaeed2010** [comment]
Redo with dashes instead of pipes

**Comment by patricksis** [comment]
Edited the file, would you mind deleted the instance @almasaeed2010 ?

**Comment by almasaeed2010** [comment]
I deleted it. I also added code to the module to auto delete these directories. From now on, we shouldn't need to delete the instance manually anymore.

**Comment by patricksis** [comment]
Jbrowse finally works!
https://www.hardwoodgenomics.org/admin/tripal/extension/tripal_jbrowse/management/instances/19

**Comment by patricksis** [comment]
@cricha59 
This organism looks good, I think you're okay to close it.
