### ISSUE TITLE
Pecan (Carya illinoinensis) transcriptome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#477]
### Publication and Data Information

There are tons of different transcriptome papers:

- https://pubs.acs.org/doi/abs/10.1021/acs.jafc.7b00922
- https://pubs.acs.org/doi/abs/10.1021/acs.jafc.6b04199
- https://pubs.acs.org/doi/abs/10.1021/acs.jafc.8b05239
- https://www.researchgate.net/profile/Ming_Zhi_Li/publication/325795857_Transcriptome_survey_reveals_candidate_genes_involved_in_lipid_metabolism_of_Carya_illinoinensis/links/5b2909e24585150c63dccaff/Transcriptome-survey-reveals-candidate-genes-involved-in-lipid-metabolism-of-Carya-illinoinensis.pdf
- https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0195913
- https://www.mdpi.com/2073-4425/9/2/71
- https://link.springer.com/article/10.1134/S1021443718020139

Instead of trying to use all of these, I think the best approach is to find all the public RNASeq libraries in NCBI, then assemble one massive reference transcriptome. But we'll need to figure out which libraries are associated with which pubs so proper attribution to original authors can be given.

### Checklist
See [New Genome Documentation](https://github.com/mestato/statonlabprivate/wiki/How-to-load-a-new-organism-and-genome) for detailed instructions.
- [ ] Create Organism
- [ ] Create Publication
- [ ] Create Reference Genome
- [ ] Create InterProScan Annotation
- [ ] Create BLAST Annotation
- [ ] Run Chado FASTA Loader for CDS
- [ ] Run Chado FASTA Loader for Polypeptides
- [ ] Publish Tripal content
- [ ] Create KEGG Annotation
- [ ] Run Chado KEGG Loader
- [ ] Run Chado BLAST XML results loader
- [ ] Run Chado InterProScan XML results loader
- [ ] Create Blast Database

**Comment by CaseyRichards92** [comment]
- https://pubs.acs.org/doi/abs/10.1021/acs.jafc.7b00922 - No accession number.
- https://pubs.acs.org/doi/abs/10.1021/acs.jafc.6b04199 - No accession number.
- https://pubs.acs.org/doi/abs/10.1021/acs.jafc.8b05239 - PRJNA504494 w/ SRA data
- https://www.researchgate.net/profile/Ming_Zhi_Li/publication/325795857_Transcriptome_survey_reveals_candidate_genes_involved_in_lipid_metabolism_of_Carya_illinoinensis/links/5b2909e24585150c63dccaff/Transcriptome-survey-reveals-candidate-genes-involved-in-lipid-metabolism-of-Carya-illinoinensis.pdf - PRJNA347430 w/o analysis
- https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0195913 - PRJNA431045 w/ no public data

- https://www.mdpi.com/2073-4425/9/2/71 - SRA) with the accession number SRP118757
- https://link.springer.com/article/10.1134/S1021443718020139 - PRJNA342905 w/ RNA-seq data

**Comment by mestato** [comment]
Sorry for the confusion, but we don't need this one anymore! The whole genome sequence has been released since I created this issue. See #521
