### ISSUE TITLE
need a "how to cite" link on front page

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#486]
im sure you're waiting on the publication but we should link . to something citeable in the meatntime.  perhaps fairsharing DOI.

I say this as someone clicking through websites trying to cite them all for a paper: we want hte words "how to cite us" with a linkout on there :)

**Comment by bradfordcondon** [comment]
FAIRsharing.org: HWG; Hardwood Genomics Project; DOI: https://doi.org/10.25504/FAIRsharing.srgkaf; Last edited: Jan. 8, 2019, 1:24 p.m.; Last accessed: Mar 04 2019 2:06 p.m.

**Comment by almasaeed2010** [comment]
@bradfordcondon should I add this to the site?

Sorry I haven't seen it earlier!

**Comment by bradfordcondon** [comment]
🤷‍♂️ it was an idea but really its up to meg

**Comment by almasaeed2010** [comment]
Alright then we'll review next meeting

**Comment by mestato** [comment]
yes!

**Comment by almasaeed2010** [comment]
Added to footer so it's visible in all pages.
