### ISSUE TITLE
BLASt missing database

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#490]
### Bug description
BLASTP with a nucleotide sequence against Q. robur peptides gives error:

Existing BLAST Database was chosen. BLAST database '/var/www/html/sites/default/files/bdb/quercus_robur/Qrob_PM1N_CDS_aa_20161004.fa ' is unaccessible. Please contact the site administrator.

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Found the issue finally. If you look closely, the file path contained a space at the end after `fa`. Once the space is removed, everything worked properly. 

We should create an issue in the tripal blast repo but for the time being. I'll use a hook to make sure the value is trimmed.

**Comment by almasaeed2010** [comment]
Issue submitted https://github.com/tripal/tripal_blast/issues/58

**Comment by almasaeed2010** [comment]
PR for fix submitted tripal/tripal_blast#59

Fix applied on live. We can close to this issue in favor for the one on the tripal_blast repo.

Thanks!
