### ISSUE TITLE
BLAST tool - improve user interface to find what they need

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#492]
BLAST tool interface is not very good. Problems:

When selecting a nucleotide database, we offer a number of types of databases:
- mRNA nucleotides
- gene nucleotides
- whole genome contigs, scaffolds or chromosomes

None of these are labeled very well. You have to click on the drop down and then look at the information in parentheses to get an idea of what you are searching. Let's fix this, we can get ideas from other genome databases about how this should look.

We should also link to the BLAST form from genome and transcriptome analysis pages and from organism pages.

**Comment by mestato** [comment]
Update on loading the above link: "Secure Connection Failed"
<img width="948" alt="screen shot 2019-03-04 at 10 17 42 am" src="https://user-images.githubusercontent.com/508122/53742523-cee1c680-3e66-11e9-9e61-67e752282eb0.png">

**Comment by almasaeed2010** [comment]
@mestato is this is the link you mean? https://www.hardwoodgenomics.org/blast/report/fPjVoPsAjVo

I tried accessing the URL from 3 different browsers (including FF) and it worked fine for me. an SSL trace shows that our certificate is still valid. (see here for trace: https://www.ssllabs.com/ssltest/analyze.html?d=hardwoodgenomics.org)

I wonder if it's a specific browser version?

**Comment by mestato** [comment]
No, it was a BLAST result with a query named lcl_contig0000566. 

https://www.hardwoodgenomics.org/blast/report/fPjVoPPyt

I got the secure connection error twice. Maybe the results had a already been deleted but the links back were still available.

**Comment by almasaeed2010** [comment]
Ok I get a 500 error on this page:

<img width="705" alt="screen shot 2019-03-04 at 10 40 14 am" src="https://user-images.githubusercontent.com/1512664/53743958-ea9a9c00-3e69-11e9-9963-3f540a03500f.png">


and here is the issue:

```
Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /var/www/html/sites/all/modules/tripal_blast/api/blast_ui.api.inc on line 714

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
```

**Comment by almasaeed2010** [comment]
The issue with this is that the generated XML is more than 300MB

```
333M	2019Mar01_154121.blast.xml
```

I am not sure if there is a way to tweak the blast program to limit the results to a manageable size.

**Comment by almasaeed2010** [comment]
Try using [XML Stream Reader](http://php.net/manual/en/class.xmlreader.php) to limit mem usage

**Comment by mestato** [comment]
Front page when selecting a blastn program, update text (on page one time):
 "Search a nucleotide database "
to 
"Search a nucleotide database (genome or transcripts) "

After selecting blastn:
Make it clear that there are scaffolds in addition to nucleotides. (They are too far down in list!) Make two lists???

**Comment by almasaeed2010** [comment]
@mestato would this work?

<img width="680" alt="Screen Shot 2019-03-28 at 10 45 59 AM" src="https://user-images.githubusercontent.com/1512664/55167113-c10e2100-5146-11e9-88fa-543d55fc62c3.png">

They are now separated by a title in the dropdown

**Comment by mestato** [comment]
Yes, wonderful!

**Comment by almasaeed2010** [comment]
ok this is now live!

Thanks
