### ISSUE TITLE
DEG ozone analysis

### ISSUE THREAD

**Issue by CaseyRichards92** [statonlab/hardwoods_site#493]

**Comment by almasaeed2010** [comment]
Here is why you were getting an error:

```
TypeError: Argument 1 passed to tripal_galaxy_get_connection() must be of the type integer, null given, called in /home/www/sites/all/modules/custom/tripal_galaxy/includes/tripal_galaxy.webform.inc on line 1034 in tripal_galaxy_get_connection() (line 31 of /home/www/sites/all/modules/custom/tripal_galaxy/api/tripal_galaxy.api.inc).
```

We should report this to [Tripal Galaxy](https://github.com/tripal/tripal_galaxy).

**Comment by almasaeed2010** [comment]
I edited the entry to fix this manually. Not sure what caused it but I updated the module and it was well behind so let's hope that fixes it: 

https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/537935
