### ISSUE TITLE
BLAST - improve user interface for results

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#494]
A number of improvements are possible here:

- Be able to see query from result page instead the name of a file created by the blast module *
- If there isn't a definition line for the query... just show "user query"? **
<img width="1121" alt="screen shot 2019-03-04 at 10 21 12 am" src="https://user-images.githubusercontent.com/508122/53743206-42380800-3e68-11e9-921d-8b6f9080d825.png">

- If you can get to a single blast result, you can see a list of recently run jobs. However, I can't figure out how to get to this list from any other page. Could we add this to the "my account" page?

<img width="1127" alt="screen shot 2019-03-04 at 10 28 17 am" src="https://user-images.githubusercontent.com/508122/53743220-48c67f80-3e68-11e9-816f-bdb10da691dd.png">

I want to talk about what we can do with this internally as I don't think there's much active development of this module right now

**Comment by mestato** [comment]
The query column refers to the query (duh) not the result. If a user does not  provide a definition line, change "No definition line" to "User-provided sequence"

**Comment by almasaeed2010** [comment]
It turns out `"No definition line"` is not part of the blast module. It looks like this is added by BLAST in the xml file. Our only option to change this is to do some JS search and replace after the results are rendered.

**Comment by almasaeed2010** [comment]
Fixed

<img width="1318" alt="Screen Shot 2019-03-14 at 7 58 43 AM" src="https://user-images.githubusercontent.com/1512664/54355268-00a91900-462f-11e9-8451-140e6a44be81.png">
