### ISSUE TITLE
KEGG results not displayed on feature page

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#496]
### Feature request
KEGG terms are being associated with a feature and working in CV Xray but are not available through the feature page.

**Comment by almasaeed2010** [comment]
I can see KEGG terms under the annotations tab in feature pages. Should they also appear elsewhere?

<img width="1337" alt="screen shot 2019-03-06 at 1 33 20 pm" src="https://user-images.githubusercontent.com/1512664/53904583-6f291e00-4014-11e9-8921-cb8ba3650b27.png">

**Comment by mestato** [comment]
Okay, I see them now, I think they are only missing on Q robur. Mentioned in #304
