### ISSUE TITLE
Table wrapping needs CSS love

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#497]
### Bug description
feature search results have column overlap issues:

<img width="790" alt="screen shot 2019-03-06 at 2 15 28 pm" src="https://user-images.githubusercontent.com/508122/53907023-51f74e00-401a-11e9-97d3-3ac81c9a8d72.png">

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Added some JS to analyze the size of the text and respond to the size of the window to break text evenly across cells. In other words, done!

**Comment by almasaeed2010** [comment]
Not fixed ... the js solution has messed up links

**Comment by almasaeed2010** [comment]
ok now fixed
