### ISSUE TITLE
tripalmap creates deadlink to tutorial link

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#498]
https://hardwoods.ag.utk.edu/mapviewer/3/LG6
<img width="727" alt="screen shot 2019-03-06 at 5 07 51 pm" src="https://user-images.githubusercontent.com/7063154/53917390-647d8180-4032-11e9-9d2c-d2d182db7c2a.png">

the "text tutorial" link is a deadlink to : https://hardwoods.ag.utk.edu/MapViewer_Manual
You can set the link via the admin area, however, theres no option for no-link.

so we want to either 
* change the admin settings to point out of our site and to cool seasons legume
* request that they make this tutorial page available so we can host it too
* request that having a null entry for the tutorial link variable (`tripal_map_text_tutorial_link`) simply doesnt create a linkout.

**Comment by almasaeed2010** [comment]
we fixed this on our end to link to their site for now.
