### ISSUE TITLE
Paging broken for biosamples

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#499]
### Bug description
When clicking on a page number on a biosamples page, it goes back to the summary pane.

### Location

*  Start at https://www.hardwoodgenomics.org/organism/Quercus/rubra?tripal_pane=gp_Biomaterials&page=0%2C6
*  Click on page 2
*  Now viewing summary page instead of page 2 of biosamples

**Comment by bradfordcondon** [comment]
works for me on chrome.  whats your browser and version?

also i m getting deja vu.  goign to dig for this issue...

**Comment by bradfordcondon** [comment]
https://github.com/statonlab/hardwoods_site/issues/297

clearing your browser cache fixed it last time for you.

raises the point that if yorue having this problem others might too and what can we do about it

**Comment by almasaeed2010** [comment]
Why is it adding a comma in the url `page=2,1`. weird!

**Comment by almasaeed2010** [comment]
Managed to replicate this issue. You need to visit this page using this link for the error to happen: https://www.hardwoodgenomics.org/organism/Quercus/rubra

**Comment by almasaeed2010** [comment]
fixed on live
