### ISSUE TITLE
Citrus sinensis genome

### ISSUE THREAD

**Issue by patricksis** [statonlab/hardwoods_site#501]
### Publication and Data Information
https://www.nature.com/articles/ng.2472
### Additional Information
@mestato This organism was on the list in issue #464. No organism was ever created, but the reference genome was, located here: https://hardwoodgenomics.org/bio_data/1962952. Maybe we can complete this organism, I found the relevant files here: http://citrus.hzau.edu.cn/orange/download/index.php
### Checklist
See [New Genome Documentation](https://github.com/mestato/statonlabprivate/wiki/How-to-load-a-new-organism-and-genome) for detailed instructions.
- [ ] Create Organism
- [ ] Create Publication
- [ ] Create Reference Genome
- [ ] Create InterProScan Annotation
- [ ] Create BLAST Annotation
- [ ] Run Chado FASTA Loader for CDS
- [ ] Run Chado FASTA Loader for Polypeptides
- [ ] Publish Tripal content
- [ ] Create KEGG Annotation
- [ ] Run Chado KEGG Loader
- [ ] Run Chado BLAST XML results loader
- [ ] Run Chado InterProScan XML results loader
- [ ] Create Blast Database

**Comment by bradfordcondon** [comment]
hi all, special note on this one- citrus sinensis is the Tripal "test" organism that one would load in the [Tripal tutorial](https://tripal.readthedocs.io/en/latest/user_guide/example_genomics.html).  Take care if theres pre-existing data, that it isn't from that.

**Comment by almasaeed2010** [comment]
Hello! 

There is no data except for a `genome reference` which contains info about the publication but I am not sure if we wanted to host this organism to begin with.
