### ISSUE TITLE
Populus trichocarpa Genome

### ISSUE THREAD

**Issue by patricksis** [statonlab/hardwoods_site#504]
### Publication and Data Information
https://phytozome.jgi.doe.gov/pz/portal.html#!info?alias=Org_Ptrichocarpa
### Additional Information
This organism has been added to the site before, but it is missing some features so we may want to update it. 
### Checklist
See [New Genome Documentation](https://github.com/mestato/statonlabprivate/wiki/How-to-load-a-new-organism-and-genome) for detailed instructions.
- [x] Create Organism
- [x] Create Publication
- [x] Create Reference Genome
- [x] Create InterProScan Annotation
- [x] Create BLAST Annotation
- [x] Run Chado FASTA Loader for CDS
- [x] Run Chado FASTA Loader for Polypeptides
- [x] Publish Tripal content
- [x] Create KEGG Annotation
- [x] Run Chado KEGG Loader
- [x] Run Chado BLAST XML results loader
- [x] Run Chado InterProScan XML results loader
- [x] Create Blast Database

**Comment by patricksis** [comment]
Dev site:
Fasta cds upload:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/544473
Fasta peptide upload:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/544483
Reg expression used:
```>(.*?).p```
Publication:
https://hardwoods.ag.utk.edu/Publication/2945582
Published tripal content:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/544486
Trembl xml results:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/547403
Swissprot xml results:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/548615
IPS xml results:
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/549006
KEGG annotation:
https://hardwoods.ag.utk.edu/KEGGresults/2966135

**Comment by patricksis** [comment]
Live site:
Publication:
https://www.hardwoodgenomics.org/Publication/3012288
InterProScan annotation:
https://www.hardwoodgenomics.org/InterProScan-annotation/3012289
trembl annotation:
https://www.hardwoodgenomics.org/BLAST-annotation/3012290
swissprot annotation:
https://www.hardwoodgenomics.org/BLAST-annotation/3012291
Cds fasta loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/748561
Polypeptide fasta loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/748565
Reg expression used:
```>(.*?).p```
Published tripal content:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/748569
Trembl results loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/748733
Swissprot results loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/748741
IPS results loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/750289

**Comment by patricksis** [comment]
@almasaeed2010 I think we may be running low on memory? I got this error when uploading IPS results:
```Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: Allowed memory size of 134217728 bytes exhausted (tried to
allocate 18874368 bytes) in phar:///usr/bin/drush/includes/drush.inc,
line 78```

**Comment by patricksis** [comment]
Blast data base:
Transcripts:
https://www.hardwoodgenomics.org/content/populus-trichocarpa-transcripts
Peptides:
https://www.hardwoodgenomics.org/content/populus-trichocarpa-peptides

**Comment by almasaeed2010** [comment]
@patricksis could you retry loading IPS? I changed the setting to allow for more memory.

**Comment by patricksis** [comment]
Thanks @almasaeed2010 that worked, It's strange though, it still shows an error on the job page, but  the job logs in terminal seems normal and the results show up on the website.

**Comment by almasaeed2010** [comment]
are you sure you are looking at the latest job page not the previous one?

**Comment by almasaeed2010** [comment]
Yeah the latest one shows an error: https://hardwoodgenomics.org/admin/tripal/tripal_jobs/view/750289 you are right. Something must've gone wrong in that case.

**Comment by patricksis** [comment]
Here's the results for one feature:
https://www.hardwoodgenomics.org/feature/Potri001G0078001?tripal_pane=group_interpro
I'm not sure why results would show up if there was an error.

**Comment by almasaeed2010** [comment]
So what could’ve happened is that the transaction was committed even though the job failed. That would cause some of the results to exist and some not to. So for now I need to investigate the issue a little more. I'll probably ask you to rerun later.

**Comment by patricksis** [comment]
Scaffolds:
https://www.hardwoodgenomics.org/content/populus-trichocarpa-scaffolds
KEGG annotation:
https://www.hardwoodgenomics.org/KEGGresults/3032842
KEGG loader:
https://www.hardwoodgenomics.org/admin/tripal/tripal_jobs/view/751090

**Comment by patricksis** [comment]
Jbrowse track added:
https://www.hardwoodgenomics.org/admin/tripal/extension/tripal_jbrowse/management/instances/6

**Comment by CaseyRichards92** [comment]
@patricksis 
- [x] I dont think your BLAST swissprot or trembl loaded correctly https://www.hardwoodgenomics.org/feature/Potri001G2412501?tripal_pane=group_homology

**Comment by patricksis** [comment]
@cricha59 
Really it looks fine on this one and a few others: https://www.hardwoodgenomics.org/feature/Potri001G0007002?tripal_pane=group_homology

**Comment by almasaeed2010** [comment]
The blast results that @cricha59 found are ok. An empty chart just means that we ran Blast for this feature but found no results (which is helpful info).

**Comment by patricksis** [comment]
Yeah that's what I figured
