### ISSUE TITLE
fagus sylvatica downloads broken

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#506]
### Bug description
From user:
we cannot download the Fagus sylvatica Reference Genome gff file and cds files. https://www.hardwoodgenomics.org/Genome-assembly/2365974. 

Email zhangbja (zhangzhiyong543@163.com) when resolved

Can confirm two of four files, links are broken

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Fixed

**Comment by almasaeed2010** [comment]
@mestato did you email the person who was interested in this? If so, I guess we can close this.

**Comment by mestato** [comment]
email sent
