### ISSUE TITLE
add best hit to summary pane for mRNA and gene

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#508]
### Feature description
User having problems finding annotation. Suggestion to put BLAST best hit on summary pane of organism with a link to open the BLAST pane. feasible?

<!-What do we want done?  Who should do it?  Is it urgent or backburner?  Please tag/assign issue appropriately.
-->

**Comment by almasaeed2010** [comment]
Would be helpful to simply rename the tab to `Homology (BLAST)` instead of only `Homology`? Otherwise, it's also easier to add a link to the summary table indicating that blast results are available, click here to open the tab.

**Comment by mestato** [comment]
Yes, I think that's helpful for users. Also, after meeting with the user today, I misinterpreted the issue he was having finding annotation anyway.

**Comment by almasaeed2010** [comment]
done
