### ISSUE TITLE
Is it normal to have ~2 million blast annotations?

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#509]
As you can see below, everything but BLAST generates around ~200k annotations per organism (depending on how large the FASTA file is). However, BLAST generates way more than anything else (above 1 million for each DB!). Are all of these annotations needed? Can we limit to top/best hits?

<img width="1396" alt="Screen Shot 2019-04-01 at 7 51 19 AM" src="https://user-images.githubusercontent.com/1512664/55325418-0ab28080-5453-11e9-85ed-5e39711c4a7f.png">

**Comment by bradfordcondon** [comment]
this is entirely dependent on the number of hits you output.  It's possible we'd be better off doing some post-processing on the blast hits, ie, filtering the results to just the top 5.  Limiting to n hits during the run doesnt limit it to the n *best* hits ofr some reason (dont have time to cross-link issue here but should be another ticket about that)

**Comment by almasaeed2010** [comment]
I wrote a script that would extract the top 25 from the blast file. We can probably use that to limit to top 5 instead. https://gist.github.com/almasaeed2010/702a7a79021be496bd6a5d79954395ea

**Comment by mestato** [comment]
Solutions to try from meeting today:
- suck data out of table, trim extra hits, reupload
- look at trimming other xml fields we don't display

If those don't work/seem too time consuming, we can revisit Diamond to reannotate everything b/c we don't have xmls still.

**Comment by almasaeed2010** [comment]
I think I finally know how to do this. The table below is an example of the content in chado.blast_hit_data. Since we have feature_id, analysis_id and eval, we can easily sort and keep only the top 5. 

|analysis_id | feature_id | hit_best_eval |  hit_best_score | hit_pid |
|-----------|-----------|--------------|-----------------|-------|
|         278 |    7143870 |   8.52956e-90       |            673 |   87.32 |
|         278 |    7143870 |   1.22368e-58       |            477 |   59.87 |
|         278 |    7143870 |   5.61957e-98       |            798 |   93.08 |
|         278 |    7143870 |   7.42578e-93       |            763 |   88.05 |
|         278 |    7143870 |   6.12534e-82       |            685 |   86.39 |
|         278 |    7143870 |   6.67947e-64       |            505 |   59.48 |
|         278 |    7143870 |  4.99663e-102       |            786 |   93.04 |
|         278 |    7143870 |   5.60291e-99     |            794 |   88.89 |


I think, instead of adding more on the user, we should just create a php script that does this automatically after the blast loader finishes.

**Comment by mestato** [comment]
I like the idea of the loader handling it. There is already an admin feature that specifies how many hits to show to the user. Should it be a single check box -how many hits to parse out and show? 

The column to sort on is hit_best_eval.

While getting the loader to handle the parsing is definitely a great solution for future loading, it won't fix the existing table and records, so that may need a separate approach of fixing the table.

**Comment by almasaeed2010** [comment]
Oh I haven't seen that option before in the loader! If that actually works, then we probably have 25 best hists already. So all we need to do to is write a script to fix existing records to get 5 instead of 25. I am just not sure how the loader limits to top 25. i,e is it sorting by eval or just plucking the first 25.

**Comment by mestato** [comment]
Its in the loader admin page so that does make me think its filtering prior to loading. 

https://www.hardwoodgenomics.org/admin/tripal/loaders/blast_loader

![Screen Shot 2019-04-15 at 9 08 33 AM](https://user-images.githubusercontent.com/508122/56135146-1b3c1e00-5f5e-11e9-8c29-c072dc947833.png)

If its already parsing extraneous hits and not storing them, then we might need to think more creatively about reducing the size of the table.

**Comment by almasaeed2010** [comment]
Something a bit odd about the loader is that it stores the actual XML in the `analysisfeatureprop` table. Not sure why it would need that. There are `8,217,280` records in that table. Each record is 1 line of the xml file for a given pair of analysis and feature! And the funny thing is, the module never again looks at that table.

**Comment by almasaeed2010** [comment]
Also I looked at the code and it appears to be storing the first 25 rather than best 25.

**Comment by mestato** [comment]
I think the Tripal field for blast results uses the XML to bulid the views of the BLAST results:

![Screen Shot 2019-04-15 at 9 11 28 AM](https://user-images.githubusercontent.com/508122/56135338-7f5ee200-5f5e-11e9-95ad-acb79558ea44.png)

![Screen Shot 2019-04-15 at 9 11 19 AM](https://user-images.githubusercontent.com/508122/56135353-8a197700-5f5e-11e9-95ee-a73f9b6817c6.png)

Where else would it get that information?

https://www.hardwoodgenomics.org/bio_data/2555103?tripal_pane=group_homology

**Comment by almasaeed2010** [comment]
That info is in the blast_organisms and blast_hit_data tables. It doesn't read from `analysisfeatureprop` outside of the importer.

this is an example of the blast_organisms table:

```
 blast_org_id | blast_org_name              
                                                                                                                 
--------------+---------------------------------------------------------------------------------------
            1 | Unknown
            2 | sp|Q8GUH2|Y1015_ARATH Uncharacterized protein At1g01500 Arabidopsis thaliana=At1g01500 PE=2 SV=1
            3 | sp|Q9FII5|TDR_ARATH Leucine-rich repeat receptor-like protein kinase TDR Arabidopsis thaliana=TDR PE=1 SV=1
            4 | sp|Q9M0G7|PXL2_ARATH Leucine-rich repeat receptor-like protein kinase PXL2 Arabidopsis thaliana=PXL2 PE=2 SV=1
            5 | sp|Q9FRS6|PXL1_ARATH Leucine-rich repeat receptor-like protein kinase PXL1 Arabidopsis thaliana=PXL1 PE=2 SV=1
            6 | sp|O49545|BAME1_ARATH Leucine-rich repeat receptor-like serine/threonine-protein kinase BAM1 Arabidopsis thaliana=BAM1 PE=1 SV=1
            7 | sp|Q9M2Z1|BAME2_ARATH Leucine-rich repeat receptor-like serine/threonine-protein kinase BAM2 Arabidopsis thaliana=BAM2 PE=1 SV=1
            8 | sp|P0DL10|TD1_MAIZE Leucine-rich repeat receptor-like kinase protein THICK TASSEL DWARF1 Zea mays=TD1 PE=2 SV=1
            9 | sp|Q5Z9N5|FON1_ORYSJ Leucine-rich repeat receptor-like kinase protein FLORAL ORGAN NUMBER1 Oryza sativa subsp. japonica=FON1 PE=1 SV=1
           10 | sp|O65440|BAME3_ARATH Leucine-rich repeat receptor-like serine/threonine-protein kinase BAM3 Arabidopsis thaliana=BAM3 PE=2 SV=3
           11 | sp|Q9SYQ8|CLV1_ARATH Receptor protein kinase CLAVATA1 Arabidopsis thaliana=CLV1 PE=1 SV=3
           12 | sp|Q9SGP2|HSL1_ARATH Receptor-like protein kinase HSL1 Arabidopsis thaliana=HSL1 PE=2 SV=1
```

**Comment by almasaeed2010** [comment]
Nevermind it does use the xml elsewhere it just initiates the blast importer as an object in the api which is unexpected since the importer should only be initiated and run by tripal itself.

**Comment by mestato** [comment]
if its true that we are storing more than 5 BLAST hits per feature, I may have stumbled on a different way of trimming the blast hits to the best ones. blast_formatter: http://home.cc.umanitoba.ca/~psgendb/doc/NCBI/blast_formatter.txt

we woudl generate the blast hits in fmt 11, then convert to fmt 5 (xml) while filtering for 5 best hits.

**Comment by mestato** [comment]
From here on, we will only keep top 5 hits in the database (not 25!)
