### ISSUE TITLE
rubber tree genome

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#51]
Paper: https://www.nature.com/articles/nplants201673

Includes 22 RNAseq libraries that can be used for expression.

From the paper:
"The H. brasiliensis genome and RNA-seq sequences have been deposited in GenBank/DDBJ/EMBL under the accession codes of LVXX01000000 and SRP069104, respectively."

When we start on this, we should contact authors to try to get repeats and variants to add as JBrowse tracks.

**Comment by Lupercal2** [comment]
The cds and polypeptide files are nowhere to be found for this paper either. 
@mestato

**Comment by mestato** [comment]
I see links for gff, CDS and protein on [this NCBI page](https://www.ncbi.nlm.nih.gov/genome/?term=Hevea+brasiliensis)

**Comment by cricha59** [comment]
Organism created
https://hardwoods.ag.utk.edu/organism/Hevea/brasiliensis%20

**Comment by cricha59** [comment]
Sequences can be found here.
```/var/www/html/sites/default/files/sequences/rubber_tree```

**Comment by cricha59** [comment]
FASTA Loader job
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/696234

**Comment by cricha59** [comment]
@almasaeed2010 @MattHuff What regular expression should I use to match the peptide names with the cds?

**Comment by MattHuff** [comment]
Try `>(XP_\d*\.?\d?)`.

**Comment by cricha59** [comment]
Polypeptide job
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/696940

Recieved 
```
Cannot find a unique feature for the parent 'YP_004327641.1' of type 'gene' for the feature
```
there are only 84 proteins with these names
0 of which exist in the CDS file
therefore, those errors can be safely ignored

**Comment by cricha59** [comment]
```#PBS -N swissprot_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=02:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/split/GCF_001654055.1_ASM165405v1_cds_from_genomic.fna.fixed.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/kiwi/blast/swissprot/rubbertree_swissprot_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by cricha59** [comment]
Start BLAST for protein files

**Comment by cricha59** [comment]
Chado InterProScan Loader job page link
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/710273

Used this path.
```/var/www/html/sites/default/files/sequences/rubber_tree/blast/swissprot```

**Comment by cricha59** [comment]
**Diamond**
```
#PBS -N trembl_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=2:00:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/diamond blastx \
 -q /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/split/GCF_001654055.1_ASM165405v1_cds_from_genomic.fna.fixed.$PBS_ARRAYID \
 -d /lustre/haven/gamma/staton/library/uniprot/diamond_db/uniprot_trembl.dmnd \
 -o /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/blast/trembl/rubber_tree_trembl_$PBS_ARRAYID.xml \
 --evalue 1e-5 \
 --outfmt 5
```

**Comment by cricha59** [comment]
Inter Pro Scan job loader page
https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/712948

**Comment by cricha59** [comment]
Need to create an InterPro Analysis Annotation and then re run IPS

**Comment by cricha59** [comment]
## Live Site ##
***Organism Created***
https://www.hardwoodgenomics.org/organism/Hevea/brasiliensis%20 UPDATE DESCRIPTION

**Comment by cricha59** [comment]
Diamond w/ new script
````#PBS -N trembl_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=4:00:00

cd $PBS_O_WORKDIR

/lustre/haven/gamma/staton/software/diamond blastx \
 -q /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/split/GCF_001654055.1_ASM165405v1_cds_from_genomic.fna.fixed.$PBS_ARRAYID \
 -d /lustre/haven/gamma/staton/library/uniprot/diamond_db/uniprot_trembl_all.dmnd \
 -o /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/blast/trembl/rubber_tree_trembl_$PBS_ARRAYID.xml \
 --evalue 1e-5 \
 --outfmt 5
```

**Comment by cricha59** [comment]
Split cds file into 400 files to run regular trembl.qsh and ran two different jobs with 200 files each
```#PBS -N trembl_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=12:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/splits/GCF_001654055.1_ASM165405v1_cds_from_genomic.fna.fixed.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/blast/trembl/rubber_tree_trembl_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

TrEMBL 201-400
```#PBS -N trembl_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 201-400
#PBS -l nodes=1:ppn=2
#PBS -l walltime=12:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/splits/GCF_001654055.1_ASM165405v1_cds_from_genomic.fna.fixed.$PBS_ARRAYID \
 -db /lustre/haven/gamma/staton/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/gamma/staton/projects/undergrads/rubber_tree/blast/trembl/rubber_tree_trembl_$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by CaseyRichards92** [comment]
Live site
BLAST db for CDS https://www.hardwoodgenomics.org/content/hevea-brasiliensis-transcripts
BLAST db for Peptide https://www.hardwoodgenomics.org/content/hevea-brasiliensis-peptides

**Comment by CaseyRichards92** [comment]
AG SITE 
JBrowse instance added https://hardwoods.ag.utk.edu/admin/tripal/tripal_jobs/view/503919

**Comment by mestato** [comment]
Comments on JBrowse for dev site:
- its possible when clicking on the feature to give the user an option to go to the gene page on hwg, which would be good to get working
- every genomic location has one big bar at the top labeled “unknown”, any idea whats going on with that? need to examine that entry in the gff file

**Comment by CaseyRichards92** [comment]
Genome has been finished.
