### ISSUE TITLE
jbrowse track label adjustment

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#510]
### Feature description
Its irritating that the jbrowse track label overlaps the glyphs.

<img width="834" alt="Screen Shot 2019-04-05 at 2 41 57 PM" src="https://user-images.githubusercontent.com/508122/55649451-ff43ba00-57b0-11e9-8c2e-33ecfe102bba.png">

Could we try this fix (trackLabels: no-block in param file):
https://github.com/GMOD/jbrowse/issues/490

**Comment by almasaeed2010** [comment]
This feature was introduced in jbrowse 1.12 but we use 1.11 so need to update first.

**Comment by almasaeed2010** [comment]
done

**Comment by almasaeed2010** [comment]
Labels now appear above the track.

<img width="621" alt="Screen Shot 2019-04-10 at 7 29 57 AM" src="https://user-images.githubusercontent.com/1512664/55875199-763ad300-5b62-11e9-9ce0-e23a693bdaf7.png">
