### ISSUE TITLE
second reference genome not showing up in reference genome field attached to organism

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#515]
### Bug description

When visiting the chinese chestnut organism page, on the tripal pane for reference genome (https://www.hardwoodgenomics.org/organism/Castanea/mollissima?tripal_pane=group_reference_genome), it only shows the old one. It should show the old and the new (https://www.hardwoodgenomics.org/Genome-assembly/3032843).

The new analysis also does not show up in the Analysis pane.

On the new analysis, it correctly links back to the C. mollissima organism.

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
cache needed clearing. Both show up now.

**Comment by almasaeed2010** [comment]
To elaborate on this issue. Since the association between the organism and the analysis is done in the analysis page, the organism's cache must be cleared before it can detect the association.
