### ISSUE TITLE
Fix chestnut gene names in Jbrowse

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#517]
### Bug description
The gene names on Jbrowse (g12345) need to be changed to start with "Cm_" (Cm_g12345).

This impacts two tracks: "High quality gene models" and "Low quality gene models"

New gff file for high quality gene models on staton server:
/staton/projects/chestnut/psudochro/Castanea_mollissima_scaffolds_v3.2.HQ.gff

New gff file for low quality gene models on staton server:
/staton/projects/chestnut/psudochro/Castanea_mollissima_scaffolds_v3.2.LQ.gff

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by mestato** [comment]
Instructions:
- use JBrowse provided scripts to remove old trakcs and add new tracks
- to link the feature to JBrowse, use the linker module (which is Tripal -> Extension -> Jbrowse link)

**Comment by CaseyRichards92** [comment]
@almasaeed2010 is this issue as simple as deleting the old tracks and loading the new ones? then adding the links. If so I can start on this.

**Comment by CaseyRichards92** [comment]
@mestato We are just deleting tracks "High quality gene models" and "Low quality gene models" and updating with the new gff's provided?

https://www.hardwoodgenomics.org/bio_data/21?tripal_pane=group_jbrowse

**Comment by mestato** [comment]
Yes

**Comment by CaseyRichards92** [comment]
Tracks are still not mapping correctly. We removed "Cm_" in HQ and LQ .gff to match with JBrowse and still not reading. https://www.hardwoodgenomics.org/tools/jbrowse/?data=chinese_chestnut&tracks=Chestnut_high_quality_gene_models%2CChestnut_low_quality_gene_models&loc=scaffold00093%3A136318..141815&highlight=

**Comment by mestato** [comment]
New plan:

* add the HQ and LQ tracks to JBRowse chestnut v 3.2:
https://hardwoodgenomics.org/tools/jbrowse/index.html?data=chinese_chestnut_3-2

* remove them from JBrowse chestnut v 1.1

**Comment by CaseyRichards92** [comment]
HQ and LQ tracks added to chestnut v 3.2 https://hardwoodgenomics.org/tools/jbrowse/index.html?data=chinese_chestnut_3-2&loc=lcl_contig0000009%3A265153..395434&tracks=DNA%2CChestnut_low_quality_gene_models%2CChestnut_high_quality_gene_models&highlight=

Added link to organism jbrowse page https://www.hardwoodgenomics.org/organism/Castanea/mollissima?tripal_pane=group_jbrowse
