### ISSUE TITLE
Go live with jbrowse management module

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#518]
Enabled tripal_jbrowse_mgmt module live. 

@cricha59 please give it a try and let me know if you encounter any errors

**Comment by CaseyRichards92** [comment]
https://hardwoodgenomics.org/tools/jbrowse/?data=data%2Fhevea_brasiliensis___rubber_tree%2Fdata&tracks=&loc=NW_018745694.1%3A465613..4187497&highlight=

I do not see any tracks

**Comment by almasaeed2010** [comment]
Seems to be working now 🎊 

Documentation https://hardwoods-jbrowse.readthedocs.io/en/latest/
