### ISSUE TITLE
"No BLAST results found" for feature pane

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#520]
### Feature description
If a feature has no BLASt homology, then the BLAST pane doesn't show up. However, this is a bit confusing - its not clear that a BLAST was tried. I think we need a way to display "no homology found" (IE signaling to the user this is super suspecious or super unique) if the analysis was run on the feature but nothing identified. not sure if this would be at the loading level (would be nice but involves getting into the blast module) or at the feature bundle (within our scope to alter, but how to know if the feature has been run against blast?)

### Link to relevant info
Example chestnut feature with no BLAST result:
https://www.hardwoodgenomics.org/bio_data/3035466?tripal_pane=group_sequence_tripalpane

This probably should be similar for IPS

**Comment by almasaeed2010** [comment]
Tripal allows us to specify (on a bundle level) whether we want to hide empty fields or display a message saying no content was found. However, doing this means it affects all fields and not only blast.

**Comment by mestato** [comment]
Lets move this over to the BLAST issue queue as a feature request.

**Comment by almasaeed2010** [comment]
ok this may have been actually solved in the newest release without us realizing it. The link you shared now has a tab showing an empty chart. https://www.hardwoodgenomics.org/bio_data/3035466?tripal_pane=group_homology

Does that work?

**Comment by mestato** [comment]
Yeah its ok (typos not withstanding).
