### ISSUE TITLE
JBrowse page - automate list

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#522]
### Feature description
The JBrowse page of all available JBrowse instances currently needs to be manually updated (https://www.hardwoodgenomics.org/content/jbrowse). Would be great to have it automated.

**Comment by almasaeed2010** [comment]
@jwest60 can you do this?

You will need to look at the tripal_jbrowse_instance module and have it create a block or a page to list all the organisms that have JBrowse linked to them

**Comment by almasaeed2010** [comment]
Live now. Thanks @jwest60!

https://hardwoodgenomics.org/content/jbrowse
