### ISSUE TITLE
Chestnut feature page, BLAST pane not displaying visualization

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#524]
### Bug description
Blue bars on the diagram for blast results not being drawn. Position is -2 for some reason.

https://www.hardwoodgenomics.org/feature/Cm_g36795.t1?tripal_pane=group_homology

<img width="810" alt="Screen Shot 2019-06-03 at 5 40 57 PM" src="https://user-images.githubusercontent.com/508122/58836443-d9a72580-8626-11e9-823e-6cf2497d02c3.png">

This is a normal example for comparison:
https://www.hardwoodgenomics.org/feature/Acersaccharum022416comp53054c0seq1?tripal_pane=group_homology

<img width="796" alt="Screen Shot 2019-06-03 at 5 42 00 PM" src="https://user-images.githubusercontent.com/508122/58836493-f0e61300-8626-11e9-807d-6faaa56e3870.png">

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Updated the module. The graph shows up for me. Could you try again?

**Comment by mestato** [comment]
Fixed for me!
