### ISSUE TITLE
Convert Mango Genome Assembly to Transcriptome Assembly

### ISSUE THREAD

**Issue by CaseyRichards92** [statonlab/hardwoods_site#529]
Mango transcriptome needs reference genome changed to a transcriptome assembly #479

**Comment by almasaeed2010** [comment]
There is a good chance Alchemist can handle this but I need to test it on a new version of Tripal first before doing it on the live server

**Comment by almasaeed2010** [comment]
Done. New URL located at https://hardwoodgenomics.org/Transcriptome-assembly/3352347
