### ISSUE TITLE
Pomegranate gene expression

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#538]
### Publication and Data Information
Pomegranate genome paper includes expression data that could be put into db:
https://onlinelibrary.wiley.com/doi/full/10.1111/pbi.12875

### Checklist
See [New Genome Documentation](https://github.com/mestato/statonlabprivate/wiki/How-to-load-a-new-organism-and-genome) for detailed instructions.
- [ ] Create Organism
- [ ] Create Publication
- [ ] Create Reference Genome
- [ ] Create InterProScan Annotation
- [ ] Create BLAST Annotation
- [ ] Run Chado FASTA Loader for CDS
- [ ] Run Chado FASTA Loader for Polypeptides
- [ ] Publish Tripal content
- [ ] Create KEGG Annotation
- [ ] Run Chado KEGG Loader
- [ ] Run Chado BLAST XML results loader
- [ ] Run Chado InterProScan XML results loader
- [ ] Create Blast Database

**Comment by patricksis** [comment]
Authors have been contacted about obtaining gene expression data. Will comment again if we get a reply. If we don't get a reply, we may close the issue.

**Comment by patricksis** [comment]
I'm closing this issue due to lack of response from authors.
