### ISSUE TITLE
Unnecessary mview  feature_expression_data

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#54]
https://github.com/tripal/tripal_analysis_expression/issues/122

**Comment by bradfordcondon** [comment]
offending mview: feature_expression_data
its not created in the code of our module, its a custom mview.

we could 
* leave it and let people be confused
* delete it

@almasaeed2010 did you find a plce this mview is in use on the site? Even if the answer is no, i think the "safe" thing to do is just leave it....

**Comment by almasaeed2010** [comment]
I'd just leave it as you suggested. It's not a big deal.

**Comment by bradfordcondon** [comment]
leaving the mview but if someone unearths this discussion:  the mview doesnt appear to be used anywhere, and isnt defined in the code of the tripal_analysis_expression module. Don't be confused by a similar feature expression mview!
