### ISSUE TITLE
Dogwood genome now available

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#549]
### Publication and Data Information
No publication yet, but the PI (Jim Leebens-Mack) emailed to say the data is in [COGE](https://genomevolution.org/coge/). Someone needs to go look for it and see what is there vs what we might be missing to add the genome to the site. Species is _Cornus florida_.

Once we have it loaded and the JBrowse working, we'll need to deal with the various Cornus transcriptomes. They can be displayed as tracks on Jbrowse. The individual C. florida transcripts could be linked to their closest gene in the genome.

### Checklist
See [New Genome Documentation](https://github.com/mestato/statonlabprivate/wiki/How-to-load-a-new-organism-and-genome) for detailed instructions.
- [ ] Create Organism
- [ ] Create Publication
- [ ] Create Reference Genome
- [ ] Create InterProScan Annotation
- [ ] Create BLAST Annotation
- [ ] Run Chado FASTA Loader for CDS
- [ ] Run Chado FASTA Loader for Polypeptides
- [ ] Publish Tripal content
- [ ] Create KEGG Annotation
- [ ] Run Chado KEGG Loader
- [ ] Run Chado BLAST XML results loader
- [ ] Run Chado InterProScan XML results loader
- [ ] Create Blast Database

**Comment by patricksis** [comment]
Data is here:
https://genomevolution.org/coge/SearchResults.pl?s=Cornus%20florid&p=genome

They have a fasta (contigs), gff bed, and tbl. 

Not seeing files for coding regions or peptides

**Comment by mestato** [comment]
Don't use those. Emailing the PI now

**Comment by CaseyRichards92** [comment]
@mestato did you ever get a response from the PI?

**Comment by mestato** [comment]
Nope. Closing :(
