### ISSUE TITLE
Add reference genomes and low coverage contigs to BLAST

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#57]
BlastN only - add ability to blast a sequence against the full reference genomes and against the contigs from the 10 low coverage sequence contigs. These latter are from this analysis (https://hardwoodgenomics.org/content/gssrs) and are linked off of each species "predicted SSRs (genomic)" page with the link for "Reconstructed Fragments - Fastq File". They can all be found:

https://hardwoodgenomics.org/sites/default/files/gSSRs/black_cherry_extendedFrags.fastq
https://hardwoodgenomics.org/sites/default/files/gSSRs/black_walnut_extendedFrags.fastq
https://hardwoodgenomics.org/sites/default/files/gSSRs/blackgum_extendedFrags.fastq
etc.

**Comment by bradfordcondon** [comment]
- [ ] Convert fastq to fasta
- [ ] format into blastn database (`makeblastdb`)
- [ ] Add blastdb to Tripal

**Comment by bradfordcondon** [comment]
sorry... how are these different from the transcriptomes already loaded?

Do the FASTA files need to be loaded in as features so that they'll link back to something?

**Comment by mestato** [comment]
These are whole genomes, not genes. The linking back has always been the problem - the proper way would be to link back to the JBrowse with the blast hit highlighted. It works on KnowPulse. Can you see this link on knowpulse?

http://knowpulse.usask.ca/portal/blast/report/HisAHijVo

Otherwise just run a blast job on a genome, it builds results the way we expect to see them, but it builds the link to click through to jbrowse.

**Comment by bradfordcondon** [comment]
But we don't have a jbrowse instance for these gSSR sequences?  We have one for the actual assemblies?

I'm pretty sure i don't understand what you are asking for.

**Comment by bradfordcondon** [comment]
Nyssa sylvatica, for example.  We don't even have a JBrowse up for it, let alone a second JBrowse for the GSSR sequecnces.

**Comment by mestato** [comment]
I'm not sure how recent this documentation is, but I think this, JSON embedded in the URL, is the basic idea:
http://gmod.org/wiki/JBrowse_Configuration_Guide#addFeatures

**Comment by almasaeed2010** [comment]
I can take care of the linking back once I figure out how to get all the info needed to build the URL. Also, this will apply only to BlastN but will it apply to any species or only the ones you highlighted?

**Comment by mestato** [comment]
Lets ignore the gSSRs for now. Lets just do the 4 reference genomes.

**Comment by mestato** [comment]
Yes, just blastn, and the four species to link out to jbrowse are the 4 that we have a JBrowse for (chinese chestnut, english walnut, european ash, valley oak)

**Comment by almasaeed2010** [comment]
It seems JBrowse expects location coordinates for each feature. I am not sure if we collect those. I can't find anything in the feature_loc table.

**Comment by almasaeed2010** [comment]
Could that info be available in the blast results?

**Comment by mestato** [comment]
yes, it needs to be parsed from the blast results

**Comment by almasaeed2010** [comment]
I looked at the results. I can't figure out where that info is. I'll see if Bradford can take a look at it with me and figure out how to get it.

**Comment by mestato** [comment]
i can show you tomorrow, no problem

**Comment by bradfordcondon** [comment]
>These are whole genomes, not genes. The linking back has always been the problem - the proper way would be to link back to the JBrowse with the blast hit highlighted. It works on KnowPulse. Can you see this link on knowpulse?

The issue of linking back is not a problem, the blast module can handle that.

We just don't have JBrowse instances for any of these and need to handle that first.

**Comment by bradfordcondon** [comment]
- [ ] black_cherry_extendedFrags.fastq


- [ ] sweetgum_hqSSR_seqs.fasta

- [ ] honeylocust_hqSSR_seqs.fasta

    
- [ ] white_ash_extendedFrags.fastq

- [ ] blackgum_extendedFrags.fastq  

- [ ] green_ash_extendedFrags.fastq

- [ ] black_walnut_extendedFrags.fastq


  

- [ ] sugar_maple_extendedFrags.fastq

- [ ] white_oak_extendedFrags.fastq

- [ ] sweetgum_extendedFrags.fastq

**Comment by mestato** [comment]
Lets just do the 4 JBrowses we already have. (Sorry if it wasnt' clear above, by "Lets ignore the gSSRs for now." I mean the 10 species with low coverage sequencing contigs).

**Comment by mestato** [comment]
Also, it looks like the functionality of the BLAST UI module itself is not in question, but just in case, I also found this issue from drupal.org: https://www.drupal.org/project/tripal_blast/issues/2356593

**Comment by bradfordcondon** [comment]
>Lets ignore the gSSRs for now. Lets just do the 4 reference genomes.

sorry missed that.

OK in that case all we need to do is make a blast db of the reference assembly, add it to tripal, and and configure it to go to JBrowse.

**Comment by bradfordcondon** [comment]
Reference genomes:

* https://www.hardwoodgenomics.org/sites/default/files/chestnut_genome_v1_1/Cm_v1.1_contigs.fasta
* http://ashgenome.org/sites/default/files/assembly_file_5/BATG-0.5-CLCbioSSPACE.fa.gz
*  https://ucla.box.com/shared/static/niimt40dq4heaefr8ajv1guhje62k50z.gz
* http://dendrome.ucdavis.edu/ftp/Genome_Data/genome/Reju/walnut.wgs.5d.scafSeq

**Comment by bradfordcondon** [comment]
Implemented on dev
Need to double check links tomorrow and re-do for live.

[notebook on wki to recreate](https://github.com/mestato/statonlabprivate/wiki/blast-database-creation:-reference-and-draft-genomes) for live

**Comment by bradfordcondon** [comment]
* [valley oak](https://www.hardwoodgenomics.org/content/quercus-lobata-sw786-scaffolds)
* [ash](https://www.hardwoodgenomics.org/content/fraxinus-excelsior-batg-05-scaffolds)
* [english walnut](https://www.hardwoodgenomics.org/content/juglans-regia-scaffolds)
* [chinese chestnut](https://www.hardwoodgenomics.org/content/castanea-mollissima-scaffolds)

**Comment by bradfordcondon** [comment]
closing this out.

We aren't going to worry about the lower coverage contigs for now.
