### ISSUE TITLE
add cds files to juglans genomes

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#579]
Analysis page includes scaffolds and peptide files for download. We also have CDs files that can be linked (they are already on server, just need HTML links).

https://hardwoodgenomics.org/Genome-assembly/2209433

**Comment by CaseyRichards92** [comment]
CDS has been added https://hardwoodgenomics.org/Genome-assembly/2209433?tripal_pane=group_downloads

**Comment by mestato** [comment]
Microcarpa only has one file, any reason for that?

**Comment by mestato** [comment]
Confirmed, we have no additional files for microcarpa.
