### ISSUE TITLE
Stephen's Juglans genomes annotation

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#583]
Annotation files are gbff. can we convert to gff?

**Comment by mestato** [comment]
GFFs are in this folder for Ebrahimi's files:
/files/files/sequences/ebrahimi/assemble/genome_annotated

I didn't create those. Was it some other organism that had gbffs?

**Comment by mestato** [comment]
Just realized this is for the Stephen's juglans not Ebrahimi's juglans as note din the title...but i can't find the gbff files for those

**Comment by CaseyRichards92** [comment]
I had them in the tree genes folder on the staton server located in the the organisms folder  /staton/projects/treegenes_data/j_hindsii

**Comment by mestato** [comment]
no genes in those files, appear to only be scaffolds. Closing.
