### ISSUE TITLE
Malus domestica gene expressions "not set"

### ISSUE THREAD

**Issue by CaseyRichards92** [statonlab/hardwoods_site#601]
@almasaeed2010  Biosamples although given a tissue still say "Not Set" https://www.hardwoodgenomics.org/feature/MD02G1118500?tripal_pane=group_expression

**Comment by almasaeed2010** [comment]
Ok Finally figured this one out. It's odd but you have to set at least 2 properties for it to work. In my case, I added "Not Set" to the Treatment field when editing the biosample. This will make it work for the time being. I will look into the code in hopes that I can find a way to fix it for all organisms without having to edit every individual biosample.

**Comment by almasaeed2010** [comment]
ok this is fixed on live now 👏
