### ISSUE TITLE
Results cannot be displayed for BLAST

### ISSUE THREAD

**Issue by mestato** [statonlab/hardwoods_site#602]
### Bug description
Ran blastn with a random poplar nucleotide sequence and the Castanea mollissima scaffolds database. (Laura Georgi, the reporter of the bug, works on chestnut). Can confirm same error:

![Screen Shot 2020-09-14 at 5 46 27 PM](https://user-images.githubusercontent.com/508122/93141535-580bc780-f6b2-11ea-8410-5985abccd23e.png)

### Location

*  Go to '...'
*  Click on '....'
*  Scroll down to '....'

**Comment by almasaeed2010** [comment]
Looks like we just needed to install blast cli tools on the server. Should work now.

**Comment by almasaeed2010** [comment]
Turns out we also needed to configure the /tmp directory for apache and install additional php libraries (php-gd and php-imagick)  but I tested it and it now works as expected.

Feel free to reopen if it doesn't work for you.
