### ISSUE TITLE
Hydrangea macrophylla 

### ISSUE THREAD

**Issue by RaymondS1** [statonlab/hardwoods_site#604]
### Publication and Data Information
https://academic.oup.com/dnaresearch/advance-article/doi/10.1093/dnares/dsaa026/5974207

### Additional Information
Link to genome (HMA_r1.2_1): https://plantgarden.jp/en/list/t23110/genome/t23110.G003

### Checklist
See [New Genome Documentation](https://github.com/mestato/statonlabprivate/wiki/How-to-load-a-new-organism-and-genome) for detailed instructions.
- [x] Create Organism
- [x] Create Publication
- [x] Create Reference Genome
- [x] Create InterProScan Annotation
- [x] Create BLAST Annotation
- [x] Run Chado FASTA Loader for CDS
- [x] Run Chado FASTA Loader for Polypeptides
- [x] Publish Tripal content
- [x] Create KEGG Annotation
- [x] Run Chado KEGG Loader
- [x] Run Chado BLAST XML results loader
- [ ] Run Chado InterProScan XML results loader
- [x] Create Blast Database

**Comment by RaymondS1** [comment]
Link to genome (HMA_r1.2_1): https://plantgarden.jp/en/list/t23110/genome/t23110.G003

**Comment by RaymondS1** [comment]
Organism created: https://hardwoodgenomics.org/bio_data/4302783?tripal_pane=group_summary_tripalpane
* Deleted

Old Organism: https://hardwoodgenomics.org/organism/Hydrangea/macrophylla?tripal_pane=group_summary_tripalpane

**Comment by RaymondS1** [comment]
Swissprot
```
#PBS -N swissprot_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=12:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/raw_data/BLAST_splits/HMA_r1.2_1.cds.fasta.$PBS_ARRAYID \
 -db /lustre/haven/proj/UTK0032/library/uniprot/uniprot_sprot.fasta \
 -out /lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/BLAST/swissprot/macrophylla_swissprot.$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by RaymondS1** [comment]
Trembl
```
#PBS -N trembl_BLAST
#PBS -S /bin/bash
#PBS -j oe
#PBS -A ACF-UTK0011
#PBS -t 1-200
#PBS -l nodes=1:ppn=2
#PBS -l walltime=12:00:00

cd $PBS_O_WORKDIR

module load blast

blastx \
 -query /lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/raw_data/BLAST_splits/HMA_r1.2_1.cds.fasta.$PBS_ARRAYID \
 -db /lustre/haven/proj/UTK0032/library/uniprot/uniprot_trembl_plants_July_2018.fasta \
 -out /lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/BLAST/trembl/macrophylla_trembl.$PBS_ARRAYID.xml \
 -evalue 1e-5 \
 -outfmt 5
```

**Comment by RaymondS1** [comment]
IPS 

```
#PBS -N hydrangea_ips
#PBS -A ACF-UTK0011
#PBS -S /bin/bash
#PBS -t 1-500
#PBS -j oe
#PBS -l nodes=1:ppn=4
#PBS -l walltime=18:00:00

cd $PBS_O_WORKDIR

module load python3

/lustre/haven/proj/UTK0032/software/interproscan-5.34-73.0/interproscan.sh \
 -i /lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/raw_data/IPS_splits/HMA_r1.2_1.protein.fasta.$PBS_ARRAYID \
 -f XML \
 -d /lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/IPS/xmls \
 --disable-precalc \
 --iprlookup \
 --goterms \
 --pathways \
 --tempdir /lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/IPS/TMP \
 > /lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/IPS/TMP/$PBS_ARRAYID.out
```

**Comment by RaymondS1** [comment]
Publication Created
https://hardwoodgenomics.org/Publication/4302784

**Comment by RaymondS1** [comment]
Reference Genome
https://hardwoodgenomics.org/Genome-assembly/4302785

**Comment by RaymondS1** [comment]
Files to be loaded to the site

CDS: 
```/lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/raw_data```

Protein: 
```/lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/raw_data/HMA_r1.2_1.protein.fasta```

Swissprot 
```/lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/BLAST/swissprot/xml```

Trembl
```/lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/BLAST/trembl/xml```

IPS
```/lustre/haven/proj/UTK0032/projects/undergrads/hydrangea_macrophylla/IPS/xmls```

**Comment by florence-77** [comment]
FTP downloads available at https://hardwoodgenomics.org/Genome-assembly/4302785?tripal_pane=group_downloads
