### ISSUE TITLE
Should Polypeptides get removed?

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#64]
Given that all the info for the Polypeptide is stored twice, once in mRNA/mRNA_contig and again in Polypeptide entities. Should we delete them?

@bradfordcondon suggests that it might be easier for users to select polypeptides if they want the protein sequences instead of guessing that it'd appear under mRNA.

**Comment by almasaeed2010** [comment]
Delete the entities and a label in collections.

**Comment by bradfordcondon** [comment]
Polypeptide bundle deleted.

We will still support AA fasta donwloads via fields.

**Comment by almasaeed2010** [comment]
We have 2 options to do this.
1- By changing the bundle name (for example, mRNA/Polypeptide)
2- Making elasticsearch change the name of the "Type" when displaying results.

Which one do you prefer?

**Comment by almasaeed2010** [comment]
The ES options means hardcoding the suffix though which means might not be compatible with all sites that use the module

**Comment by almasaeed2010** [comment]
I oughta get know the WS module a but more but I think this isn't an issue

**Comment by bradfordcondon** [comment]
i think we figured "when there are instructions for this we'll look into it more" and i stand by that decision.

I know that our fields need work to be WS compatible (put stuff in the `elements` format) but without instructions just wasnt worth figuring out...

**Comment by bradfordcondon** [comment]
I've renamed mrna and mrna_contig to mrna/polypeptide etc.

Assuming ES pulls the bundle **label** then we'll be all set.

**Comment by bradfordcondon** [comment]
Confirmed.

Once site **reindex** this will be all set.  Closing issue.
