### ISSUE TITLE
Move libraries field to tripal_manage_analyses

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#65]

**Comment by bradfordcondon** [comment]
https://github.com/statonlab/ero__nucleic_acid_library

**Comment by bradfordcondon** [comment]
see #26 for full discussion

**Comment by almasaeed2010** [comment]
putting the field's repo here for reference https://github.com/statonlab/ero__nucleic_acid_library

**Comment by bradfordcondon** [comment]
Moved and enabled on dev.
