### ISSUE TITLE
Create Genome Tab

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#66]
Probably need a field for this

**Comment by bradfordcondon** [comment]
* Would attach on Organism.
* Would display transcriptome link and/or genome assembly link?

**Comment by almasaeed2010** [comment]
> Would display transcriptome link and/or genome assembly link?

genomes assembly


this brings back the idea of switching the genome pages we have in http://160.36.205.61:8095/genomes to genome assembly analyses

**Comment by bradfordcondon** [comment]
We could write one field that changes the label depending on which bundle its attached to.  It says "Genome" when attached to genome assembly, "Transcriptome" when attached to transcriptome assembly.

We would then have the analysis field exclude the genome/transcript analysis from its display. Or, leave the analysis there and have the genome/transcriptome tab have something other than the analysis (a text description instead?)

**Comment by almasaeed2010** [comment]
Unfortunately, TripalPanes don't give us that much liberty or if they do, it's not documented and I have no clue how to do it. We could explore the functions in their api and see what's available though.

**Comment by bradfordcondon** [comment]
Look at our declaration in `tripal_manage_analyses_bundle_instances_info`.


```php
  if (isset($bundle->data_table) AND ($bundle->data_table == 'organism')) {
....//more code...
$field_type = 'local__analysis_browser';
    $instances[$field_name] = [
      'field_name' => $field_name,
      'entity_type' => $entity_type,
      'bundle' => $bundle->name,
      **'label' => 'Analyses',**
 ```
Set the label depending on which bundle you are attaching to.  should be as simple as that.

**Comment by bradfordcondon** [comment]
This is implemented.
