### ISSUE TITLE
Add organism common name to feature pages

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#74]
Find out if we need to create a field to display the organism common name in feature pages. This is critical to allow elasticsearch to recognize features related to that organism.

**Comment by bradfordcondon** [comment]
Linking back to organism from features is critical because of #75  as well

**Comment by bradfordcondon** [comment]
I think this was resolved by setting the *label* of the obi__organism field.

**Comment by almasaeed2010** [comment]
Tested and works 👍
