### ISSUE TITLE
 Make sure all entities link back to organism if thats the hub

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#75]
Right now, organism is the hub for everything for the user.

Therefore every entity should link back to organism.

**Comment by bradfordcondon** [comment]
## Entities that will need to link back

- [x] Biosample

- [ ] Drupal pages (if we continue to use them ,for example, this [chestnut genome page](http://160.36.205.61:8095/chinese-chestnut-genome)

- [ ] Analysis: blast evidence

- [ ] Analysis: Genome/Transcriptome

- [ ] library

Note: we want to use the common name instead I think?  see #74

**Comment by bradfordcondon** [comment]
We *already have* an analysis_organism mview.

Guess what: that's a linker table!

In theory all we have to do is attach the EXISTING obi__organism field to analysis.  If it doesnt auto-detect and make it work all nice, then that's an issue we can submit to core.

**Comment by almasaeed2010** [comment]
I thought this mview only connects analyses if a feature is associated with the analysis. So if we want to get analyses that don't use the FASTA loader (like blast and interpro), they won't be in this mview. Is that right or am I misunderstanding?

**Comment by almasaeed2010** [comment]
A quick check in that table to see if there is an analysis that's not genome assembly or transcriptome assembly show make this clear I guess

**Comment by bradfordcondon** [comment]
thats how the mview works.

here's the thing: if we attach the obi__organism linker to, say, the blast analysis bundle... when you create a new blast analysis entity, guess what?   the linker will be there!

**Comment by almasaeed2010** [comment]
That's good to know!

**Comment by bradfordcondon** [comment]
I think I see your point: other analyses didn't insert into the organism_analysis linker table.

newly created analyses will.

we can manually edit the entity once we attach the field.  or we can sql to insert into it for existing analyse

**Comment by bradfordcondon** [comment]
linker created ( see #93 ).

We will want to create a library linker too, but frankly, we dont really use library.  I'll say it "would be nice" and move on.
