### ISSUE TITLE
hwd site theme issue for tripal galaxy webform fields

### ISSUE THREAD

**Issue by MingChen0919** [statonlab/hardwoods_site#77]
Some webform fields are not themed correctly in our HWG site theme.  
Specifically, some field titles are not bolded. field values are not nested within the corresponding field titles. 
See the screenshot below. The one on the right is the default, and it's correct. 

<img width="1122" alt="screen shot 2018-01-10 at 1 14 09 pm" src="https://user-images.githubusercontent.com/1262709/34796313-fd92acac-f609-11e7-8b14-ae4f3b82c863.png">

**Comment by MingChen0919** [comment]
Since this is a HWG theme issue, I need Abdullah's help on this:)

**Comment by almasaeed2010** [comment]
If at all possible, could you provide the code snippet that creates this form?

Thanks!

**Comment by MingChen0919** [comment]
I'll need to ask Connor, I forgot this yesterday. Remind me if I forget again.

**Comment by MingChen0919** [comment]
hi @almasaeed2010, those incorrectly themed texts/titles/labels belong to the type of `fixed_value`. I think here is the code that renders `fixed_value` elements. https://github.com/tripal/tripal_galaxy/blob/7.x-1.x/includes/components/tripal_galaxy.fixed_value.inc#L80-L87.

**Comment by almasaeed2010** [comment]
I can't find the rendered html to be able to style it. In which workflow and step does this issue arise?

**Comment by MingChen0919** [comment]
it arises at all workflows as long the webform component is `fixed_value`. It is a custom form element defined by tripal galaxy module to render fixed values from workflows. see the WGCNA workflow **Step 2** as an example: http://160.36.205.61:8095/content/wgcna-analysis.

Here is the component type defined in the webform data: https://github.com/statonlab/dibbs/blob/master/annotated-tripal-galaxy-workflows/wgcna.json#L266

please let me know if you need more info, or maybe discuss in person?

**Comment by almasaeed2010** [comment]
Fixed in both live and dev. @MingChen0919 could you please verify the issue is fixed and close this if so?

**Comment by MingChen0919** [comment]
confirmed. thanks!
