### ISSUE TITLE
Can we develop a behavior diagram?

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#85]
It'd be helpful for us to develop a behavior flow diagram describing how we imagine users interact with our site and tools.

- Identify landing pages
  - https://analytics.google.com/analytics/web/?et=reset&hl=en#report/content-engagement-flow/a24308494w47463836p47798157/
  - If the link above doesn't work, go to google analytics and select **Behavior** from the left sidebar > **Behavior Flow**
- Find out how people find us
  - https://analytics.google.com/analytics/web/?et=reset&hl=en#report/content-engagement-flow/a24308494w47463836p47798157/%3F_r.dimension%3Danalytics.source/
  - **Behavior** > **Behavior Flow**  and select *Acquisition > Source*  from the dropdown above the chart

------------------
### Notes

**Most users land in our home page.** To utilize this, we should provide more information on the home page as to what services we provide and make them easier to access. The second most popular landing page is [Chinese Chestnut Genome](https://www.hardwoodgenomics.org/chinese-chestnut-genome). 68% of users exit the page immediately after landing on this page. What could we offer to appeal to the user looking for Chinese Chestnut Genome?

**Most users find us through Google.** Using short paragraphs rather than short (almost-) sentences increase our chances of users finding keywords in our home page via Google. Can we repurpose the homepage to guide users to tools and other useful pages on the site? What could we characterize as useful past the home page?

**Comment by almasaeed2010** [comment]
Do we have "Goals" (things users are expected to do/achieve in the site) that we can identify and track?

**Comment by almasaeed2010** [comment]
Can we develop help material designed for users? A FAQ, for example, could help users find a starting point on the site.

**Comment by bradfordcondon** [comment]
@almasaeed2010 any tools/question worksheetes you're aware of to help people design site behavior flow diagrams?

**Comment by almasaeed2010** [comment]
I normally sketch a diagram using good old pen and paper :) 

The main thing we want to establish here is figuring out what steps should a user take to accomplish a certain task or complete an action.

Questions to answer:
- Which page is the user starting from?
- What tools should they be aware of on that page?
- How can we guide the user to reach the next page?
- What can we identify as a "Goal" on that page (which will allow us to track interactions leading to it).

**Comment by bradfordcondon** [comment]
Old usage diagram:

<img width="876" alt="screen shot 2018-01-19 at 11 54 18 am" src="https://user-images.githubusercontent.com/7063154/35161886-8c770d58-fd0f-11e7-85fa-6275a3ff22be.png">

Proposed new usage:

<img width="978" alt="screen shot 2018-01-19 at 11 54 24 am" src="https://user-images.githubusercontent.com/7063154/35161884-898d4760-fd0f-11e7-9da0-031ea2538540.png">


>*What are our most prominent page types and what benefits do they offer to users?*
We are assuming that users want to look at a specific organism.  They want to then, in order of priority, a) read the overview, b) download the data, c) dive deep by using specific tools.  d) the details of analyses ie blast annotation parameters are nice to put up but waaaaay down the UX list.

>Which page is the user starting from?
>What tools should they be aware of on that page?
>How can we guide the user to reach the next page?
Google is telling us the landing page is where most users start.
Therefore I want to focus the landing page on getting users to the right organism quickly, either via organism list or, by picking a tool and seeing what tool they can use with that organism.

>What can we identify as a "Goal" on that page (which will allow us to track interactions leading to it).
Clicking through to an organism.

It sounds like I should answer those questions not just for the landing but again for organism...

**Comment by bradfordcondon** [comment]
h1 improvements:

Sentence composed of keywords we want to promote.

**Comment by bradfordcondon** [comment]
I'm closing this issue but will create a new H1/KEYWORDS issue
