### ISSUE TITLE
Elasticsearch Faceted Searching 

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#87]
What does that entail? 
- Rebuilding entities index to hold field information information (converting simple arrays to complex objects)
- Building an advanced search interface/page
- How would all of this look like?

How important/urgent is implementing this feature compared to other matters given that this is requested by the core tripal team and added in [DIBBs TODO](https://docs.google.com/document/d/1qODYrQNsFjitKD_tddx8OR6eKsx6bjiPJ04V7ukyCD0/edit#heading=h.kh6a4eq20m02).

**Comment by bradfordcondon** [comment]
Conclusion:

lots of work (2 weeks +) to implement a la NCBI.  Too much work.

Present keywords as compromise?
