### ISSUE TITLE
when blast fails on site, we want to be notified

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#91]
we dont know when blast goes down.

can we havea daily job that runs to test?

@almasaeed2010 suggests we change the exit status of the tripal_job so that the error will get picked up

**Comment by almasaeed2010** [comment]
Tried doing this using sendmail (with spf and dkim config) and mailx but both didn't deliver to my inbox. My suggestion is to create a Mailgun domail and write a small (10 line) script to handle errors.

Note: to detect job errors use `||` to pipe any exit code other than 0. Example `drush trp-run-jobs --username=user || php send_errors.php < /var/log_file`

For a php script to send mail with mailgun, see https://www.mailgun.com/

**Comment by almasaeed2010** [comment]
On that note, why not create a new "contact us" module that uses mailgun? This takes away all the messy server configuration that goes into building a mail server and ensures that emails get delivered to our inboxes.

**Comment by bradfordcondon** [comment]
creating such a module wouldn't also imrpove the emails going to spam issue would it?

**Comment by almasaeed2010** [comment]
UPDATE:

We are now using the [mailgun module](https://www.drupal.org/project/mailgun) to send mail from the server. We'll have to implement a drush command that uses their API to send mail. That's the best way I can think of to do this.

**Comment by bradfordcondon** [comment]
is it possible to have a daily job that runs and emails if it fails?

**Comment by almasaeed2010** [comment]
I am not sure I understand. Could you please clarify?

**Comment by bradfordcondon** [comment]
so you said `drush trp-run-jobs --username=user || php send_errors.php < /var/log_file` will pipe the job errors to a log.

Can we schedule a blast job that runs every 24 hours.  And then if there are errors sent to the log file, we get a mail notification.

we dont need to monitor every singel blast job.  users will likely submit blast jobs that error all the time (submitting a protein sequence to nucleotide blast for example).  Instead we just have a basic blast job that runs.  and if something is wrong (the file permissions dont allow the file to be created, whatever) we get notified

**Comment by almasaeed2010** [comment]
Well this handles more than just blast. We'll also need to monitor galaxy, for example.

**Comment by almasaeed2010** [comment]
Done on live using the mail_cli module.

On our wiki we have [a post explaining how we utilize mail_cli to collect logs and how schedule sending them once a day](https://github.com/mestato/statonlabprivate/wiki/Daily-Tripal-Jobs-Error-Report).
