### ISSUE TITLE
implement cv-browser

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#95]
* Try out https://github.com/bradfordcondon/tripal_cvb
* Make plan for Tripal 3 implementation
* Determine what features we would want to add if any

**Comment by bradfordcondon** [comment]
with a minor patch, tripal_cvb works just fine.  Below is an example on my dev site looking at the molecular function cv.  (i actually root it at the molecular_function cvterm root, because the molecular function root level has about 20 terms, 19 of which are "Deprecated[something]" and the 20th is molecular function, so we'll want to start from the root term instead.

![screen shot 2018-01-19 at 3 01 49 pm](https://user-images.githubusercontent.com/7063154/35169258-e836ef04-fd29-11e7-80dc-45f35f8feff6.png)

**Comment by almasaeed2010** [comment]
I think this can be closed in favor of #214
