### ISSUE TITLE
Error from field bug: array_design module

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_site#96]
## Bug
```
User warning: The following module is missing from the file system: tripal_arraydesign. For information about how to fix this, see the documentation page. in _drupal_trigger_error_with_delayed_logging() (line 1143 of /data/www/html/hardwoods_dev/drupal-7.52/includes/bootstrap.inc).

```

## Fix

array_design means it has something to do with the array_design bundle or field.  if its a field, then i'd bet that the `module` field variable is set to array_design and should be changed to the actual module (or tripal_chado)

**Comment by almasaeed2010** [comment]
Usually, this error only means that the path for the module has changed. I don't think we have tripal_arraydesign anymore (or if it ever existed, which is weird).

**Comment by bradfordcondon** [comment]
we didn't which is why i suspect a field is the problem.

probably tripal_protocol in tripal_analysis_expression

**Comment by almasaeed2010** [comment]
I am pretty positive it's not a field related issue. I encountered this several times before and it's always been solved by disabling the module somehow. We can try the doc's solution: https://www.drupal.org/node/2487215

**Comment by almasaeed2010** [comment]
Oh this section suggests you might be right "Leftover fields or other configuration entries"

**Comment by bradfordcondon** [comment]
yeah ;) I've gotten this error in relation to a relocated module... but in this case i'm pretty certain the module has never existed so i'm betting on the expression module. 

I dont see any fields referencing it as their module... but the protocol module has a bunch of functions named tripal_arraydesign_.... instead of tripal_protocol_....  maybe refactoring those will fix.

![screen shot 2018-01-22 at 10 52 34 am](https://user-images.githubusercontent.com/7063154/35229832-63d34024-ff62-11e7-9a6d-a40dadf43456.png)

**Comment by almasaeed2010** [comment]
Ok I give up. Looked into the DB for the module as suggested but can't find any references to it nor can I find any references to it in the code. There is something about views and it might make a difference if we just remove that code since it's not being used anymore.

**Comment by bradfordcondon** [comment]
shoot, where does this error appear?  Can't troubleshoot without that.
